import type { ResearchPost } from '../fleet-data';

const commonSources = [
  { name: 'National Privacy Commission: Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
  { name: 'Department of Labor and Employment: Labor Code', url: 'https://dole.gov.ph/labor-code-of-the-philippines-2/' },
  { name: 'Philippine Statistics Authority: QuickStat', url: 'https://psa.gov.ph/statistics/quickstat' },
  { name: 'Department of Trade and Industry', url: 'https://www.dti.gov.ph/' }
] as const;

const base = {
  readTime: '11 minute read',
  related: [{ label: 'Review support services', href: '/services' }, { label: 'Read the research library', href: '/research' }]
} as const;

export const august20ResearchPosts: readonly ResearchPost[] = [
  {
    ...base, published: 'August 20, 2026', datePublished: '2026-08-20', slug: 'philippines-article-research-evidence-desk-research-2026', title: 'What Evidence Should a Philippines Article Research Desk Preserve?',
    excerpt: 'A research question for FilipinoOutsource.com: which evidence trail lets a Philippines-based article research role prepare useful findings without blurring source, interpretation, and publication authority?', cluster: 'Research Operations',
    cardHighlight: 'A defensible article brief preserves the source, retrieval date, claim boundary, and editor decision separately.', heroImage: '/images/research-2026-08-20-article-evidence-desk.png',
    keyTakeaways: ['Source capture is not the same as fact checking or editorial approval.', 'A Philippines-based research role can preserve traceability while an editor retains the publication decision.', 'A useful evidence trail records uncertainty instead of polishing it away.'],
    stats: [{ label: 'Evidence layers', value: '4', width: 72 }, { label: 'External sources', value: '4', width: 84 }, { label: 'Owner decisions', value: '3', width: 60 }], graphicCaption: 'The evidence desk separates retrieval, interpretation, drafting, and editorial authority.',
    sections: [
      { heading: 'Research question: what makes an article evidence trail usable?', paragraphs: [
        'FilipinoOutsource.com serves businesses that need practical help with recurring operations, including research and content support. That makes article research a role-design question, not simply a request to collect links. The question is: what evidence should a Philippines-based article research desk preserve so an editor can inspect a claim before it becomes public?',
        'The answer is a chain of custody for meaning. A researcher records what a source actually says, where it says it, when it was retrieved, and what the proposed article infers from it. The editor then decides whether the inference is fair, relevant to the audience, and ready to publish. Keeping those acts separate protects both the article and the person doing the preparation.',
        'This is analysis for a bounded support role. It does not claim that a source makes an article true by association, or that a research worker can substitute for subject-matter review.'
      ]},
      { heading: 'What the public sources establish', paragraphs: [
        'The National Privacy Commission""s text of the Data Privacy Act describes transparency, legitimate purpose, proportionality, accuracy, and retention as general principles for personal information processing. Those are useful control ideas for an article desk when research notes include names, contact details, customer examples, or other personal data. The source does not prescribe a particular FilipinoOutsource.com workflow; that operational mapping is analysis.',
        'The Philippine Statistics Authority publishes official statistical releases and QuickStat tables. A statistics page can support a number, but the researcher still needs the indicator definition, period, unit, revision status, and geographic scope. A headline that drops those qualifiers may be numerically sourced yet editorially misleading.',
        'DOLE""s Labor Code publication and DTI""s public consumer-protection material demonstrate why an article about staffing or customer operations needs a clear jurisdiction and claim boundary. They are authoritative starting points, not permission to turn a support article into legal advice.'
      ]},
      { heading: 'The evidence record a researcher can prepare', paragraphs: [
        'For each proposed claim, the desk can preserve the exact source URL, page heading, retrieval date, relevant passage in a short paraphrase, and the claim it supports. It can label the claim as direct fact, contextual fact, interpretation, scenario, or open question. That label is more useful than a single "verified" flag because it shows what kind of editorial work remains.',
        'A second record captures scope: which population or process is represented, which is not, and whether a source is primary, secondary, or an organization""s explanation of a rule. A third records conflicts. If two sources use different definitions, the researcher should present the difference and route the decision rather than silently choose the more convenient number.',
        'The role may also prepare an evidence matrix that maps each planned section to a source and a decision owner. It should not approve a claim, invent a statistic, create a testimonial, or publish because a field is complete. Those are editorial or company-owner decisions.'
      ], bullets: ['Record source and retrieval context.', 'Separate source fact from article interpretation.', 'Mark conflicts and missing evidence.', 'Route publication judgment to the named editor.']},
      { heading: 'A worked scenario for a Philippines-based support role', paragraphs: [
        'Imagine an editor is preparing an article about access controls for a remote customer-support queue. The researcher finds a privacy principle, a labor reference, and a public operational example. The first draft note should not say "the law requires this exact queue design." It should say what the law states, what the example demonstrates, and what the article recommends as a cautious operating choice.',
        'The researcher can then test the note against four questions: Is the source about the Philippines or another jurisdiction? Is the date current enough for the claim? Does the source support the whole sentence or only one clause? Does the scenario disclose that it is an illustrative operating example? Any "no" belongs in the exception field.',
        'The editor can accept, narrow, replace, or remove the claim. That feedback becomes a useful training example, while the researcher remains accountable for a clear record rather than for the final editorial judgment.'
      ]},
      { heading: 'Limits of this research', paragraphs: [
        'The cited public materials do not measure a particular FilipinoOutsource.com team, a particular writer, or a particular article queue. They cannot prove faster publishing, stronger rankings, lower cost, or better conversion. Nor do they establish that every research task can be delegated safely. The article desk still depends on the client""s source list, review capacity, access design, and editorial standards.',
        'The model also does not resolve specialist questions. A legal, medical, financial, or technical claim may need qualified review even when the underlying source is public. A source record improves inspectability; it does not turn a generalist researcher into a licensed adviser.',
        'The evidence scope is therefore deliberately narrow: preserve the trail for ordinary research and stop when authority, sensitivity, or consequence exceeds the written role.'
      ]},
      { heading: 'Evidence-led conclusion', paragraphs: [
        'The strongest evidence trail for a Philippines article research desk has four separable layers: source retrieval, claim description, operational interpretation, and editorial decision. That separation lets a support role prepare organized material without claiming authority it does not have.',
        'For FilipinoOutsource.com buyers, the practical test is not how many links a desk can collect. It is whether an editor can reconstruct why a sentence was proposed, see its limitations, identify unresolved conflicts, and make a timely decision. Begin with a small set of recurring article questions, preserve the four layers, sample the records, and expand only when corrections are understandable.'
      ]}
    ], methodology: 'Desk research used the National Privacy Commission, DOLE, PSA, and DTI public materials as claim-relevant context. The operational recommendations are analysis for a bounded FilipinoOutsource.com research-support role; they are not legal, labor, or editorial guarantees.', faq: [{ q: 'Can a researcher approve publication?', a: 'No. The researcher can preserve evidence and route an editorial recommendation; the named editor retains publication authority.' }, { q: 'What should be measured first?', a: 'Measure traceable claims, correction reasons, unresolved-source rate, and editor review effort.' }], sources: commonSources
  },
  {
    ...base, published: 'August 20, 2026', datePublished: '2026-08-20', slug: 'philippines-remote-staffing-handoff-research-2026', title: 'When Does a Philippines Remote Staffing Handoff Preserve Accountability?',
    excerpt: 'Research for FilipinoOutsource.com on whether a Philippines-based support handoff transfers work cleanly while keeping approval, exception, and publishing decisions with the right owner.', cluster: 'Remote Operations',
    cardHighlight: 'A handoff is accountable when the receiving role gets a defined output, evidence context, and stop rule, not just a task name.', heroImage: '/images/research-2026-08-20-remote-handoff.png',
    keyTakeaways: ['Handoffs fail when ownership is implied rather than recorded.', 'The receiving role needs a bounded output and an escalation trigger.', 'Completion counts are weaker evidence than reviewable records.'],
    stats: [{ label: 'Handoff fields', value: '5', width: 80 }, { label: 'Stop conditions', value: '4', width: 68 }, { label: 'Review owners', value: '1', width: 52 }], graphicCaption: 'A handoff connects an input, expected output, evidence, stop rule, and named owner.',
    sections: [
      { heading: 'Research question: what must cross the handoff?', paragraphs: ['FilipinoOutsource.com""s niche is helping businesses define recurring work for Philippines-based support. In that setting, a handoff is more than sending a message in a chat channel. The research question is whether the next person can understand the request, inspect its evidence, complete the permitted preparation, and know exactly where authority stops.', 'A good handoff transfers context and accountability together. It names the source record, the desired output, the due window, the decision still owned by the client, and the condition that requires escalation. A vague instruction such as """handle this customer issue""" transfers anxiety, not work.', 'This distinction matters for distributed teams because time-zone continuity can make an incomplete record look finished. The next shift may move the item forward while losing the uncertainty that should have reached an owner.'],},
      { heading: 'Evidence scope and method', paragraphs: ['This analysis compares general principles in four public sources with a bounded support scenario. The Data Privacy Act supplies a lens for purpose, proportionality, accuracy, and lawful processing. DOLE""s Labor Code publication supplies labor context but does not define a client""s internal handoff. PSA supplies a reminder that definitions and periods matter in official data. DTI supplies consumer-facing context for records that affect customer communication.', 'The unit of analysis is one handoff record, not worker productivity or market size. A record is considered inspectable when another authorized person can identify the request, source, work performed, unresolved question, and next owner without reconstructing the conversation from memory.', 'This method distinguishes facts from analysis. The public sources are facts about their published material; the five-field handoff model is an operational recommendation for FilipinoOutsource.com buyers.'],},
      { heading: 'Why ownership disappears in ordinary queues', paragraphs: ['Ownership commonly disappears in three places. First, a request arrives through an informal channel and has no durable identifier. Second, the worker completes a preparation step but the note says """done""" rather than describing what was checked. Third, an exception is treated as a delay instead of a decision that belongs to someone else.', 'A Philippines-based coordinator can improve the record by assigning a neutral state such as received, evidence collected, clarification needed, owner review, or closed by owner. These states do not pretend that every queue is identical; they make the change in responsibility visible.', 'The coordinator may normalize approved fields, attach an existing source, prepare a draft response from approved language, and route a question. The coordinator should not approve refunds, interpret a contract, disclose sensitive information, or publish a consequential claim simply because the request is old.'], bullets: ['Identifier and source.', 'Expected deliverable.', 'Evidence checked.', 'Stop condition and owner.']},
      { heading: 'The handoff test in a realistic case', paragraphs: ['Consider a customer-support article team that asks a Philippines-based researcher to investigate a recurring question. The request says which audience the article serves, links to the approved source set, and asks for a two-paragraph evidence note. The researcher finds conflicting definitions in two official pages. A weak handoff says """sources disagree.""" A strong one identifies the exact terms, gives each page""s date and scope, and routes the choice to the editor.', 'The receiving role has still added value: the evidence is organized and the conflict is legible. The editor retains the decision because selecting a definition changes the article""s meaning. If the chosen definition is later challenged, the record shows why it was used.', 'The same logic applies to support queues outside publishing. A worker can prepare a comparison or schedule a next step while leaving policy, entitlement, access, and employment decisions with the named client owner.'],},
      { heading: 'What to measure before expanding the lane', paragraphs: ['Measure the percentage of handoffs with a durable identifier, a source, a clear output, and an owner. Sample the exceptions rather than only the completed items. Ask whether the receiving person could explain the record without opening the original chat, and whether the owner could decide without requesting the same evidence again.', 'Do not interpret a high completion count as proof that the lane is safe. A queue can be fast because people are guessing or because exceptions are being hidden. Review correction reasons, repeated clarification requests, unauthorized access attempts, and the age of unresolved decisions.', 'The point of measurement is learning. If the same field is missing, improve the intake instruction. If the same decision is escalated, clarify the role boundary. If the same source conflict appears, assign an editorial owner rather than asking support to settle it invisibly.'],},
      { heading: 'Conclusion and limitations', paragraphs: ['The evidence supports a narrow conclusion: a Philippines remote staffing handoff preserves accountability when it carries the record, expected output, evidence context, stop rule, and named owner together. This is a design property of the workflow, not a claim about any worker or provider.', 'The public sources do not measure this handoff model, and the model does not guarantee quality, speed, savings, or compliance. Client policy, access configuration, manager availability, and the nature of the queue remain decisive. Sensitive and irreversible actions require additional review.', 'Start with one recurring lane, inspect real handoffs, and expand only when a second person can understand the work and the owner can see what still needs deciding.']}
    ], methodology: 'The article applies four public Philippine sources to a record-level handoff analysis. The five-field model and scenario are operational analysis, not a claim that any regulator endorses a particular outsourcing workflow.', faq: [{ q: 'Does a handoff transfer decision authority?', a: 'No. It transfers a defined preparation or coordination output; the client owner keeps approvals and consequential judgment.' }, { q: 'What is the first useful measure?', a: 'Sample whether another authorized person can reconstruct the handoff without searching informal messages.' }], sources: commonSources
  },
  {
    ...base, published: 'August 20, 2026', datePublished: '2026-08-20', slug: 'philippines-customer-support-knowledge-accuracy-research-2026', title: 'How Should Philippines Customer Support Knowledge Accuracy Be Tested?',
    excerpt: 'A source-bounded study of knowledge-base accuracy for Philippines-based customer support: what can be checked, what needs owner review, and where a support role must stop.', cluster: 'Customer Support',
    cardHighlight: 'Accuracy is not just a correct sentence; it is a current, scoped answer tied to an approved source and escalation path.', heroImage: '/images/research-2026-08-20-knowledge-accuracy.png',
    keyTakeaways: ['A knowledge article needs a source, scope, effective date, and owner.', 'Support can identify stale or conflicting content without deciding policy.', 'Sampling edge cases reveals more than counting article views.'],
    stats: [{ label: 'Accuracy dimensions', value: '4', width: 76 }, { label: 'Review states', value: '5', width: 82 }, { label: 'Owner gates', value: '2', width: 56 }], graphicCaption: 'Knowledge accuracy combines correctness, currency, scope, and safe escalation.',
    sections: [
      { heading: 'Question and decision context', paragraphs: ['For a business using Philippines-based customer support, knowledge accuracy is a delegation problem. The question is not merely whether a support worker can read an article. It is how a team tests whether the article is correct for the customer""s situation, current for the relevant policy, and safe to use when a case falls outside the written rule.', 'FilipinoOutsource.com""s service context makes the boundary concrete: a support role may search approved material, match a routine request to an approved answer, note a missing condition, and route an exception. It should not invent a promise, infer an entitlement, or turn a stale page into a new policy.', 'Accuracy therefore has four dimensions: factual correctness, currency, scope, and escalation behavior. Each can be sampled separately.'],},
      { heading: 'Evidence from public authorities', paragraphs: ['The Data Privacy Act""s principles of transparency, legitimate purpose, proportionality, and accuracy are directly relevant when a knowledge workflow handles personal information. They support minimization and careful use; they do not provide a script for every customer case.', 'DTI""s consumer-facing role illustrates why claims about products, conditions, and customer remedies need an accountable source. A public agency page can inform the research lens, but a business must still identify its own approved policy and the owner authorized to change it.', 'PSA""s statistical publications demonstrate another accuracy issue: a number has a definition, period, unit, and revision context. A customer article that repeats a number without those qualifiers can be technically sourced and practically misleading. DOLE""s Labor Code is included as a boundary reminder for employment-related support content: interpretation belongs with an appropriately authorized owner.'],},
      { heading: 'A four-part accuracy protocol', paragraphs: ['First, test the answer against its source. The reviewer records the source title, effective date if available, and the sentence or rule being applied. Second, test scope: which product, customer type, region, channel, or time period does the answer cover? Third, test currency by checking for a newer approved document or a known review date. Fourth, test the stop rule with a case that is close to, but not inside, the normal path.', 'A Philippines-based knowledge coordinator can run these comparisons and classify the result as confirmed, stale, unclear, conflicting, or owner decision. That classification keeps uncertainty visible. It also gives an editor or support manager a queue that can be prioritized by customer impact rather than by whoever complained most recently.', 'The coordinator should not rewrite a policy while performing the test. A proposed wording change can be attached as a recommendation, but the existing owner decides whether it is accurate and publishable.'], bullets: ['Correct against an approved source.', 'Check effective date and scope.', 'Test a boundary case.', 'Route policy changes.']},
      { heading: 'Why edge cases are the research sample', paragraphs: ['Routine cases often conceal knowledge defects because the answer is obvious from context. Edge cases show where a rule changes. Sample a normal question, a missing-information question, a conflicting-source question, a request involving personal data, and a request that could change an entitlement or commitment.', 'For each case, record what the article allowed the worker to say, what additional evidence was needed, and where the case was routed. The goal is not to force every case into a script. It is to discover whether the script exposes its own limits.', 'A knowledge article can be accurate in isolation yet unsafe in use. If its heading is broad but its rule applies to one product, the problem is scope. If its source is correct but its effective date is unknown, the problem is currency. If its answer is correct but invites a private-data disclosure, the problem is operational fit.'],},
      { heading: 'Measures and limitations', paragraphs: ['Useful measures include source-match rate, stale-content findings, scope corrections, edge-case escalation quality, and owner review time. Avoid a single """accuracy percentage""" unless the team defines what counts as an error and who adjudicates borderline cases. The record behind the measure matters more than the number on a dashboard.', 'The public sources do not measure a specific knowledge base, customer population, or support team. They cannot prove a particular answer is compliant, commercially effective, or suitable for every jurisdiction. A client""s own policy, contracts, product changes, and privacy instructions remain controlling.', 'This research also does not imply that a remote support role should make clinical, legal, financial, employment, or policy decisions. It describes a way to test written material and route questions within a bounded role.'],},
      { heading: 'Evidence-led conclusion', paragraphs: ['The evidence supports testing knowledge accuracy as correctness, currency, scope, and escalation, not as a count of articles or views. A Philippines-based support role can make that test repeatable by preserving the source, date, case type, observed gap, and owner decision.', 'For FilipinoOutsource.com buyers, the safest first lane is a narrow knowledge set with an identified owner and a sample that includes edge cases. Expand only when the team can explain why an answer is valid, when it is not, and how a change is approved.']}
    ], methodology: 'This research uses NPC, DTI, PSA, and DOLE public material to define an evidence lens. The accuracy protocol is operational analysis for customer-support planning and does not constitute legal, labor, or consumer-protection advice.', faq: [{ q: 'Can support staff change a policy article?', a: 'They can flag a gap and prepare a proposed edit; the authorized owner approves the policy and publication.' }, { q: 'What cases should be sampled?', a: 'Include ordinary, incomplete, conflicting, sensitive-data, and entitlement-changing cases.' }], sources: commonSources
  },
  {
    ...base, published: 'August 20, 2026', datePublished: '2026-08-20', slug: 'philippines-outsourced-data-retention-research-2026', title: 'What Should a Philippines Outsourced Data Retention Review Prove?',
    excerpt: 'Research for FilipinoOutsource.com on retention reviews: how a Philippines-based operations role can inventory records and route deletion decisions without making unsupported compliance claims.', cluster: 'Data Operations',
    cardHighlight: 'A retention review proves what exists, why it is held, who owns the decision, and what remains uncertain.', heroImage: '/images/research-2026-08-20-data-retention.png',
    keyTakeaways: ['Retention is a purpose and ownership question, not just a storage question.', 'An inventory can be delegated; deletion authority must be explicit.', 'The review should document exceptions and legal or business holds.'],
    stats: [{ label: 'Review questions', value: '6', width: 88 }, { label: 'Retention states', value: '5', width: 76 }, { label: 'Deletion owner', value: '1', width: 48 }], graphicCaption: 'A retention review links record inventory to purpose, authority, exception, and action.',
    sections: [
      { heading: 'Research question: what can an inventory prove?', paragraphs: ['Businesses planning Philippines-based support often begin a data-retention question with a spreadsheet: which records exist, where are they stored, and when can they be removed? The deeper question is what the review must prove before anyone changes or deletes a record.', 'For FilipinoOutsource.com, a bounded operations role can inventory approved systems, normalize record categories, identify apparent dates, and flag duplicates or missing owners. It cannot decide that a record is legally disposable because its age looks high. Retention can depend on purpose, contract, a dispute, a tax or labor requirement, a customer request, or an internal hold.', 'The review should therefore establish facts and route decisions. That is slower than a blind cleanup and safer than treating age as authority.'],},
      { heading: 'Method and evidence boundary', paragraphs: ['The Data Privacy Act is the central source because its general principles include specified purpose, accuracy, proportionality, and retaining personal information only as long as necessary for the relevant purpose or other lawful basis. The statute supplies a principle, not a universal retention calendar for every business record.', 'DOLE""s Labor Code publication is relevant when employee or applicant records appear in the inventory. PSA and DTI are included as independent public authorities that help distinguish official record context from a client""s own retention policy. None of these sources determines the policy of a particular company.', 'The method is record-level desk research: inspect a sample, identify the record category and stated purpose, note the apparent owner and date, flag exceptions, and route the decision. Facts from the sources remain distinct from the recommended workflow.'],},
      { heading: 'The retention review ledger', paragraphs: ['A useful ledger has a stable record identifier, category, system, data subjects if known, stated purpose, source of the retention rule, apparent creation or last-use date, access owner, hold indicator, and next action. """Delete""" should not be a default value. Use states such as inventory confirmed, purpose unclear, owner needed, hold suspected, review approved, and action recorded.', 'A Philippines-based coordinator can fill fields from approved systems, compare duplicate records, request missing policy references, and produce a review queue. The coordinator can also preserve an evidence snapshot so an owner sees why a record was flagged. If the source systems contain sensitive personal information, access must be limited to the minimum necessary view.', 'Deletion, anonymization, legal interpretation, and changing a retention policy belong to the authorized client owner. The support role""s boundary is especially important when a cleanup action is irreversible.'], bullets: ['Inventory before action.', 'Tie each category to a purpose.', 'Flag holds and uncertainty.', 'Record the owner""s decision.']},
      { heading: 'A case where age misleads', paragraphs: ['Suppose an operations team finds an old applicant file in a shared drive. The file appears inactive, but the folder also contains a complaint correspondence and a note that an owner is reviewing a dispute. An age-only cleanup would treat the file as obsolete. A careful reviewer marks a potential hold, records the source path, and routes the question without opening more personal information than necessary.', 'The same pattern appears in customer records. A record may be old but still connected to a current service obligation; a newer copy may be redundant but not safely removable until the source of truth is confirmed. The inventory makes these cases visible, but it does not solve them by itself.', 'The useful output is a defensible queue: what was seen, what is known, what is uncertain, and who can authorize the next step.'],},
      { heading: 'What measurement can and cannot say', paragraphs: ['Measure inventory coverage, percentage with a named purpose, percentage with an owner, suspected duplicate rate, unresolved-hold rate, and time to resolve a review. Inspect the records behind each measure. A high coverage number may hide categories that the coordinator could not access, while a low unresolved rate may reflect premature deletion.', 'The cited sources do not validate a particular company""s retention schedule or prove compliance. They also do not support claims about cost reduction, storage savings, or risk elimination. Those outcomes depend on the organization""s systems, policies, legal advice, and execution.', 'The review should stop when the record category is unclear, a hold may apply, a sensitive field is involved, or the action would be irreversible without documented authority.'],},
      { heading: 'Evidence-led conclusion', paragraphs: ['A Philippines outsourced data-retention review should prove the inventory, purpose, source of the rule, apparent lifecycle, exception status, and decision owner. It should not pretend that a worker can infer deletion authority from age or a general public principle.', 'For FilipinoOutsource.com buyers, begin with one system and a narrow category. Test whether the ledger helps an owner make decisions without redoing the inventory. Expand only when access is appropriate, holds are visible, and every irreversible action has explicit authority.']}
    ], methodology: 'The research uses the National Privacy Commission""s Data Privacy Act text plus DOLE, PSA, and DTI public sources for context. Recommendations describe a bounded record-inventory role and do not set a legal retention schedule or provide compliance advice.', faq: [{ q: 'Can a coordinator delete old records?', a: 'Only if the client has explicitly authorized that action under a documented rule; otherwise the coordinator inventories and routes.' }, { q: 'What is the biggest review risk?', a: 'Treating age as authority while missing a purpose, owner, duplicate-source issue, or hold.' }], sources: commonSources
  },
  {
    ...base, published: 'August 20, 2026', datePublished: '2026-08-20', slug: 'philippines-back-office-exception-routing-research-2026', title: 'Can Philippines Back-Office Exception Routing Improve Review Without Hiding Risk?',
    excerpt: 'An evidence-led study of exception routing for Philippines-based back-office support: how to make unusual cases visible while keeping approvals and consequential decisions with the client.', cluster: 'Risk and Controls',
    cardHighlight: 'Exception quality depends on description and ownership, not on pushing every unusual case back into a normal queue.', heroImage: '/images/research-2026-08-20-exception-routing.png',
    keyTakeaways: ['An exception is a decision signal, not a failure to process.', 'Neutral descriptions reduce guessing and preserve review context.', 'Routing quality should be sampled by outcome, not just speed.'],
    stats: [{ label: 'Exception fields', value: '7', width: 92 }, { label: 'Routing states', value: '4', width: 68 }, { label: 'Owner gates', value: '2', width: 56 }], graphicCaption: 'Exception routing turns an irregular record into an owner-readable decision queue.',
    sections: [
      { heading: 'The question behind exception queues', paragraphs: ['A Philippines-based back-office role is often described with ordinary verbs: check, update, reconcile, schedule, or prepare. The risk appears when a record does not fit the ordinary path. The research question is whether exception routing can improve review without encouraging a worker to guess, conceal uncertainty, or turn an operational queue into an unauthorized decision desk.', 'For FilipinoOutsource.com, the answer depends on the quality of the exception record. A useful exception says what was expected, what was observed, which source was checked, what is missing or conflicting, and who owns the next decision. It does not label a customer, employee, vendor, or transaction as """bad""" without evidence.', 'The role""s value is making the unusual case legible. The owner""s value is deciding what the unusual case means.'],},
      { heading: 'Evidence and methodology', paragraphs: ['The National Privacy Commission""s principles frame careful handling of personal information and support a minimum-necessary approach to exception notes. DTI public material provides consumer-protection context for cases where an operational discrepancy may affect a customer. DOLE""s Labor Code publication matters when an exception touches employee records or workplace administration. PSA is used as a source-quality comparison because official statistics require definitions and scope.', 'The method studies a hypothetical record journey rather than claiming a benchmark. It asks whether a reviewer can distinguish a missing field from a conflicting source, a routine correction from an entitlement change, and a documentation issue from a policy decision.', 'The recommendations are analysis for a bounded Philippines-based support role. They do not assert that any public authority has endorsed the routing labels or that routing itself resolves the underlying risk.'],},
      { heading: 'Describe before you classify', paragraphs: ['A common failure is classifying too early. """Fraud,""" """urgent,""" """noncompliant,""" or """customer error""" can smuggle a conclusion into the first note. Start with observable facts: the invoice amount differs from the approved record; the address field is missing; the customer asks for an exception; two policy pages conflict; the access request lacks an owner.', 'The support role can preserve the source values, timestamp the check, identify the permitted next action, and route the question. It can use a neutral category such as source conflict, missing evidence, policy exception, sensitive-data concern, or owner approval. A client owner can then decide whether the case requires a correction, a communication, a hold, or a different process.', 'This separation is not bureaucratic decoration. It protects the record from becoming a permanent guess that later readers mistake for a fact.'], bullets: ['Describe observable evidence.', 'Name the expected rule or source.', 'State what cannot be concluded.', 'Route to a named owner.']},
      { heading: 'Routing an exception from a real workflow', paragraphs: ['Consider an ecommerce support queue where an order""s delivery status conflicts with the customer""s message. The coordinator may compare the approved tracking source, record the latest visible event, and note the discrepancy. The coordinator should not promise a refund, accuse a carrier, or invent a delivery date. The exception goes to the owner with the evidence and the permitted communication language.', 'In a research-content queue, the equivalent is a public statistic that has been revised or defined differently across sources. The researcher can show both definitions, identify the period, and suggest a narrower sentence. The editor decides which claim is fit for publication.', 'Across both examples, routing improves review only if it preserves the reason the case left the normal path. A label without evidence simply creates a faster-looking blind spot.'],},
      { heading: 'Testing routing quality', paragraphs: ['Measure whether exceptions contain the expected source, neutral description, missing evidence, impact context, next owner, and decision deadline. Then sample outcomes: was the route correct, did the owner have enough information, did the case return because the note guessed, and did the final decision get recorded?', 'Do not optimize only for time to route. A fast but vague escalation increases rework and may push the same risk into another queue. Look at repeated exception types and decide whether the written rule needs clarification, the source needs correction, or the role should remain narrow.', 'The public sources cannot supply a universal severity model. The client must define its own risk tolerance, approval paths, and response obligations.'],},
      { heading: 'Conclusion and limits', paragraphs: ['The evidence supports a bounded conclusion: exception routing improves review when it records observable facts, source context, uncertainty, permitted preparation, and a named owner. It hides risk when the route is a label that substitutes for evidence or when speed is rewarded over legibility.', 'A Philippines-based support role can prepare and route exceptions, but it should stop before approvals, policy interpretation, accusations, sensitive disclosures, or irreversible changes. Begin with one queue, sample ordinary and unusual cases, and expand only when the owner can understand why each case left the normal path.']}
    ], methodology: 'This study maps NPC, DTI, DOLE, and PSA public materials to a hypothetical exception-record analysis. The routing model is operational guidance for FilipinoOutsource.com planning, not a regulator-approved control or a guarantee of risk reduction.', faq: [{ q: 'Should a support role decide the exception?', a: 'It can document and route the exception; the client owner decides policy, entitlement, and other consequential outcomes.' }, { q: 'What proves routing quality?', a: 'A reviewer can see the source, observed discrepancy, uncertainty, owner, and recorded outcome.' }], sources: commonSources
  }
];
