const date = '2026-09-04' as const;

type Topic = { slug:string; title:string; excerpt:string; lane:string; owner:string; packet:string; boundary:string; caseStudy:string; metric:string };

const topics: readonly Topic[] = [
  {slug:'filipino-customer-credit-note-evidence-assistant',title:'How to scope Filipino customer credit note evidence support',excerpt:'Prepare a review-ready credit note packet without deciding eligibility, value, or accounting treatment.',lane:'customer credit note evidence',owner:'finance and customer-service owner',packet:'the request, invoice, delivery record, approved policy, prior remedy, tax detail, and correspondence',boundary:'issuing a credit, accepting liability, changing the ledger, or promising a customer outcome',caseStudy:'A customer asks for a full credit, but the delivery record shows only one line item was returned.',metric:'packets returned for missing invoice, policy, or delivery evidence'},
  {slug:'filipino-catalog-price-change-verification-coordinator',title:'How to plan Filipino catalog price change verification',excerpt:'Check proposed catalog prices against approved sources while commercial owners retain publishing authority.',lane:'catalog price change verification',owner:'ecommerce or commercial owner',packet:'the SKU, current price, proposed price, currency, approved source, effective window, channel, and requester',boundary:'setting a price, approving a promotion, interpreting a contract, or publishing a change',caseStudy:'The approved price sheet uses US dollars while the storefront draft is labeled in Australian dollars.',metric:'changes paused for currency, version, or approval conflicts'},
  {slug:'filipino-vendor-bank-detail-change-register-assistant',title:'How to scope Filipino vendor bank detail change register support',excerpt:'Organize bank-detail change evidence without verifying identity or authorizing payment instructions.',lane:'vendor bank detail change registration',owner:'procurement and finance owner',packet:'the vendor record, change request, known contact channel, verification state, approver, effective date, and audit history',boundary:'confirming identity, editing payment details, approving a vendor, or releasing funds',caseStudy:'A bank-change email arrives from a new domain two days before a scheduled payment.',metric:'requests held for independent verification or owner review'},
  {slug:'filipino-support-macro-version-control-assistant',title:'How to plan Filipino support macro version control',excerpt:'Maintain approved reply versions while policy and customer-remedy decisions remain with the client.',lane:'support macro version control',owner:'customer support policy owner',packet:'the macro name, approved wording, policy source, audience, channel, version, effective date, and retired text',boundary:'changing policy, inventing a remedy, publishing unapproved language, or restoring a retired response',caseStudy:'A current macro links to a policy page that was revised after the macro approval date.',metric:'macros with stale sources, duplicate versions, or missing owners'},
  {slug:'filipino-candidate-offer-document-checklist-coordinator',title:'How to scope Filipino candidate offer document checklist support',excerpt:'Track approved offer documents while hiring managers retain selection, compensation, and employment decisions.',lane:'candidate offer document checklist',owner:'hiring and people operations owner',packet:'the candidate identifier, approved offer version, required attachments, signer, due date, status, and access restriction',boundary:'selecting a candidate, changing compensation, interpreting employment terms, or sending an unapproved offer',caseStudy:'The signed attachment names a different start date from the approved offer record.',metric:'packets with version, signature, date, or attachment exceptions'},
  {slug:'filipino-executive-meeting-decision-log-assistant',title:'How to plan Filipino executive meeting decision log support',excerpt:'Turn approved meeting notes into traceable decisions without inventing priorities or commitments.',lane:'executive meeting decision logging',owner:'executive meeting owner',packet:'the meeting record, decision wording, accountable owner, due date, dependency, source timestamp, and later amendment',boundary:'declaring consensus, assigning an owner, changing priority, or closing an action without approval',caseStudy:'The transcript suggests a due date, but the chair’s approved notes leave the timing open.',metric:'decisions lacking an approved source, named owner, or effective date'},
  {slug:'filipino-subscription-cancellation-evidence-coordinator',title:'How to scope Filipino subscription cancellation evidence support',excerpt:'Assemble cancellation evidence while account owners decide eligibility, timing, refund, and retention offers.',lane:'subscription cancellation evidence',owner:'account or customer policy owner',packet:'the customer request, plan, billing cycle, approved terms, contact history, service state, and requested effective date',boundary:'canceling service, promising a refund, interpreting terms, or making a retention offer',caseStudy:'A cancellation request arrives after renewal, but the customer cites an earlier unanswered message.',metric:'cases waiting on a term, timestamp, remedy, or owner decision'},
  {slug:'filipino-property-maintenance-access-note-coordinator',title:'How to plan Filipino property maintenance access note coordination',excerpt:'Prepare visit and access notes while property owners retain safety, entry, and repair decisions.',lane:'property maintenance access-note coordination',owner:'property or facilities owner',packet:'the work order, site, approved contact, access window, visitor identity, affected area, restriction, and visit result',boundary:'granting entry, judging safety, changing locks, or approving repair scope',caseStudy:'A contractor requests access to a plant room that is absent from the approved work order.',metric:'visits paused for access, identity, safety, or scope questions'},
  {slug:'filipino-healthcare-referral-records-assistant',title:'How to scope Filipino healthcare referral records support',excerpt:'Maintain minimum referral records without interpreting clinical information or making care decisions.',lane:'healthcare referral record administration',owner:'authorized healthcare administrator',packet:'the patient identifier, referral source, destination, received date, required administrative fields, consent state, and scheduling status',boundary:'interpreting symptoms, recommending care, changing clinical content, or disclosing unnecessary patient data',caseStudy:'A referral is complete for scheduling but contains free-text clinical detail the coordinator does not need.',metric:'records with missing administrative fields, excess data, or clinical escalation'},
  {slug:'filipino-social-content-approval-register-assistant',title:'How to plan Filipino social content approval register support',excerpt:'Track approved social copy and assets while brand owners retain claim, response, and publication decisions.',lane:'social content approval registration',owner:'brand or marketing owner',packet:'the draft, channel, asset, claim source, audience, approver, scheduled time, and revision history',boundary:'approving a claim, changing brand position, responding publicly, or publishing without sign-off',caseStudy:'An approved caption is paired with a later image containing a new numerical claim.',metric:'posts held for asset, claim, version, or scheduling conflicts'},
  {slug:'filipino-sales-demo-follow-up-records-coordinator',title:'How to scope Filipino sales demo follow-up records',excerpt:'Prepare factual follow-up records without qualifying leads or making commercial commitments.',lane:'sales demo follow-up records',owner:'sales account owner',packet:'the attendee list, approved notes, stated questions, requested material, consented channel, owner, due date, and status',boundary:'qualifying a prospect, promising functionality, changing price, or sending unapproved outreach',caseStudy:'A prospect asks about a roadmap item that the approved product material does not confirm.',metric:'follow-ups with unsupported claims, missing owners, or unclear contact permission'},
  {slug:'filipino-month-end-accrual-support-packet-assistant',title:'How to plan Filipino month-end accrual support packets',excerpt:'Assemble period-end evidence while accountants retain recognition, estimate, and posting authority.',lane:'month-end accrual support packets',owner:'client accountant or controller',packet:'the period, vendor, service evidence, invoice state, approved estimate source, account reference, reviewer, and open difference',boundary:'choosing accounting treatment, estimating without an approved rule, posting an entry, or certifying the close',caseStudy:'A service was delivered before month end, but the vendor estimate covers a different billing period.',metric:'packets returned for period, source, estimate, or account conflicts'},
];

function buildDetail(t: Topic) {
  const sections = [
    {title:'Name the packet before the role',paragraphs:[`Start ${t.lane} with a concrete packet: ${t.packet}. A broad job title will not tell a Filipino team member which evidence is enough to move an item forward.`,`Give every field a source and checking time. If a required item is absent, use a visible missing state instead of filling the gap from memory.`]},
    {title:'Separate preparation from authority',paragraphs:[`The assistant can collect, transcribe, compare, label, and route the approved records. The line is clear: no ${t.boundary}.`,`Keep the ${t.owner} named on the queue. A deadline or familiar pattern is not permission to act when approval is missing.`]},
    {title:'Test the awkward case before launch',paragraphs:[`${t.caseStudy} The useful response is to preserve both records, describe the conflict in neutral language, and send one focused question to the owner.`,`Run that case beside an ordinary item and an incomplete one. These examples expose hidden rules while access and volume are still small.`]},
    {title:'Design a handoff another shift can use',paragraphs:[`A clean handoff states the last source checked, current status, unresolved difference, next owner, and action that must wait. Avoid notes such as “handled” that hide what actually happened.`,`Use named accounts, minimum permissions, multifactor authentication where available, and a dated removal path. Sensitive evidence should stay in the approved system.`]},
    {title:'Review evidence, not busyness',paragraphs:[`Sample completed packets against their original sources and track ${t.metric}. Pair every count with a defined period and total queue volume.`,`Return reasons should distinguish missing input, transcription error, stale source, conflicting evidence, unclear instruction, and work outside the role. That makes the operating guide easier to repair.`]},
    {title:'Decide whether the lane is ready to grow',paragraphs:[`Expansion is sensible only when a second reviewer can reproduce the packet, explain the stop rule, and locate the ${t.owner} without private context.`,`A new system, audience, data class, or decision changes the risk of the work. Treat it as a new scope review, even when the task looks similar.`]},
  ];
  return {datePublished:date,dateModified:date,image:{src:'/article-planning.svg',alt:`Workflow planning board for ${t.lane}`,caption:`A bounded ${t.lane} workflow keeps sources, stop rules, and ownership visible.`},shortAnswer:`Scope ${t.lane} around a defined evidence packet, one rehearsed exception, minimum access, and a named ${t.owner}.`,takeaways:['Define what a complete packet contains.','Show ordinary, incomplete, and conflicting examples.',`Keep decisions with the ${t.owner}.`,'Expand only after another reviewer can reproduce the handoff.'],sections,sourceArticleText:`${t.title}. ${t.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,sources:[{name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine privacy principles for proportionate, secure data handling.'},{name:'CISA: Require multifactor authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Account-security guidance for named access.'}],faqs:[{question:'What may the assistant complete?',answer:`The assistant may prepare and route the documented ${t.lane} packet.`},{question:'Who decides an exception?',answer:`The ${t.owner} keeps decision and approval authority.`},{question:'What should the first review include?',answer:'Compare an ordinary item, an incomplete item, and the rehearsed conflict with their original sources.'}],tags:[t.lane,'Filipino outsourcing','Workflow design'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Build a staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Use the onboarding checklist'}]};
}

export const september4BlogPosts = topics.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10}));
export const september4BlogDetails = Object.fromEntries(topics.map(topic => [topic.slug, buildDetail(topic)]));
