const published = '2026-09-10' as const;

type Brief = { slug:string; title:string; excerpt:string; queue:string; owner:string; fields:string; stop:string; caseStudy:string };

const briefs: readonly Brief[] = [
  {slug:'filipino-saas-user-provisioning-assistant',title:'How to Scope a Filipino SaaS User Provisioning Assistant',excerpt:'Prepare routine user access changes while system owners keep approval and security decisions.',queue:'SaaS user provisioning',owner:'system or security owner',fields:'requester, user, approved role, application, approval source, effective date, completion evidence, and removal date',stop:'the requested role exceeds the approved template, an approver is missing, or a departing user still owns shared resources',caseStudy:'A new sales employee needs three applications, but one request asks for administrator access and cites no approving manager.'},
  {slug:'filipino-mortgage-document-intake-assistant',title:'A Controlled Brief for Filipino Mortgage Document Intake Support',excerpt:'Index borrower documents and missing items without moving credit or lending judgment into an administrative role.',queue:'mortgage document intake',owner:'authorized lending owner',fields:'applicant reference, document type, source, received time, stated period, legibility state, duplicate flag, and reviewer',stop:'identity conflicts, a document appears altered, financial meaning is unclear, or an eligibility opinion is requested',caseStudy:'Two bank statements carry the same month and account ending, but their closing balances differ and one arrived through an unapproved channel.'},
  {slug:'filipino-property-lease-renewal-coordinator',title:'Planning a Filipino Property Lease Renewal Coordinator',excerpt:'Track dates, notices, and tenant records while property and legal owners decide terms and commitments.',queue:'lease renewal coordination',owner:'property or legal owner',fields:'property, tenant, agreement source, stated end date, notice window, communication history, proposed action, and decision owner',stop:'documents disagree, new terms are requested, a statutory question arises, or the tenant disputes notice',caseStudy:'The signed lease and property system show different end dates, and an earlier email refers to an extension that is not attached.'},
  {slug:'filipino-manufacturing-change-order-log-assistant',title:'Setting Boundaries for a Filipino Manufacturing Change Order Log Assistant',excerpt:'Maintain change evidence and routing without granting authority over engineering, safety, cost, or production release.',queue:'manufacturing change order logging',owner:'engineering or production owner',fields:'part, revision, request source, reason, affected order, drawing reference, approval state, effective point, and superseded version',stop:'a safety characteristic changes, drawings conflict, cost approval is absent, or production has already started',caseStudy:'A supplier sends a revised drawing after material was issued, but the message does not identify the first production lot affected.'},
  {slug:'filipino-veterinary-referral-records-assistant',title:'A Safe Workflow for Filipino Veterinary Referral Records Support',excerpt:'Coordinate referral records and consent status while veterinary professionals retain clinical decisions.',queue:'veterinary referral record coordination',owner:'authorized veterinary owner',fields:'animal and client identifiers, referring practice, request source, consent state, document list, appointment status, and exception',stop:'clinical urgency appears in a message, consent is unclear, identities conflict, or someone asks for treatment advice',caseStudy:'A referral packet names the correct animal but lists a different owner phone number and includes an urgent symptom note.'},
  {slug:'filipino-supplier-rebate-claim-assistant',title:'Building a Filipino Supplier Rebate Claim Preparation Queue',excerpt:'Assemble purchase and program evidence while finance and commercial owners decide eligibility and claim value.',queue:'supplier rebate claim preparation',owner:'finance or commercial owner',fields:'program, supplier, purchase record, eligible period, claimed category, evidence link, calculation source, exception, and reviewer',stop:'program language is ambiguous, purchase records conflict, a calculation needs interpretation, or submission authority is requested',caseStudy:'An invoice falls within the promotion dates, but its product code maps to two categories with different rebate rates.'},
  {slug:'filipino-fleet-maintenance-records-coordinator',title:'How a Filipino Fleet Maintenance Records Coordinator Should Work',excerpt:'Keep service records and due signals complete without assigning roadworthiness or repair approval to the coordinator.',queue:'fleet maintenance record coordination',owner:'fleet or safety owner',fields:'vehicle, mileage source, service type, due rule, work order, vendor evidence, completion state, and next review',stop:'a safety complaint appears, service evidence is incomplete, mileage conflicts, or continued operation needs a decision',caseStudy:'A van passed its calendar service date, while the telematics mileage is lower than the workshop record and a driver reported braking noise.'},
  {slug:'filipino-advertising-creative-trafficking-assistant',title:'Scoping a Filipino Advertising Creative Trafficking Assistant',excerpt:'Route approved creative and placement details without handing over claims, budgets, targeting policy, or launch authority.',queue:'advertising creative trafficking',owner:'campaign or brand owner',fields:'campaign, approved asset, copy version, destination, placement, audience instruction, flight dates, tracking reference, and launch state',stop:'copy or destination differs, a regulated claim appears, budget changes, or audience instructions are incomplete',caseStudy:'The platform upload matches the approved image, but its destination page contains an offer date that ended before the scheduled flight.'},
  {slug:'filipino-legal-hold-custodian-tracking-assistant',title:'A Bounded Filipino Legal Hold Custodian Tracking Role',excerpt:'Maintain notice and acknowledgement records while counsel controls scope, interpretation, and release.',queue:'legal hold custodian tracking',owner:'authorized legal owner',fields:'matter reference, custodian, approved notice version, delivery evidence, acknowledgement, reminder state, exception, and release instruction',stop:'scope is questioned, a custodian reports deletion, legal advice is requested, or a release has not been authorized',caseStudy:'A former contractor acknowledges the notice but says all project files remained in a client-owned account that is now inaccessible.'},
  {slug:'filipino-ecommerce-chargeback-evidence-assistant',title:'Designing a Filipino Ecommerce Chargeback Evidence Workflow',excerpt:'Prepare transaction evidence and deadlines while payment and legal owners decide representations and remedies.',queue:'ecommerce chargeback evidence preparation',owner:'payments or legal owner',fields:'case, reason code, transaction, order, delivery evidence, customer contact, policy source, deadline, and decision state',stop:'identity is disputed, evidence conflicts, a representation must be certified, or a refund and chargeback overlap',caseStudy:'Tracking shows delivery, but the carrier photo depicts another doorway and the customer had already requested an address correction.'},
  {slug:'filipino-clinical-trial-site-file-assistant',title:'A Controlled Brief for Filipino Clinical Trial Site File Support',excerpt:'Index approved study records while investigators and regulated owners retain clinical and compliance judgment.',queue:'clinical trial site file administration',owner:'investigator or regulated study owner',fields:'study, site, document identity, approved version, effective date, signer, filing location, completeness state, and query owner',stop:'consent, safety, eligibility, protocol interpretation, or source-data correction is involved',caseStudy:'A training certificate is current, but the delegation log assigns the same person a duty before the certificate date.'},
  {slug:'filipino-utility-billing-exception-assistant',title:'Planning a Filipino Utility Billing Exception Assistant',excerpt:'Prepare meter and billing discrepancies without giving the role authority to recalculate, credit, or interpret tariffs.',queue:'utility billing exception preparation',owner:'billing or regulatory owner',fields:'account, meter, reading source, service period, tariff reference, billed value, prior case, discrepancy, and reviewer',stop:'meter identity conflicts, a tariff needs interpretation, tampering is suspected, or a credit is requested',caseStudy:'A manual reading is lower than the prior accepted reading, while the uploaded photograph shows a meter number missing one digit.'},
];

function detail(b: Brief) {
  const sections = [
    {title:'Define the queue before assigning it',paragraphs:[`${b.queue} starts with a written eligibility rule. Each record should contain ${b.fields}. A missing field remains an exception instead of being filled from memory or a similar account.`,`State which channels are approved, when a record enters the queue, and which event marks administrative completion. The role prepares a reviewable packet; it does not inherit the authority attached to the underlying business process.`]},
    {title:'Separate preparation from approval',paragraphs:[`The assistant may retrieve approved records, compare stated fields, label a client-defined condition, request missing evidence, and route the packet. The ${b.owner} keeps the consequential decision.`,`Pause when ${b.stop}. The escalation should quote the conflicting source, name the blocked action, and ask one answerable question.`]},
    {title:'Test the boundary with a real-looking case',paragraphs:[`${b.caseStudy} The assistant should preserve each source, record when it was retrieved, and describe the mismatch without choosing the preferred version.`,`Run this example during training along with a complete case and a case that lacks a required source. If two reviewers choose different routes, rewrite the rule and examples before adding volume.`]},
    {title:'Limit access to the work',paragraphs:[`Issue a named account with only the systems and actions required for ${b.queue}. Use multifactor authentication where the system supports it, keep exports off personal devices, and set a removal trigger before access begins.`,`Mask fields that the task does not require. A record may be operationally useful without exposing every personal, financial, health, legal, or commercial detail held by the client.`]},
    {title:'Preserve changes and handoffs',paragraphs:[`A correction log should retain the former value, new value, supporting source, reason, actor, and time. Overwriting the earlier state removes evidence that the ${b.owner} may need later.`,`At shift handoff, show items received, packets completed, exceptions waiting, approaching deadlines, and the named owner for each pause. Do not bury decisions in private chat.`]},
    {title:'Review the routine without inventing a benchmark',paragraphs:[`For the first week, review consecutive eligible items rather than a hand-picked set of clean records. Count missing sources, conflicting fields, correction events, owner wait time, and completed packets under one dated instruction version.`,`These observations describe that queue and period only. They do not prove worker quality, provider performance, savings, compliance, or business impact. Report exclusions and system outages beside the count.`]},
  ];
  return {datePublished:published,dateModified:published,image:{src:'/article-planning.svg',alt:`Planning board for ${b.queue}`,caption:'A bounded queue keeps evidence, decisions, and access responsibilities visible.'},shortAnswer:`A Filipino assistant can support ${b.queue} when entry rules, evidence fields, stop conditions, and the ${b.owner} are documented.`,takeaways:['Define eligibility and completion in writing.','Preserve missing and conflicting source evidence.',`Keep approval with the ${b.owner}.`,'Audit consecutive cases under a dated instruction version.'],sections,sourceArticleText:`${b.title}. ${b.excerpt} ${sections.flatMap(section=>section.paragraphs).join(' ')}`,sources:[{name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official principles for purpose limitation, accuracy, proportionality, and data security.'},{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Official account-security guidance for multifactor authentication.'}],faqs:[{question:'What work can the assistant complete?',answer:`The assistant can prepare, document, and route the defined ${b.queue} packet.`},{question:'Who handles an exception?',answer:`The ${b.owner} decides any consequential exception or approval.`},{question:'What should managers inspect first?',answer:'Review consecutive complete, incomplete, and conflicting cases against their original sources.'}],tags:[b.queue,'Filipino outsourcing','Operations controls'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Build a staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Use the onboarding checklist'}]};
}

export const september10BlogPosts = briefs.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10,image:'/article-planning.svg'}));
export const september10BlogDetails = Object.fromEntries(briefs.map(brief => [brief.slug, detail(brief)]));
