const published = '2026-09-18' as const;

export type Brief = {
  slug: string; title: string; excerpt: string; service: string; queue: string;
  owner: string; inputs: string; stop: string; example: string; output: string;
};

const briefs: readonly Brief[] = [
  {slug:'filipino-executive-travel-approval-assistant',title:'How to Scope a Filipino Executive Travel Approval Assistant',excerpt:'Prepare itinerary choices and approval records while the traveler or budget owner keeps booking and exception authority.',service:'executive assistance',queue:'executive travel request preparation',owner:'traveler or budget owner',inputs:'traveler, purpose, approved dates, origin, destination, policy version, budget reference, preferences, and approval state',stop:'a fare exceeds policy, identity data conflicts, a visa or safety question appears, or a purchase is requested without approval',example:'A lower fare arrives outside the approved travel window and includes a connection the traveler previously rejected.',output:'a comparison packet with source links, total stated cost, restrictions, open questions, and a recorded owner choice'},
  {slug:'filipino-customer-escalation-timeline-assistant',title:'Building a Filipino Customer Escalation Timeline Assistant Role',excerpt:'Assemble customer events and promises for review without transferring remedy, liability, or policy decisions.',service:'customer support operations',queue:'customer escalation timeline preparation',owner:'customer operations owner',inputs:'case ID, customer messages, channel, order or account events, prior replies, policy version, promised action, and current owner',stop:'records conflict, compensation is requested, legal or safety language appears, or a new commitment would be made',example:'The ticket promises a replacement while the order log records a refund and the customer says neither has arrived.',output:'a dated event timeline that separates customer statements, system events, staff actions, gaps, and the next owner question'},
  {slug:'filipino-expense-receipt-matching-assistant',title:'A Controlled Filipino Expense Receipt Matching Workflow',excerpt:'Match receipts to approved expense records while finance owners retain classification, reimbursement, and tax judgments.',service:'bookkeeping support',queue:'expense receipt matching',owner:'finance or accounting owner',inputs:'expense ID, employee, transaction source, receipt, date, currency, stated purpose, policy reference, and review state',stop:'amounts or entities conflict, a receipt is altered or absent, business purpose is unclear, or reimbursement approval is requested',example:'A card charge is in local currency, the receipt shows another currency, and the submitted conversion does not match the card statement.',output:'a match packet showing exact sources, variances, missing fields, duplicate indicators, and the finance decision still required'},
  {slug:'filipino-duplicate-customer-record-review-assistant',title:'How to Brief a Filipino Duplicate Customer Record Review Assistant',excerpt:'Prepare likely duplicate records for controlled review while system owners retain merge and deletion authority.',service:'data processing support',queue:'duplicate customer record review',owner:'CRM or data governance owner',inputs:'record IDs, names, verified contact fields, account relationships, source systems, creation dates, activity history, and confidence rule',stop:'identities remain uncertain, records belong to related people, regulated data differs, or a merge or deletion must be executed',example:'Two contacts share an email domain and postal address but have different names, purchases, and consent histories.',output:'a side-by-side comparison with matched fields, conflicts, source lineage, affected relationships, and a recommended review lane'},
  {slug:'filipino-reference-check-scheduling-assistant',title:'Planning a Filipino Reference Check Scheduling Assistant',excerpt:'Coordinate consented reference conversations while recruiters retain assessment, eligibility, and hiring decisions.',service:'recruitment coordination',queue:'reference check scheduling',owner:'recruiter or hiring owner',inputs:'candidate, consent state, approved referee, relationship, contact channel, time zone, scheduling window, and completion status',stop:'consent is missing, identity is uncertain, a referee volunteers sensitive information, or evaluation is requested',example:'A referee replies from an address not supplied by the candidate and asks for the candidate’s proposed compensation.',output:'a scheduling record with consent evidence, contact attempts, confirmed participants, time-zone conversion, and exception notes'},
  {slug:'filipino-campaign-link-qa-assistant',title:'A Practical Filipino Campaign Link QA Assistant Brief',excerpt:'Test approved campaign links and tracking parameters without changing claims, audiences, budgets, or launch decisions.',service:'digital marketing support',queue:'campaign link quality assurance',owner:'marketing or analytics owner',inputs:'approved creative, destination URL, UTM convention, channel, audience label, device scope, launch window, and reviewer',stop:'copy or destination differs from approval, personal data enters a URL, a redirect is unsafe, or publication authority is needed',example:'The mobile ad opens the correct page but drops the campaign parameter after a regional redirect.',output:'a device-and-channel test record with requested URL, final URL, parameter result, screenshot reference, and blocked launch issue'},
  {slug:'filipino-marketplace-listing-suppression-assistant',title:'Scoping a Filipino Marketplace Listing Suppression Assistant',excerpt:'Document suppressed ecommerce listings and source evidence while platform, compliance, and catalog owners decide corrections.',service:'ecommerce operations',queue:'marketplace listing suppression review',owner:'marketplace or catalog owner',inputs:'SKU, channel, suppression notice, listing version, approved product source, inventory state, prior changes, and appeal status',stop:'a product claim needs revision, safety or authenticity is questioned, source records conflict, or an appeal must be submitted',example:'A listing is suppressed for a missing attribute that appears in the supplier sheet but not in the approved packaging artwork.',output:'an evidence packet linking the platform reason to current listing fields, authoritative sources, discrepancies, and owner options'},
  {slug:'filipino-property-maintenance-intake-assistant',title:'Designing a Filipino Property Maintenance Intake Assistant Role',excerpt:'Capture tenant maintenance evidence and route urgency indicators while property owners retain safety and dispatch judgments.',service:'customer support operations',queue:'property maintenance intake',owner:'property or facilities owner',inputs:'property, unit, requester, contact permission, issue as stated, occurrence time, photos, access constraints, and prior work order',stop:'injury, fire, gas, flooding, security, habitability, or any uncertain urgency indicator appears',example:'A tenant reports a slow leak but a photo shows water near an electrical outlet and access is unavailable until evening.',output:'a verbatim intake record with location, observable facts, attachments, access details, prior case links, and immediate escalation flag'},
  {slug:'filipino-legal-client-intake-data-assistant',title:'Boundaries for a Filipino Legal Client Intake Data Assistant',excerpt:'Organize prospective-client facts for authorized review without giving advice, accepting representation, or clearing conflicts.',service:'data processing support',queue:'legal client intake data preparation',owner:'authorized legal intake owner',inputs:'prospective client, adverse parties as supplied, matter description, jurisdiction, dates, referral source, contact permission, and review state',stop:'legal advice is requested, a deadline or emergency appears, confidentiality is assumed, or representation must be accepted',example:'A caller describes a hearing next week and names a company whose subsidiary appears in the firm’s records.',output:'a source-labeled intake packet that preserves the caller’s words, parties, stated dates, missing fields, and urgent owner alert'},
  {slug:'filipino-healthcare-eligibility-records-assistant',title:'A Safe Filipino Healthcare Eligibility Records Assistant Workflow',excerpt:'Record payer eligibility responses while authorized clinic staff retain coverage, billing, and care decisions.',service:'data processing support',queue:'healthcare eligibility record preparation',owner:'authorized clinic or billing owner',inputs:'patient reference, consented identifiers, payer source, service date, response time, plan state, stated benefits, limitations, and reviewer',stop:'identity differs, clinical urgency appears, coverage requires interpretation, or a patient asks for a guarantee',example:'The portal shows active coverage but returns no benefit detail for the scheduled service and lists an unfamiliar group number.',output:'a time-stamped eligibility record with source, exact response, unresolved fields, access log, and a clear non-guarantee note'},
  {slug:'filipino-saas-migration-validation-assistant',title:'How to Plan a Filipino SaaS Migration Validation Assistant',excerpt:'Compare approved source and target records while product owners retain transformation, deletion, and cutover authority.',service:'data processing support',queue:'SaaS migration validation',owner:'implementation or data owner',inputs:'migration batch, source extract, target record, mapping version, required fields, relationship keys, error class, and reviewer',stop:'mapping logic is unclear, sensitive fields appear unexpectedly, source and target counts diverge, or cutover action is requested',example:'All accounts migrate, but contacts attached to archived customers appear as unowned records in the target system.',output:'a reproducible validation sample with record keys, field comparisons, relationship checks, error evidence, and owner disposition'},
  {slug:'filipino-purchase-order-confirmation-assistant',title:'A Filipino Purchase Order Confirmation Assistant Playbook',excerpt:'Compare supplier acknowledgments with approved purchase orders while procurement retains change and acceptance authority.',service:'data processing support',queue:'purchase order confirmation review',owner:'procurement or operations owner',inputs:'purchase order, approved revision, supplier acknowledgment, item, quantity, price, delivery date, ship-to location, and terms reference',stop:'price, quantity, specification, entity, date, or terms differ, or a change must be accepted',example:'The supplier confirms the correct quantity and price but substitutes a later delivery date and a different warehouse.',output:'a line-level variance record with both sources, material differences, deadline context, and a single owner decision request'},
];

export function buildSeptember18Detail(b: Brief) {
  const sections = [
    {title:'Define the work before access begins',paragraphs:[`Treat ${b.queue} as a bounded queue, not a broad assistant title. The written entry rule should name ${b.inputs}. The ${b.owner} should identify which system is authoritative for each field and what evidence is acceptable when a source is missing.`, `Define administrative completion as ${b.output}. Completion does not mean the underlying business decision is approved. It means the evidence is organized, the open question is visible, and an accountable owner can review the case without reconstructing it from private messages.`, `Use one queue identifier from intake through closure. If an item arrives through email, chat, a form, and a business system, link those events rather than creating four unrelated tasks. This protects the chronology and reduces duplicate effort.`]},
    {title:'Separate preparation from authority',paragraphs:[`The assistant may retrieve approved records, transcribe exact fields, apply client-defined labels, compare sources, request specified missing items, and route a packet. The ${b.owner} retains judgment, approval, external commitment, and any action that changes money, access, rights, safety, or the authoritative record.`, `A useful stop rule is concrete: stop when ${b.stop}. The escalation should quote or link the conflicting evidence, describe the action that cannot continue, and ask one decision question. “Please advise” without context only moves the research burden back to the owner.`, `Urgency never expands permission. If a deadline approaches, record the deadline source and notify the named owner through the approved channel. Do not resolve uncertainty by copying an earlier decision from a superficially similar case.`]},
    {title:'Build the minimum complete record',paragraphs:[`Create a required-field checklist from ${b.inputs}. Mark each field present, absent, conflicting, or not applicable. “Not applicable” should require a reason so it cannot become a convenient substitute for missing evidence.`, `Preserve the submitted record in its received form. Corrections belong in a new event with old value, proposed value, source, actor, time, and approval state. Silent cleanup makes a packet look complete while removing the history a reviewer needs.`, `Where personal or commercially sensitive data is involved, collect only what this queue needs. A complete packet is not the largest packet. It is the smallest set that answers the approved operational question and supports the reviewer’s decision.`]},
    {title:'Test a realistic boundary case',paragraphs:[`${b.example} A training exercise should require the assistant to keep every source, explain the discrepancy in neutral language, identify the stop condition, and route the case without deciding which party is correct.`, `Add two controls to that exercise: a normal case that can be completed and an incomplete case that must wait. Ask two reviewers to apply the written rule independently. If they select different paths, revise the instruction or example before increasing volume.`, `Do not score the worker on whether the owner likes the eventual outcome. Score the preparation against observable requirements: source traceability, field accuracy, preserved chronology, correct stop rule, protected access, and timely routing.`]},
    {title:'Limit systems, permissions, and exports',paragraphs:[`Provide a named account for only the systems and actions required by ${b.queue}. Use multifactor authentication where supported, prohibit shared credentials, and document the access owner, approval, review date, and removal trigger.`, `Prefer read access or a preparation workspace when the assistant does not need to change the authoritative record. Separate drafting from sending, comparison from merging, and packet preparation from approval. These technical boundaries reinforce the written operating boundary.`, `Exports require their own control. Name the approved storage location, file naming rule, retention owner, and deletion process. Do not move live records into personal drives or chat attachments simply because that makes review faster.`]},
    {title:'Run a controlled first week',paragraphs:[`Start with consecutive eligible items rather than a selection of easy examples. Review every early packet, then reduce review only after repeated accuracy under the same instruction version. Keep unusual items in the sample because they test whether the escalation path actually works.`, `A daily handoff should show items received, packets completed, missing evidence, source conflicts, approaching deadlines, and decisions waiting on the ${b.owner}. Counts need the same entry and completion definitions each day or apparent progress will be misleading.`, `Write corrections into the operating guide. Record the original instruction, the observed problem, the corrected rule, its effective time, and the owner who approved it. Do not retroactively judge earlier work against a rule that did not yet exist.`]},
    {title:'Measure the queue without inventing performance claims',paragraphs:[`Useful operating measures include eligible items, complete packets, missing-source cases, conflict cases, returned packets, owner-wait time, and age of the oldest open item. Report raw counts beside percentages so a small or changing denominator stays visible.`, `These measures describe the queue under a specific process and period. They do not by themselves prove savings, service quality, compliance, worker capability, or customer outcomes. Note outages, policy changes, staffing gaps, and exclusions beside the figures.`, `If a target is introduced, the business owner should approve its definition and consequence. The assistant may calculate from controlled records, but should not choose the denominator, suppress inconvenient exceptions, or reinterpret a missed target.`]},
    {title:'Review privacy, security, and evidence quality',paragraphs:[`The Philippines National Privacy Commission emphasizes transparency, legitimate purpose, and proportionality in personal-data processing. Apply those principles by stating why a field is needed, limiting access, and avoiding copies that are unrelated to ${b.queue}.`, `NIST guidance on digital identity and security controls supports named identities, authentication, least privilege, and auditable account lifecycle practices. CISA also recommends phishing-resistant multifactor authentication where available. The client remains responsible for selecting controls appropriate to its systems and risk.`, `Citations provide control principles, not a claim that the workflow is certified or legally sufficient. Sensitive healthcare, legal, financial, employment, safety, and identity matters may need qualified review and stricter client rules.`]},
    {title:'Decide whether the role is ready to expand',paragraphs:[`Expansion is reasonable only when the queue definition is stable, source locations are known, corrections are traceable, owner questions are answered promptly, and the worker consistently stops at the stated boundary. More volume is not a reason to remove approvals.`, `Before adding another workflow, compare its data, systems, consequences, reviewer, and authority. A task that sounds adjacent may need different access or professional oversight. Write a separate lane when the inputs or decision owner change materially.`, `A strong handoff leaves the business with a reusable operating record: scope, examples, permissions, stop rules, review notes, measures, and removal steps. That record supports continuity without pretending that documentation can replace accountable management.`]},
  ];
  return {
    datePublished:published,dateModified:published,
    image:{src:'/article-planning.svg',alt:`Planning board for ${b.queue}`,caption:'A practical role brief connects source evidence, boundaries, access, and a named reviewer.'},
    shortAnswer:`A Filipino assistant can support ${b.queue} when the source fields, completion event, stop rules, access limits, and ${b.owner} are written before live work begins.`,
    takeaways:[`Define ${b.output}.`,'Preserve missing and conflicting evidence.','Keep consequential decisions with the named client owner.','Review consecutive early work under one instruction version.'],
    sections,
    sourceArticleText:`${b.title} ${b.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,
    sources:[
      {name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine guidance for transparency, legitimate purpose, proportionality, accuracy, and security.'},
      {name:'NIST SP 800-63-4: Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/',note:'Primary guidance for identity, authentication, and account lifecycle controls.'},
      {name:'CISA: More than a Password',url:'https://www.cisa.gov/mfa',note:'Current first-party guidance on multifactor authentication.'},
    ],
    faqs:[{question:'What may the assistant complete?',answer:`The assistant may prepare and route the defined ${b.queue} output using approved sources and rules.`},{question:'Who decides exceptions?',answer:`The ${b.owner} decides exceptions, approvals, and consequential actions.`},{question:'How should early work be checked?',answer:'Review consecutive items for source traceability, field accuracy, stop-rule use, access handling, and clear owner questions.'}],
    tags:[b.service,'Filipino outsourcing','Role planning'],
    related:[{href:`/services/${b.service.replaceAll(' ','-')}`,label:`Explore ${b.service}`},{href:'/contact-us',label:'Discuss a bounded staffing role'}],
  };
}

export const september18BlogPosts = briefs.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:12,image:'/article-planning.svg'}));
export const september18BlogDetails = Object.fromEntries(briefs.map(brief=>[brief.slug,buildSeptember18Detail(brief)]));
