const publicationDate = '2026-09-23' as const;

export type September23Brief = {slug:string;title:string;excerpt:string;pillar:string;question:string;owner:string;inputs:string;scenario:string;boundary:string;comparison:string;output:string};

export function buildSeptember23Detail(b: September23Brief) {
  const sections = [
    {title:'Define the decision before collecting information',paragraphs:[
      `${b.question} Start by naming the decision, the person authorized to make it, and the date on which the answer will be reviewed. The accountable owner for this plan is the ${b.owner}. A job title alone does not reveal the queue, consequence, access, schedule, or review effort that makes the decision practical.`,
      `Define the finish line as ${b.output}. Keep each input connected to its source rather than turning a preference into a fact. A current agreement, system role, timestamp, approved instruction, or observed work sample can be checked. A confident estimate without a source should remain an assumption and receive an owner and review date.`,
      `Use one recent, representative period of actual work. Include ordinary items, incomplete items, a conflicting-source example, and an event that must stop for owner review. This prevents the plan from describing only the easy path while leaving the first real exception to private chat or improvisation.`
    ]},
    {title:'Build a small evidence packet',paragraphs:[
      `Gather ${b.inputs}. Remove personal information that the planning exercise does not need, and keep necessary records in the approved location. The packet should show version, source owner, date checked, and any limitation that could change how it is interpreted.`,
      `Separate observed facts, reported statements, calculations, assumptions, and decisions. These categories answer different questions. A complete row is not necessarily an approved action, and a polished note is not proof that the underlying source is current. When two records disagree, preserve both and ask which source governs.`,
      `Write one normal example, one incomplete example, and one stop example. For each, show what enters the queue, what the team member may do, what evidence must remain visible, and which person receives the next question. Someone who did not write the brief should be able to reproduce the route.`
    ]},
    {title:'Compare options on the same basis',paragraphs:[
      `${b.comparison} Use the same work sample, time period, definitions, access assumptions, owner availability, and completion rule for every option. Changing the basis between columns creates a tidy table that cannot support a responsible choice.`,
      `Record what is included, excluded, unknown, dependent on another party, and subject to current written terms. Do not fill an unknown with an invented market norm or imply that a staffing structure guarantees cost, quality, availability, security, or business results. Ask the candidate, provider, system owner, or qualified adviser for the missing current evidence.`,
      `Include internal work. Recruiting, instruction repair, account setup, review, exception decisions, meetings, access administration, and offboarding consume client capacity even when a proposal does not show them as line items. The useful comparison makes those responsibilities visible without pretending that every hour can be forecast precisely.`
    ]},
    {title:'Test a realistic scenario',paragraphs:[
      `${b.scenario} Walk through this event with the proposed worker, provider, and client owner. Ask what they would observe, which source they would open, what action is permitted, what must pause, and what precise question would reach the ${b.owner}.`,
      `Score the walkthrough against observable criteria: source use, factual accuracy, boundary recognition, privacy discipline, escalation clarity, record quality, and reproducibility. Do not reward speed when the correct action is to preserve uncertainty. Do not reward confidence when a required approval or source is absent.`,
      `Run the same scenario for each option and retain the notes. If an answer depends on an undocumented promise, ask for it in the relevant written terms or mark it unverified. A decision record should show why an option fit this role at this time, not claim that it is universally best.`
    ]},
    {title:'Set authority, privacy, and access boundaries',paragraphs:[
      `The operating boundary is ${b.boundary}. Translate it into an allowed-action list and a stop-action list. Identify who can approve money movement, customer remedies, policy exceptions, account changes, public statements, employment decisions, sensitive-data use, and destructive system actions.`,
      `Apply least privilege to the first approved queue. For every account, record the business purpose, permission level, approving owner, authentication method, review date, and removal trigger. Use named accounts and approved authentication controls. Shared credentials and convenience exports weaken both accountability and offboarding.`,
      `The Philippine National Privacy Commission describes transparency, legitimate purpose, and proportionality as core data-privacy principles. Put those principles into the workflow: explain the use, collect only what the task needs, keep it only where approved, restrict access, and provide a route for questions or correction.`
    ]},
    {title:'Create an escalation record that reduces uncertainty',paragraphs:[
      `An escalation should include the item identifier, source links, timestamps, observed facts, missing or conflicting evidence, action already taken, paused action, named owner, fallback owner, and one answerable question. “Please advise” shifts the research burden back to the manager and makes response time harder to interpret.`,
      `Use distinct waiting reasons for missing requester information, unavailable source, system outage, owner decision, policy question, permission gap, and scheduled future action. A generic pending label hides whether the team can make progress and encourages people to clear the queue by guessing.`,
      `Record the owner response in the approved system with its effective date. If the response changes a rule, identify earlier open work that may need review and update the example or instruction. Do not leave a durable operating decision only in a call or private message.`
    ]},
    {title:'Launch with a controlled review rhythm',paragraphs:[
      `Begin with a small live scope, a named reviewer, and scheduled checkpoints. Review the source record as well as the final output. Sample routine work, incomplete work, high-consequence events, and a random portion of apparently clean completions. This makes the review useful without suggesting that one sample proves every item correct.`,
      `Classify corrections as instruction gap, source conflict, access problem, execution error, reviewer disagreement, or unresolved owner decision. Count returned work and repeated exceptions, but use those measures to repair the process rather than rank a person without context. State the sample and checklist version beside every summary.`,
      `Expand only after the ordinary path and stop path are reproducible, owner questions receive timely answers, access is still proportionate, and the manager has capacity for the next lane. Expansion requires a revised scope, examples, permissions, and review plan; a casual chat request should not silently redefine the role.`
    ]},
    {title:'Plan continuity and the eventual exit',paragraphs:[
      `Keep a handoff record with current state, last source checked, unresolved question, deadline source, next owner action, and access limitation. A substitute should not need to reconstruct work from memory. Test the handoff before an absence, deadline, or system incident makes it urgent.`,
      `Document what happens when a worker, client manager, provider contact, or critical system is unavailable. Name the activation authority, fallback communication, work that may continue, work that must pause, and the evidence required when normal operations resume. Silence is not approval.`,
      `Offboarding belongs in the initial design. Maintain the account and asset inventory, work-transfer fields, record locations, removal triggers, responsible owners, and confirmation evidence. Contractual, employment, privacy, and payment questions remain with authorized people and qualified advisers, not the workflow coordinator.`
    ]},
    {title:'Use measures as management signals',paragraphs:[
      `Track received, eligible, completed, returned, waiting, escalated, reopened, missing-source, correction, and owner-wait counts. Add age bands and reason codes when they help a manager find a bottleneck. These are queue signals; they do not by themselves prove savings, accuracy, satisfaction, compliance, revenue, or employee performance.`,
      `Review measures with the denominator, time period, queue definition, source system, and known exclusions. A falling completion count may reflect lower demand, a system outage, a new stop rule, or insufficient capacity. Ask what changed before assigning a cause. Keep qualitative examples beside aggregate counts.`,
      `The final decision should cite the evidence reviewed, unresolved assumptions, owner, effective date, and next review trigger. Preserve rejected options and the reason they were not selected. A practical record helps the next manager reconsider the choice when volume, systems, terms, risks, or team capacity change.`
    ]},
  ];
  return {datePublished:publicationDate,image:{src:'/article-planning.svg',alt:`Planning board for ${b.title.toLowerCase()}`,caption:`A source-based plan keeps ownership, limits, and review visible for ${b.pillar}.`},lead:`A useful ${b.pillar} decision starts with the real queue and names the owner before comparing people or delivery models.`,shortAnswer:`${b.question} Use current evidence from the actual role, compare options on one basis, and keep consequential decisions with the ${b.owner}. The deliverable is ${b.output}.`,takeaways:[`Create ${b.output}.`,'Use the same real work sample for every option.','Preserve unknowns and conflicting sources.','Keep access narrow and decisions with named owners.'],sections,sourceArticleText:`${b.title} ${b.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,sources:[{name:'Philippine National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine source for data privacy principles and responsibilities.'},{name:'NIST SP 800-53 Rev. 5: Security and Privacy Controls',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Primary control catalog for access, accounts, audit, and lifecycle planning.'},{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'First-party security guidance for account protection.'}],faqs:[{question:'Does this guide determine the final staffing decision?',answer:`No. It prepares comparable evidence; the ${b.owner} retains the decision.`},{question:'Should unknown information be estimated?',answer:'Keep it marked as unknown, request a current source, and assign an owner and review date.'},{question:'When should the scope expand?',answer:'Only after the initial queue, stop rules, access, owner response, and review process work consistently.'}],tags:[b.pillar,'Philippines staffing','Hiring operations'],related:[{href:'/services',label:'Explore staffing services'},{href:'/contact-us',label:'Discuss a bounded Philippines role'}]};
}
