const date = '2026-09-07' as const;

type Topic = { slug:string; title:string; excerpt:string; lane:string; owner:string; packet:string; boundary:string; caseStudy:string; metric:string };

const topics: readonly Topic[] = [
  {slug:'filipino-customer-refund-approval-packet-assistant',title:'A practical scope for Filipino customer refund packet support',excerpt:'Build complete refund review packets while client owners keep approval and payment authority.',lane:'customer refund packet preparation',owner:'customer policy or finance owner',packet:'the request, order, payment, delivery evidence, approved policy, contact history, and requested remedy',boundary:'deciding eligibility, promising a remedy, approving a refund, or releasing money',caseStudy:'The customer reports a missing parcel while the carrier record says delivered and includes no proof image.',metric:'packets paused for missing evidence, policy conflicts, or owner decisions'},
  {slug:'filipino-payroll-input-change-register-coordinator',title:'Planning a Filipino payroll input change register',excerpt:'Keep payroll input changes traceable without transferring pay, tax, or employment decisions.',lane:'payroll input change registration',owner:'authorized payroll or people owner',packet:'the employee identifier, requested field, old value, new value, effective period, source, approver, and status',boundary:'calculating pay, interpreting tax rules, changing employment terms, or submitting payroll',caseStudy:'A manager requests an allowance change after the period cutoff but does not state an effective date.',metric:'changes returned for cutoff, source, approval, or effective-date gaps'},
  {slug:'filipino-ecommerce-promotion-setup-checklist-assistant',title:'How to brief a Filipino ecommerce promotion setup assistant',excerpt:'Prepare channel-ready promotion checks while commercial owners retain pricing and publishing control.',lane:'ecommerce promotion setup checking',owner:'commercial or ecommerce owner',packet:'the approved offer, eligible SKUs, market, currency, dates, exclusions, creative version, and channel checklist',boundary:'setting prices, changing offer terms, approving claims, or publishing the promotion',caseStudy:'The banner says “sitewide” while the approved offer excludes two product collections.',metric:'setups held for offer, SKU, date, currency, or creative conflicts'},
  {slug:'filipino-supplier-insurance-certificate-tracker',title:'Scoping a Filipino supplier insurance certificate tracker',excerpt:'Track document status and exceptions without making coverage or supplier-risk judgments.',lane:'supplier insurance certificate tracking',owner:'procurement, risk, or legal owner',packet:'the supplier, required document type, received file, stated dates, named entity, requirement source, and reviewer state',boundary:'interpreting coverage, accepting risk, waiving a requirement, or approving a supplier',caseStudy:'A certificate is current, but the insured name differs from the contracted supplier entity.',metric:'records with missing files, date conflicts, entity mismatches, or owner review'},
  {slug:'filipino-crm-lead-consent-record-assistant',title:'A safe workflow for Filipino CRM lead consent records',excerpt:'Organize consent evidence and channel preferences without deciding whether outreach is lawful.',lane:'CRM lead consent record administration',owner:'privacy, legal, or campaign owner',packet:'the contact identifier, collection source, timestamp, notice version, stated channel, preference history, and suppression state',boundary:'interpreting consent, overriding suppression, selecting a lawful basis, or sending outreach',caseStudy:'A webinar form records email permission while the CRM import also marks the contact for SMS.',metric:'records held for source, channel, timestamp, or suppression conflicts'},
  {slug:'filipino-software-access-review-evidence-coordinator',title:'Designing Filipino software access review evidence support',excerpt:'Prepare access-review evidence while system owners decide entitlement changes.',lane:'software access review evidence',owner:'system or security owner',packet:'the user, role, system, permission source, last activity, manager, review result, and effective timestamp',boundary:'granting or removing access, judging business need, approving exceptions, or sharing credentials',caseStudy:'A contractor is inactive in HR records but still owns an automated integration account.',metric:'reviews waiting on identity, ownership, entitlement, or dependency decisions'},
  {slug:'filipino-content-claim-substantiation-register-assistant',title:'How to run a Filipino content claim substantiation register',excerpt:'Link marketing claims to approved evidence without turning coordinators into claim approvers.',lane:'content claim substantiation registration',owner:'brand, legal, or subject-matter owner',packet:'the exact claim, placement, audience, source link, source date, qualification, approver, and expiry trigger',boundary:'inventing evidence, interpreting law, approving a claim, or publishing content',caseStudy:'A product page says “fastest” but its source compares only three providers from the prior year.',metric:'claims held for scope, freshness, qualification, or approval gaps'},
  {slug:'filipino-logistics-delivery-exception-timeline-assistant',title:'Briefing a Filipino delivery exception timeline assistant',excerpt:'Reconstruct shipment events for review while logistics owners choose remedies and carrier actions.',lane:'delivery exception timeline preparation',owner:'logistics or customer-service owner',packet:'the order, carrier events, warehouse handoff, customer messages, location data, promised window, and open question',boundary:'declaring fault, promising compensation, changing delivery instructions, or filing an unauthorized claim',caseStudy:'The carrier scan predates the warehouse dispatch timestamp by six hours.',metric:'timelines with missing events, conflicting clocks, or unresolved ownership'},
  {slug:'filipino-employee-training-expiry-coordinator',title:'Planning a Filipino employee training expiry queue',excerpt:'Maintain renewal evidence and reminders while qualified owners decide compliance and work eligibility.',lane:'employee training expiry coordination',owner:'people, safety, or compliance owner',packet:'the worker identifier, required course, rule source, completion record, expiry date, reminder history, and exception owner',boundary:'certifying competence, waiving training, interpreting a requirement, or suspending work',caseStudy:'A certificate has a completion date but no expiry rule or approved renewal interval.',metric:'records with missing rules, evidence, dates, or owner decisions'},
  {slug:'filipino-property-lease-document-index-assistant',title:'A bounded role for Filipino property lease document indexing',excerpt:'Index lease records and dates without offering legal interpretation or triggering lease actions.',lane:'property lease document indexing',owner:'property or legal owner',packet:'the property, parties, signed document, amendment chain, stated dates, notice address, source location, and review state',boundary:'interpreting terms, calculating obligations, sending notice, or changing a lease record',caseStudy:'An amendment changes the term but refers to a schedule missing from the document folder.',metric:'indexes held for signature, amendment, schedule, date, or entity gaps'},
  {slug:'filipino-customer-data-export-packet-coordinator',title:'How to scope Filipino customer data export packet coordination',excerpt:'Collect approved export evidence while privacy owners control identity, scope, redaction, and release.',lane:'customer data export packet coordination',owner:'privacy or data-request owner',packet:'the request identifier, verified scope state, systems searched, export files, exclusions, redaction state, and release approval',boundary:'verifying identity, interpreting rights, choosing exclusions, or releasing personal data',caseStudy:'The account email matches, but the request asks for records tied to a second household member.',metric:'packets paused for identity, scope, search, redaction, or release decisions'},
  {slug:'filipino-board-report-source-check-assistant',title:'Building a Filipino board report source-checking workflow',excerpt:'Trace board-report figures to dated sources while executives retain interpretation and sign-off.',lane:'board report source checking',owner:'executive, finance, or governance owner',packet:'the slide, exact figure, definition, source file, reporting period, calculation note, owner, and revision',boundary:'changing a metric, explaining performance, forecasting results, or approving the board pack',caseStudy:'A revenue chart uses the latest month while its denominator comes from the prior quarter.',metric:'figures held for definition, period, calculation, source, or approval conflicts'},
];

function buildDetail(t: Topic) {
  const sections = [
    {title:'Define the record, not just the job title',paragraphs:[`Start ${t.lane} with a visible packet: ${t.packet}. The worker should be able to show where every field came from and mark a gap without guessing.`,`Write down the entry condition, the finish condition, and the events that send work back to an owner. That turns a broad assistant role into a reviewable routine.`]},
    {title:'Keep authority on the client side',paragraphs:[`A coordinator may collect, compare, label, and route approved records. The role does not include ${t.boundary}.`,`Name the ${t.owner} on the queue and show how to reach that person. Familiarity, urgency, and a previous answer do not create fresh authority.`]},
    {title:'Rehearse the uncomfortable example',paragraphs:[`${t.caseStudy} Preserve both sources, state the mismatch without choosing a winner, and ask one focused question.`,`Test this case beside one ordinary record and one incomplete record. Those three examples reveal whether the guide explains what to do or merely describes the happy path.`]},
    {title:'Make the next handoff legible',paragraphs:[`A useful note records the last source checked, current state, unresolved difference, waiting owner, and action that remains paused. “Done” or “handled” is too thin for another shift to trust.`,`Use named accounts, minimum permissions, multifactor authentication where available, and an agreed removal date. Keep sensitive evidence in the approved system rather than copying it into chat.`]},
    {title:'Review the evidence trail',paragraphs:[`Sample completed packets against their original sources and track ${t.metric}. Always pair counts with the review window and eligible volume.`,`Separate missing inputs, transcription mistakes, stale sources, conflicting evidence, unclear instructions, and out-of-scope requests. Different failure modes need different fixes.`]},
    {title:'Expand only after the routine holds up',paragraphs:[`Ask a second reviewer to reproduce the status and find the ${t.owner} using only the packet and guide. If private context is required, the workflow is not ready to scale.`,`A new system, audience, data class, or decision changes the work. Review scope and access again before adding it to the lane.`]},
  ];
  return {datePublished:date,dateModified:date,image:{src:'/article-planning.svg',alt:`Planning board for ${t.lane}`,caption:`A bounded ${t.lane} routine keeps evidence, stop rules, and ownership visible.`},shortAnswer:`Build ${t.lane} around a defined packet, a tested exception, minimum access, and a named ${t.owner}.`,takeaways:['Define a complete packet and its sources.','Test ordinary, incomplete, and conflicting records.',`Keep decisions with the ${t.owner}.`,'Scale only when another reviewer can reproduce the handoff.'],sections,sourceArticleText:`${t.title}. ${t.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,sources:[{name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine principles for proportionate and secure personal-data handling.'},{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Practical account-security guidance for named access.'}],faqs:[{question:'What can the coordinator finish?',answer:`The coordinator can prepare and route the documented ${t.lane} packet.`},{question:'Who decides an exception?',answer:`The ${t.owner} retains decision and approval authority.`},{question:'What should the first review cover?',answer:'Compare an ordinary record, an incomplete record, and the rehearsed conflict with their original sources.'}],tags:[t.lane,'Filipino outsourcing','Workflow design'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Build a staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Use the onboarding checklist'}]};
}

export const september7BlogPosts = topics.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10,image:'/article-planning.svg'}));
export const september7BlogDetails = Object.fromEntries(topics.map(topic => [topic.slug, buildDetail(topic)]));
