const date = '2026-09-01' as const;

type Topic = { slug:string; title:string; excerpt:string; lane:string; owner:string; inputs:string; stop:string; exception:string; measures:string };

const topics: readonly Topic[] = [
  {slug:'filipino-cash-application-evidence-coordinator',title:'How to scope Filipino cash application evidence support',excerpt:'Prepare payment-to-invoice evidence while finance retains posting and exception authority.',lane:'cash application evidence',owner:'accounts receivable owner',inputs:'bank reference, remittance advice, customer account, invoice list, currency, amount, and receipt timestamp',stop:'posting a receipt, choosing an invoice when evidence conflicts, or changing a customer balance',exception:'one payment reference covers two accounts but the remittance advice names only one',measures:'payments prepared, unmatched references, value conflicts, returned packets, and owner wait time'},
  {slug:'filipino-supplier-master-change-records-coordinator',title:'How to plan Filipino supplier master change records support',excerpt:'Assemble vendor change evidence without approving bank, tax, identity, or payment-record updates.',lane:'supplier master change records',owner:'procurement or finance owner',inputs:'request as received, supplier identifier, current record, proposed value, verification status, requester channel, and approval history',stop:'verifying identity, approving a bank change, or editing the authoritative supplier record',exception:'a bank-detail request arrives from a familiar address but bypasses the approved change channel',measures:'requests logged, verification gaps, conflicting values, approvals pending, and confirmed changes'},
  {slug:'filipino-customer-renewal-evidence-assistant',title:'How to scope Filipino customer renewal evidence preparation',excerpt:'Organize renewal dates, usage records, and approved terms while account owners keep commercial decisions.',lane:'customer renewal evidence preparation',owner:'account manager',inputs:'signed terms, renewal date, current plan, approved pricing, usage record, open support items, and contact history',stop:'changing price, promising a concession, interpreting a contract, or committing the company',exception:'the CRM renewal date differs from the signed agreement and a draft quote uses a third date',measures:'packets prepared, date conflicts, missing terms, owner questions, and approved follow-ups'},
  {slug:'filipino-website-accessibility-issue-log-coordinator',title:'How to plan Filipino website accessibility issue logging',excerpt:'Document reproducible interface observations while product owners retain remediation and compliance judgments.',lane:'website accessibility issue logging',owner:'product accessibility owner',inputs:'page URL, device, browser, assistive setting, exact steps, observed result, expected behavior, and supporting capture',stop:'declaring legal compliance, assigning severity, or publishing a remediation commitment',exception:'a keyboard path works in one browser but traps focus in another supported browser',measures:'issues reproduced, environment gaps, duplicate reports, owner classifications, and retest results'},
  {slug:'filipino-sales-contract-metadata-coordinator',title:'How to scope Filipino sales contract metadata coordination',excerpt:'Extract approved contract fields for review without interpreting obligations or changing commercial records.',lane:'sales contract metadata coordination',owner:'legal or commercial owner',inputs:'executed document, counterparty, effective date, term, renewal wording, notice field, governing version, and repository identifier',stop:'interpreting a clause, deciding an obligation, or treating an unsigned draft as authoritative',exception:'the signature page and repository name reference different document versions',measures:'records indexed, version conflicts, missing signatures, owner decisions, and corrected metadata'},
  {slug:'filipino-order-fraud-review-packet-assistant',title:'How to plan Filipino order fraud review packet support',excerpt:'Collect order and account signals while authorized risk owners retain fraud and fulfillment decisions.',lane:'order fraud review packet preparation',owner:'fraud or risk owner',inputs:'order identifier, account history, payment-system result, delivery fields, device signal supplied by approved tools, and prior review notes',stop:'labeling a person fraudulent, canceling an order, contacting law enforcement, or overriding a risk control',exception:'the billing check passes while the delivery change and account history trigger conflicting signals',measures:'packets assembled, missing signals, conflicts, owner dispositions, and review age'},
  {slug:'filipino-employee-equipment-return-records-coordinator',title:'How to scope Filipino employee equipment return records',excerpt:'Track assigned assets and return evidence while HR, IT, and security retain employment and access decisions.',lane:'employee equipment return records',owner:'HR and IT asset owners',inputs:'asset register, assignee, approved separation notice, return instructions, carrier reference, received condition, and access-removal status',stop:'making an employment judgment, withholding pay, disabling an account, or deciding loss liability',exception:'a laptop is returned but a separately assigned security key is absent from the shipment',measures:'assets due, returns confirmed, missing items, access checks pending, and owner closures'},
  {slug:'filipino-product-catalog-source-records-assistant',title:'How to plan Filipino product catalog source records support',excerpt:'Prepare product fields from approved sources without inventing claims, compatibility, pricing, or availability.',lane:'product catalog source records',owner:'merchandising owner',inputs:'approved product sheet, SKU, variant, dimensions, materials, claim approvals, price source, and asset reference',stop:'creating a product claim, resolving a source conflict, changing price, or publishing a listing',exception:'the supplier sheet and approved packaging artwork show different material descriptions',measures:'SKUs prepared, source gaps, field conflicts, owner corrections, and publication approvals'},
  {slug:'filipino-service-credit-case-records-coordinator',title:'How to scope Filipino service credit case records',excerpt:'Build SLA-event timelines and evidence packets while service owners retain eligibility and remedy decisions.',lane:'service credit case records',owner:'service delivery owner',inputs:'customer request, applicable agreement, service events, monitoring source, exclusion records, calculation inputs, and communication history',stop:'interpreting an SLA, accepting fault, calculating an unapproved remedy, or issuing credit',exception:'monitoring shows an outage but the affected service boundary differs from the contracted scope',measures:'cases prepared, event gaps, scope conflicts, owner decisions, and approved responses'},
  {slug:'filipino-donation-receipt-records-assistant',title:'How to plan Filipino donation receipt records support',excerpt:'Organize contribution evidence while authorized finance owners retain classification, correction, and issuance decisions.',lane:'donation receipt records',owner:'nonprofit finance owner',inputs:'transaction record, donor-provided details, fund designation, receipt policy, correction history, approval status, and delivery channel',stop:'providing tax advice, changing donor identity, classifying a contribution, or issuing an unapproved receipt',exception:'the payer name differs from the donor name requested for the receipt',measures:'records prepared, identity differences, designation questions, approvals waiting, and delivery failures'},
  {slug:'filipino-warranty-claim-evidence-coordinator',title:'How to scope Filipino warranty claim evidence coordination',excerpt:'Assemble product, purchase, and condition evidence without determining warranty coverage or remedy.',lane:'warranty claim evidence coordination',owner:'warranty or quality owner',inputs:'claim as received, product identifier, purchase evidence, warranty version, issue description, diagnostic record, and prior service history',stop:'deciding coverage, attributing cause, authorizing replacement, or making a safety judgment',exception:'the product identifier is valid but purchase evidence predates the recorded warranty start',measures:'claims assembled, identifier gaps, policy conflicts, diagnostic waits, and owner decisions'},
  {slug:'filipino-board-meeting-action-records-coordinator',title:'How to plan Filipino board meeting action records support',excerpt:'Maintain approved actions and evidence while directors and officers retain governance decisions.',lane:'board meeting action records',owner:'corporate secretary or governance owner',inputs:'approved minutes, resolution identifier, exact action wording, named owner, due date, dependency, confidentiality level, and completion evidence',stop:'interpreting a resolution, changing minutes, disclosing restricted material, or speaking for the board',exception:'draft minutes name an action owner but the approved resolution names only a committee',measures:'actions recorded, ownership gaps, due dates missing, evidence returns, and governance reviews'},
];

function buildDetail(t: Topic) {
  const sections = [
    {title:'Define the source packet',paragraphs:[`A ${t.lane} queue begins with ${t.inputs}. Preserve the source location and checking time for every consequential field.`,`Completeness means the packet is ready for review, not that the requested outcome is approved. The ${t.owner} remains visible beside every decision field.`]},
    {title:'Set an explicit authority boundary',paragraphs:[`A Filipino coordinator may collect, label, compare, and route approved records. The role stops before ${t.stop}.`,`Use a written “owner review required” state. Silence, an approaching deadline, or a clean checklist does not expand authority.`]},
    {title:'Test conflicting evidence',paragraphs:[`Practice this stop case before launch: ${t.exception}. Keep both sources, state the disagreement exactly, pause the consequential action, and route one focused question.`,`Also test one ordinary record and one incomplete record. Corrections should update the written example with an effective date rather than remain in private chat.`]},
    {title:'Limit access and preserve continuity',paragraphs:[`Grant named access only to systems required for ${t.lane}. Record purpose, permission, approver, review date, and same-day removal steps.`,`A handoff names the last source checked, open question, current status, next owner, and approved substitute path. A substitute should never need to guess.`]},
    {title:'Review the source, not only the tracker',paragraphs:[`Sample the original evidence against the prepared packet. Classify returns as missing evidence, transcription error, stale source, source conflict, weak instruction, or judgment outside the role.`,`Track ${t.measures}. These are workflow signals, not guarantees of compliance, savings, accuracy, speed, revenue, or another business outcome.`]},
    {title:'Expand only after the lane is reproducible',paragraphs:[`Before increasing volume, ask a second reviewer to explain the intake, finish point, source hierarchy, stop case, access boundary, and ${t.owner} decision path.`,`If the explanation depends on memory, narrow the queue. New systems, data classes, audiences, or decisions require a fresh scope and access review.`]},
  ];
  const sourceArticleText = `${t.title}. ${t.excerpt} ` + sections.flatMap(s=>s.paragraphs).join(' ');
  return {datePublished:date,dateModified:date,image:{src:'/article-planning.svg',alt:`Planning board for ${t.lane}`,caption:`A bounded ${t.lane} workflow keeps sources and ownership visible.`},shortAnswer:`Scope ${t.lane} around a finite source packet, tested exceptions, limited access, and a named ${t.owner}.`,takeaways:[`Define the source and finish point for ${t.lane}.`,'Preserve gaps and conflicting evidence.',`Keep consequential decisions with the ${t.owner}.`,'Expand only after sampled work is reproducible.'],sections,sourceArticleText,sources:[{name:'CISA: Require multifactor authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Account-security guidance for named access.'}],faqs:[{question:'What can the coordinator complete?',answer:'The coordinator can prepare and route the defined evidence packet using approved systems and examples.'},{question:'Who decides exceptions?',answer:`The ${t.owner} decides exceptions and approves any scope expansion.`},{question:'What should the first review include?',answer:'Review an ordinary record, an incomplete record, and the documented stop case.'}],tags:[t.lane,'Philippines staffing','Operations controls'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Onboarding checklist'}]};
}

export const september1BlogPosts = topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:10}));
export const september1BlogDetails = Object.fromEntries(topics.map(t=>[t.slug,buildDetail(t)]));
