const date = '2026-09-08' as const;

type Topic = { slug:string; title:string; excerpt:string; lane:string; owner:string; packet:string; boundary:string; exception:string; metric:string };

const topics: readonly Topic[] = [
  {slug:'filipino-vendor-master-change-evidence-assistant',title:'How to Scope a Filipino Vendor Master Change Evidence Assistant',excerpt:'Prepare traceable vendor-change packets while finance owners retain approval and system authority.',lane:'vendor master change evidence',owner:'finance or procurement owner',packet:'request, vendor identity, changed fields, bank-verification state, source documents, requester, approver, and effective date',boundary:'verifying bank details independently, approving a supplier, changing the master record, or releasing payment',exception:'A bank-change request arrives from a familiar email address, but the supporting letter names a different legal entity.',metric:'packets held for identity, source, approval, or effective-date gaps'},
  {slug:'filipino-saas-license-reclamation-queue-coordinator',title:'Building a Filipino SaaS License Reclamation Queue',excerpt:'Organize inactive-license evidence without letting coordinators revoke access or judge business need.',lane:'SaaS license reclamation coordination',owner:'system or security owner',packet:'user, application, assigned plan, last activity, employment state, dependency, manager response, and review status',boundary:'revoking access, interpreting inactivity, approving an exception, or changing a subscription',exception:'A dormant user account owns a workflow integration that has no documented service owner.',metric:'licenses waiting on identity, dependency, owner, or exception decisions'},
  {slug:'filipino-accounts-receivable-dispute-file-assistant',title:'A Safe Workflow for Filipino Accounts Receivable Dispute Files',excerpt:'Assemble dispute evidence while authorized client staff decide credits, collections, and accounting treatment.',lane:'accounts receivable dispute file preparation',owner:'finance or account owner',packet:'invoice, contract or order, delivery evidence, customer message, prior credits, disputed amount, response history, and decision state',boundary:'accepting a dispute, issuing a credit, changing the ledger, or threatening collection',exception:'The customer disputes a line item that appears in the signed order but not in the implementation handoff.',metric:'files paused for contract, delivery, amount, ownership, or approval conflicts'},
  {slug:'filipino-product-recall-contact-list-coordinator',title:'Planning Filipino Product Recall Contact List Support',excerpt:'Prepare controlled contact lists while safety, legal, and operations owners direct recall decisions.',lane:'product recall contact-list preparation',owner:'safety, legal, or operations owner',packet:'approved affected-item scope, lot or serial identifier, customer record, channel, contact status, response, and escalation owner',boundary:'defining recall scope, judging risk, drafting unapproved claims, or sending a notice',exception:'A customer bought a bundle containing one affected item, but the order record stores only the bundle SKU.',metric:'records held for item matching, contact data, message approval, or escalation'},
  {slug:'filipino-b2b-renewal-obligation-tracker',title:'Scoping a Filipino B2B Renewal Obligation Tracker',excerpt:'Track dated renewal evidence without transferring contract interpretation or commercial authority.',lane:'B2B renewal obligation tracking',owner:'commercial or legal owner',packet:'agreement, amendment chain, customer entity, stated term, notice detail, commercial owner, source location, and review status',boundary:'interpreting a clause, calculating legal deadlines, sending notice, or committing commercial terms',exception:'An amendment extends service but does not expressly update the renewal paragraph in the original agreement.',metric:'records with missing agreements, amendments, dates, entities, or owner review'},
  {slug:'filipino-marketplace-seller-verification-packet-assistant',title:'How to Brief a Filipino Marketplace Seller Verification Packet Assistant',excerpt:'Collect seller records and discrepancies while compliance owners make verification and access decisions.',lane:'marketplace seller verification packet preparation',owner:'compliance or marketplace owner',packet:'seller identity, business record, payout name, submitted document, capture date, discrepancy log, review state, and owner',boundary:'certifying identity, interpreting regulation, approving a seller, or enabling payouts',exception:'The registration document is current, but its trading name differs from the marketplace profile and payout account.',metric:'packets paused for identity, document, payout, freshness, or ownership gaps'},
  {slug:'filipino-customer-success-health-signal-register-assistant',title:'Designing a Filipino Customer Success Health Signal Register',excerpt:'Trace customer-health signals to sources without turning a register into an automated account judgment.',lane:'customer success health-signal registration',owner:'customer success or account owner',packet:'account, signal definition, source event, observation window, current value, prior value, data gap, and owner note',boundary:'assigning account risk, forecasting renewal, promising intervention, or changing commercial status',exception:'Usage falls after a tracking migration, while support volume also drops because tickets moved to a new channel.',metric:'signals held for definition, source, window, migration, or owner interpretation'},
  {slug:'filipino-facilities-work-order-closeout-assistant',title:'A Practical Filipino Facilities Work Order Closeout Routine',excerpt:'Compile closeout evidence while property owners retain safety, acceptance, and payment decisions.',lane:'facilities work-order closeout',owner:'facilities or property owner',packet:'work order, site, approved scope, completion note, timestamped evidence, exception, invoice reference, and acceptance state',boundary:'certifying safety, accepting work, approving an invoice, or changing maintenance scope',exception:'The technician marks the job complete, but the photo shows a temporary repair and no return date.',metric:'closeouts waiting on scope, evidence, safety, acceptance, or invoice review'},
  {slug:'filipino-returns-disposition-evidence-coordinator',title:'Building a Filipino Returns Disposition Evidence Queue',excerpt:'Document returned-item condition and policy inputs while owners decide refunds, resale, and disposal.',lane:'returns disposition evidence coordination',owner:'returns, inventory, or finance owner',packet:'return authorization, item identity, received date, condition evidence, policy version, stated exception, inventory state, and owner decision',boundary:'grading condition, approving a refund, returning stock to sale, or authorizing disposal',exception:'The warehouse photo shows intact packaging, but the serial number does not match the authorized return.',metric:'returns held for identity, condition, policy, inventory, or decision gaps'},
  {slug:'filipino-clinical-referral-record-routing-assistant',title:'Boundaries for a Filipino Clinical Referral Record Routing Assistant',excerpt:'Route complete referral records while licensed and authorized owners retain clinical decisions.',lane:'clinical referral record routing',owner:'authorized clinical or referral owner',packet:'patient identifier, referral source, destination, received timestamp, required document checklist, consent state, routing status, and exception',boundary:'triaging clinically, interpreting records, selecting treatment, or disclosing information outside the approved channel',exception:'A referral names one specialty while the attached note requests a different service and contains no urgency instruction.',metric:'records held for identity, document, consent, destination, or clinical-owner review'},
  {slug:'filipino-digital-asset-rights-register-coordinator',title:'How to Run a Filipino Digital Asset Rights Register',excerpt:'Link creative assets to approved usage evidence while legal and brand owners retain rights decisions.',lane:'digital asset rights registration',owner:'brand or legal owner',packet:'asset identifier, creator or supplier, license source, permitted channel, territory, term, attribution requirement, derivative state, and approver',boundary:'interpreting a license, clearing rights, changing creative work, or publishing an asset',exception:'A stock image is cleared for web use, but a campaign brief also requests paid social and partner syndication.',metric:'assets held for license, channel, territory, term, attribution, or approval gaps'},
  {slug:'filipino-procurement-bid-comparison-file-assistant',title:'Scoping a Filipino Procurement Bid Comparison File',excerpt:'Normalize supplier evidence for review while procurement owners retain scoring and award authority.',lane:'procurement bid comparison preparation',owner:'procurement or business owner',packet:'approved requirement, supplier response, price basis, currency, stated exclusions, delivery assumption, evidence link, and clarification status',boundary:'scoring a bid, interpreting terms, negotiating, selecting a supplier, or announcing an award',exception:'One supplier quotes an annual total including implementation while another separates setup and excludes tax.',metric:'comparisons held for scope, currency, exclusions, assumptions, or clarification'},
];

function buildDetail(t: Topic) {
  const sections = [
    {title:'Define the packet before assigning the queue',paragraphs:[`Treat ${t.lane} as a record routine, not an open-ended job description. A complete packet contains the ${t.packet}. Each field should point to an approved source or carry an explicit missing state.`,`Document the entry condition, completion condition, and the events that pause work. A coordinator can then hand off a consistent packet without inventing facts to keep the queue moving.`]},
    {title:'Keep consequential authority with the client',paragraphs:[`The coordinator may collect, transcribe, compare, label, and route approved records. The role excludes ${t.boundary}.`,`Name the ${t.owner} in the operating guide. Urgency, familiarity, or a previous approval does not authorize a new decision.`]},
    {title:'Test a conflict before launch',paragraphs:[`${t.exception} The safe response is to preserve both records, state the mismatch plainly, pause the affected action, and route one focused question to the owner.`,`Rehearse that example beside one ordinary item and one incomplete item. If two reviewers reach different queue states, revise the definition or example before adding volume.`]},
    {title:'Protect access and sensitive evidence',paragraphs:[`Use named accounts, minimum permissions, multifactor authentication where available, and an agreed removal trigger. Keep evidence in the approved system rather than duplicating it in chat or private files.`,`Mask unnecessary personal or commercial data in training examples. Record who can view, edit, approve, and export the packet, and review those permissions when the scope changes.`]},
    {title:'Make handoffs reproducible',paragraphs:[`A useful handoff names the last source checked, current state, unresolved difference, waiting owner, and paused next action. Labels such as “handled” or “done” do not let another shift reconstruct the result.`,`Use a dated instruction version and retain corrections. Quietly replacing an earlier record makes review easier to read but harder to trust.`]},
    {title:'Measure the routine without overclaiming',paragraphs:[`Track ${t.metric}. Pair every count with its eligible volume, observation window, definition version, and exclusions.`,`Separate missing inputs, transcription errors, stale sources, conflicting evidence, unclear instructions, and owner-wait time. Those failure modes require different fixes and should not become a single worker score.`]},
  ];
  return {datePublished:date,dateModified:date,image:{src:'/article-planning.svg',alt:`Planning board for ${t.lane}`,caption:`A bounded ${t.lane} workflow keeps sources, stop rules, and owners visible.`},shortAnswer:`Scope ${t.lane} around a defined packet, a rehearsed exception, minimum access, and a named ${t.owner}.`,takeaways:['Define the packet and acceptable source for each field.','Rehearse ordinary, incomplete, and conflicting records.',`Keep decisions with the ${t.owner}.`,'Scale only when another reviewer can reproduce the handoff.'],sections,sourceArticleText:`${t.title}. ${t.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,sources:[{name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine principles for proportionate, accurate, and secure handling of personal data.'},{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Practical guidance for protecting named accounts.'}],faqs:[{question:'What can the coordinator complete?',answer:`The coordinator can prepare, document, and route the defined ${t.lane} packet.`},{question:'Who decides an exception?',answer:`The ${t.owner} retains approval and consequential decision authority.`},{question:'What should the first quality review cover?',answer:'Compare an ordinary item, an incomplete item, and the rehearsed conflict against their original sources.'}],tags:[t.lane,'Filipino outsourcing','Workflow controls'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Build a staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Use the onboarding checklist'}]};
}

export const september8BlogPosts = topics.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10,image:'/article-planning.svg'}));
export const september8BlogDetails = Object.fromEntries(topics.map(topic => [topic.slug, buildDetail(topic)]));
