const date = '2026-08-31' as const;

type Topic = {
  slug: string; title: string; excerpt: string; lane: string; owner: string;
  intake: string; decision: string; evidence: string; edge: string; measure: string;
};

const topics: readonly Topic[] = [
  { slug:'filipino-customer-credit-memo-preparation-coordinator', title:'How to scope Filipino customer credit memo preparation', excerpt:'Build a source-linked credit memo packet while finance retains approval and posting authority.', lane:'customer credit memo preparation', owner:'finance controller', intake:'the invoice, customer request, approved policy reference, prior adjustments, tax treatment note, and account identifier', decision:'whether a credit is valid, its amount, its accounting treatment, and when it may be posted', evidence:'original invoice, correspondence, calculation sheet, approval record, and ledger reference', edge:'a request cites a discount that is absent from the signed order', measure:'packets prepared, missing approvals, calculation returns, duplicate requests, and controller wait time' },
  { slug:'filipino-product-return-inspection-records-coordinator', title:'How to plan Filipino product return inspection records support', excerpt:'Organize condition evidence and return records without deciding refunds, warranty coverage, or inventory disposition.', lane:'product return inspection records', owner:'returns or quality manager', intake:'the return authorization, item identifier, customer statement, received timestamp, condition photos, inspection checklist, and shipment record', decision:'whether the return qualifies, who caused damage, what remedy applies, and how the item is dispositioned', evidence:'unaltered photographs, carrier events, serial or lot details, checklist version, and reviewer notes', edge:'the received serial number does not match the return authorization', measure:'returns logged, evidence gaps, identifier conflicts, inspection returns, and owner decisions outstanding' },
  { slug:'filipino-subscription-cancellation-case-preparation-assistant', title:'How to scope Filipino subscription cancellation case preparation', excerpt:'Prepare cancellation facts and fulfillment status while the account owner keeps policy and remedy decisions.', lane:'subscription cancellation case preparation', owner:'customer account owner', intake:'the customer request, account plan, contract or policy version, renewal date, billing status, prior contacts, and requested outcome', decision:'whether cancellation is effective, whether a fee or refund applies, and what promise can be made to the customer', evidence:'original request, account history, applicable terms, transaction records, and approved response', edge:'the customer says an earlier agent promised a date that is not recorded in the account', measure:'cases assembled, missing terms, disputed promises, owner escalations, and reopened cases' },
  { slug:'filipino-procurement-bid-comparison-coordinator', title:'How to plan Filipino procurement bid comparison support', excerpt:'Normalize supplier submissions for review without selecting a vendor or interpreting commercial risk.', lane:'procurement bid comparison', owner:'procurement lead', intake:'the approved requirements, supplier submissions, currency and tax fields, delivery assumptions, exclusions, validity dates, and clarification responses', decision:'which supplier is preferred, whether an exception is acceptable, and what commercial terms should be negotiated', evidence:'versioned bid files, requirement matrix, clarification log, normalization notes, and approval trail', edge:'one bid bundles an optional service while another records it as mandatory', measure:'bids normalized, unanswered clarifications, non-comparable fields, version conflicts, and decision waits' },
  { slug:'filipino-software-license-inventory-coordinator', title:'How to scope Filipino software license inventory coordination', excerpt:'Maintain license and assignment evidence while system owners retain access, renewal, and purchasing decisions.', lane:'software license inventory coordination', owner:'IT asset owner', intake:'the product name, subscription record, assigned account, seat type, owner, renewal date, business purpose, and source system', decision:'who should retain access, whether a license renews, what tier is appropriate, and whether an account is disabled', evidence:'vendor invoice, admin-console export, named-user record, approval request, and removal confirmation', edge:'an active seat belongs to a departed user but also owns shared automation', measure:'licenses reconciled, unassigned seats, source conflicts, missing owners, and removal confirmations' },
  { slug:'filipino-customer-data-correction-request-coordinator', title:'How to plan Filipino customer data correction request coordination', excerpt:'Route record-correction evidence with narrow access and a clear privacy-owner decision path.', lane:'customer data correction request coordination', owner:'privacy or data owner', intake:'the requester identity-check status, exact field challenged, stated correction, record locations, source provenance, and communication history', decision:'whether identity is sufficient, which record controls, what must change, and what disclosure can be sent', evidence:'request as received, verification outcome from the authorized owner, system extracts, change record, and response approval', edge:'the requested correction conflicts with a controlled transaction record', measure:'requests received, identity checks pending, systems searched, conflicts routed, and corrections confirmed' },
  { slug:'filipino-event-sponsor-deliverables-coordinator', title:'How to scope Filipino event sponsor deliverables coordination', excerpt:'Track approved sponsor assets and fulfillment evidence without changing benefits or making commercial commitments.', lane:'event sponsor deliverables coordination', owner:'partnerships manager', intake:'the signed benefit schedule, asset specifications, due dates, brand files, approval status, event run sheet, and contact list', decision:'whether a late asset is accepted, a benefit is substituted, or a sponsor receives an additional commitment', evidence:'agreement version, submitted asset, approval message, publication proof, placement record, and completion note', edge:'a sponsor requests a stage mention that is absent from the approved schedule', measure:'deliverables due, assets awaiting approval, fulfillment proofs, scope questions, and sponsor-owner waits' },
  { slug:'filipino-facilities-maintenance-request-records-assistant', title:'How to plan Filipino facilities maintenance request records support', excerpt:'Keep work-order evidence and handoffs visible while facilities owners retain safety and dispatch authority.', lane:'facilities maintenance request records', owner:'facilities manager', intake:'the location, requester statement, asset identifier, observed condition, access window, prior work, photos, and urgency stated by the requester', decision:'how hazardous the condition is, which technician attends, what repair is authorized, and whether a site can remain open', evidence:'original request, inspection note, approved work order, technician update, parts record, and closure approval', edge:'a water report appears minor in the ticket but a photo shows proximity to electrical equipment', measure:'requests logged, missing locations, repeat assets, safety escalations, technician waits, and owner-closed orders' },
  { slug:'filipino-learning-certificate-records-coordinator', title:'How to scope Filipino learning certificate records coordination', excerpt:'Prepare attendance and issuance records without certifying competence or changing program requirements.', lane:'learning certificate records coordination', owner:'learning program owner', intake:'the learner identifier, approved course version, session record, attendance source, required activities, assessor decision, and issuance rule', decision:'whether requirements were satisfied, an exception is allowed, or a person is competent or qualified', evidence:'registration, attendance log, assessment outcome supplied by the owner, certificate identifier, and delivery record', edge:'attendance is complete but the approved assessment result is missing', measure:'records checked, missing outcomes, duplicate certificates, delivery failures, and owner approvals pending' },
  { slug:'filipino-vendor-invoice-tax-document-coordinator', title:'How to plan Filipino vendor invoice tax document coordination', excerpt:'Assemble invoice and tax-document evidence while qualified finance owners retain classification and payment authority.', lane:'vendor invoice tax document coordination', owner:'qualified finance reviewer', intake:'the invoice, purchase order, receipt evidence, vendor master record, tax document, jurisdiction field, currency, and prior exception history', decision:'the tax classification, deductibility, withholding treatment, payment release, and any correction posted to the books', evidence:'supplier document, approved order, receiving record, calculation supplied by finance, approval, and posting reference', edge:'the vendor name matches but the tax identifier differs from the approved master record', measure:'documents matched, tax records missing, identifier conflicts, finance returns, and payment holds recorded' },
  { slug:'filipino-customer-success-action-register-coordinator', title:'How to scope Filipino customer success action-register coordination', excerpt:'Turn meeting commitments into traceable actions without inventing promises or account strategy.', lane:'customer success action-register coordination', owner:'customer success manager', intake:'the approved meeting record, action wording, responsible person, stated due date, dependency, source link, and customer-visible status', decision:'what the company commits to, whether priority changes, what risk a delay creates, and what message goes to the customer', evidence:'meeting note, owner confirmation, task-system record, completion artifact, and approved customer update', edge:'meeting notes imply an action but do not identify who accepted it or a due date', measure:'actions captured, missing owners, overdue dependencies, reopened items, and customer updates awaiting approval' },
  { slug:'filipino-security-questionnaire-evidence-coordinator', title:'How to plan Filipino security questionnaire evidence coordination', excerpt:'Collect approved security evidence while security, legal, and commercial owners retain attestation authority.', lane:'security questionnaire evidence coordination', owner:'security assurance owner', intake:'the customer question, requested scope, approved answer library, current control evidence, system boundary, answer owner, and expiry date', decision:'whether a control is effective, whether the company complies, which exception is acceptable, and who may attest externally', evidence:'approved policy excerpt, control record, audit artifact, answer version, reviewer approval, and submission copy', edge:'a question uses a broader system scope than the evidence in the approved library', measure:'questions mapped, evidence expired, scope mismatches, owner reviews, and approved responses delivered' },
];

const buildDetail = (topic: Topic) => {
  const sections = [
    { title:'Define the record before assigning the queue', paragraphs:[`For ${topic.lane}, write the intake rule around ${topic.intake}. The record should preserve the source location and time checked so the reviewer can reproduce the preparation.`, `A complete intake is not an approved outcome. Name the ${topic.owner} beside the fields that require judgment, and keep missing evidence visible rather than filling gaps from memory.`] },
    { title:'Separate preparation from authority', paragraphs:[`A Filipino coordinator can collect, compare, label, schedule, and route approved records. The role stops before deciding ${topic.decision}.`, `Use an explicit status for “ready for owner review.” Do not let a clean checklist imply permission to post, promise, certify, select, disclose, or change a consequential record.`] },
    { title:'Build a traceable evidence packet', paragraphs:[`The useful packet contains ${topic.evidence}. Preserve original wording when a paraphrase could change the meaning.`, `When two sources disagree, show both values, their timestamps, and one precise question for the ${topic.owner}. The coordinator should not choose the value that makes the queue easier to close.`] },
    { title:'Practice the difficult case', paragraphs:[`Test the workflow with this exception: ${topic.edge}. The example should say what the worker records, what action pauses, and who receives the handoff.`, `Also test an ordinary item and an incomplete item. Those three samples reveal whether the procedure explains the real work or merely describes an ideal case.`] },
    { title:'Control access and continuity', paragraphs:[`Grant named access only to systems needed for ${topic.lane}. Record purpose, permission level, approver, review date, and the same-day removal step. Avoid shared credentials and uncontrolled exports.`, `Across Philippine and client working hours, the handoff should state the last verified event, unresolved question, next owner, and approved substitute path. Silence is not approval.`] },
    { title:'Review and measure the lane honestly', paragraphs:[`Sample source records, not only the final tracker. Classify corrections as missing evidence, transcription error, stale source, source conflict, weak instruction, or judgment outside the role.`, `Track ${topic.measure}. These are workflow signals, not guarantees of accuracy, savings, compliance, safety, satisfaction, revenue, or another business outcome.`] },
  ];
  const sourceArticleText = sections.flatMap(s=>s.paragraphs).join(' ') + ` The launch brief for ${topic.lane} should identify what begins the work, what constitutes a finished preparation, and which decisions remain with the ${topic.owner}. Reviewers should be able to trace every consequential field to an approved source without reconstructing private conversations. A returned item needs a reason code and a next action; “pending” by itself does not explain whether the queue is waiting for evidence, system access, an owner decision, or a response from another party. Corrections belong in the written procedure with an effective date so later workers receive the same rule. If a new request adds a system, information class, audience, or decision type, pause and approve the expanded scope before work continues. The purpose of Filipino support in this lane is dependable preparation: facts become easier to inspect, uncertainty becomes harder to overlook, and the authorized owner receives a focused question. Expand only after a second reviewer can explain the source hierarchy, normal example, incomplete example, stop case, access boundary, review cadence, and removal process.`;
  return { datePublished:date, dateModified:date, image:{src:'/article-planning.svg',alt:`Planning board for ${topic.lane}`,caption:`A bounded ${topic.lane} queue keeps evidence and ownership visible.`}, shortAnswer:`Scope ${topic.lane} around a finite evidence queue, named access, tested exceptions, and a ${topic.owner} who keeps consequential decisions.`, takeaways:[`Define the inputs and finish point for ${topic.lane}.`,`Preserve source evidence and disagreements.`,`Keep ${topic.decision} with the ${topic.owner}.`,'Expand only after sampled work is reproducible.'], sections, sourceArticleText, sources:[{name:'CISA: Require multifactor authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Named access and account-security guidance.'}], faqs:[{question:'What can the coordinator complete?',answer:'The coordinator can prepare and route the defined evidence packet using approved systems and examples.'},{question:'Who owns exceptions?',answer:`The ${topic.owner} owns consequential decisions and any expansion of scope.`},{question:'What should the first review sample?',answer:'Review an ordinary item, an incomplete item, and the documented stop case.'}], tags:[topic.lane,'Philippines staffing','Operations controls'], related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Onboarding checklist'},{href:'/services/data-processing-support',label:'Data processing support'}] };
};

export const august31BlogPosts = topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:10}));
export const august31BlogDetails = Object.fromEntries(topics.map(topic=>[topic.slug,buildDetail(topic)]));
