const published = '2026-09-14' as const;

type Brief = {
  slug: string;
  title: string;
  excerpt: string;
  queue: string;
  owner: string;
  fields: string;
  boundary: string;
  scenario: string;
};

const briefs: readonly Brief[] = [
  { slug:'filipino-customer-refund-evidence-assistant', title:'How to Scope a Filipino Customer Refund Evidence Assistant', excerpt:'Prepare refund evidence and exception notes while an authorized owner keeps policy and payment decisions.', queue:'customer refund evidence', owner:'customer operations or finance owner', fields:'case ID, order, request source, policy version, payment state, delivery evidence, exception, and reviewer', boundary:'the policy is unclear, identity is disputed, evidence conflicts, or money movement is requested', scenario:'A customer requests a refund after a replacement shipped, while the order system and payment record show different statuses.' },
  { slug:'filipino-procurement-intake-coordinator', title:'A Controlled Brief for a Filipino Procurement Intake Coordinator', excerpt:'Organize purchase requests and supplier records without transferring sourcing, budget, or approval authority.', queue:'procurement intake', owner:'procurement or budget owner', fields:'requester, need, specification source, supplier record, budget reference, due date, conflict flag, and approver', boundary:'a supplier must be selected, terms need interpretation, budget evidence is absent, or a conflict is disclosed', scenario:'A rush request names a preferred supplier, but the approval record covers another specification and an earlier price.' },
  { slug:'filipino-sales-contract-data-assistant', title:'Planning a Filipino Sales Contract Data Assistant', excerpt:'Extract approved contract facts into business systems while legal and commercial owners retain interpretation.', queue:'sales contract data administration', owner:'legal or commercial owner', fields:'customer, signed version, effective date, term, renewal notice, approved price source, obligation owner, and exception', boundary:'versions conflict, a clause needs interpretation, pricing differs, or a commitment is missing', scenario:'The signed order form lists an annual term while the CRM record and renewal reminder both describe a monthly agreement.' },
  { slug:'filipino-healthcare-appointment-records-coordinator', title:'Boundaries for a Filipino Healthcare Appointment Records Coordinator', excerpt:'Maintain scheduling evidence and patient contact preferences without making clinical or urgency decisions.', queue:'healthcare appointment records', owner:'authorized clinic or clinical owner', fields:'patient reference, request channel, consent state, appointment type, available window, contact preference, status, and escalation', boundary:'symptoms or urgency appear, identity is uncertain, consent is missing, or clinical advice is requested', scenario:'A scheduling message asks for the next routine slot but also mentions a new symptom and a different callback number.' },
  { slug:'filipino-property-vendor-document-assistant', title:'How a Filipino Property Vendor Document Assistant Should Work', excerpt:'Index vendor certificates and work records while property owners decide eligibility, risk, and authorization.', queue:'property vendor document control', owner:'property or risk owner', fields:'vendor, property, document type, issuing source, effective period, work order, exception, and decision owner', boundary:'coverage needs interpretation, a document appears altered, safety is involved, or work authorization is requested', scenario:'A vendor certificate is current for one entity name, while the invoice and work order use a similar but different name.' },
  { slug:'filipino-ecommerce-catalog-change-assistant', title:'Designing a Filipino Ecommerce Catalog Change Assistant', excerpt:'Prepare approved catalog updates with traceable sources while brand, pricing, and launch decisions stay client-owned.', queue:'ecommerce catalog change preparation', owner:'catalog, brand, or pricing owner', fields:'SKU, approved source, current value, proposed value, channel, effective time, dependency, and reviewer', boundary:'price or claim approval is absent, sources disagree, regulated wording appears, or a launch decision is needed', scenario:'A supplier sheet changes package size, but the approved product image and marketplace description still show the former quantity.' },
  { slug:'filipino-employee-onboarding-access-assistant', title:'A Safe Filipino Employee Onboarding Access Workflow', excerpt:'Coordinate approved onboarding access without granting identity, security, or employment decision authority.', queue:'employee onboarding access preparation', owner:'HR, system, or security owner', fields:'worker identity, start date, approved role, application, permission template, approver, completion evidence, and removal trigger', boundary:'identity conflicts, elevated access is requested, approval is missing, or the employment state changes', scenario:'A new hire needs four systems, but one request includes administrator rights that do not appear in the approved role matrix.' },
  { slug:'filipino-insurance-renewal-records-assistant', title:'Scoping a Filipino Insurance Renewal Records Assistant', excerpt:'Track renewal evidence and deadlines while licensed or authorized owners retain coverage and placement judgment.', queue:'insurance renewal record coordination', owner:'authorized insurance or risk owner', fields:'policy, insured entity, carrier source, stated expiry, request history, evidence received, open question, and owner', boundary:'coverage needs interpretation, values conflict, advice is requested, or binding authority is involved', scenario:'A renewal worksheet and carrier notice list different locations, and the latest email asks whether existing coverage is sufficient.' },
  { slug:'filipino-subscription-cancellation-records-assistant', title:'A Controlled Filipino Subscription Cancellation Records Role', excerpt:'Document cancellation requests and effective dates without deciding entitlement, refunds, or retention offers.', queue:'subscription cancellation records', owner:'billing or customer policy owner', fields:'account, requester, identity check, request time, plan, renewal date, policy source, action state, and exception', boundary:'identity is disputed, the policy is ambiguous, a refund is requested, or a retention exception is proposed', scenario:'A customer cancels before renewal, but the billing platform records the request after an overnight charge and a prior pause.' },
  { slug:'filipino-logistics-delivery-exception-assistant', title:'Planning a Filipino Logistics Delivery Exception Assistant', excerpt:'Assemble shipment events and customer evidence while logistics owners decide remedies and carrier disputes.', queue:'delivery exception preparation', owner:'logistics or customer operations owner', fields:'shipment, order, carrier event, promised window, delivery evidence, customer contact, exception type, and reviewer', boundary:'evidence conflicts, loss or damage is alleged, compensation is requested, or liability is questioned', scenario:'Tracking says delivered, but the proof image shows another doorway and the customer reported an address correction before dispatch.' },
  { slug:'filipino-marketing-consent-records-assistant', title:'How to Bound a Filipino Marketing Consent Records Assistant', excerpt:'Organize consent evidence and suppression events without making legal conclusions about permitted outreach.', queue:'marketing consent record administration', owner:'privacy, legal, or marketing policy owner', fields:'contact reference, purpose, collection source, notice version, timestamp, scope, withdrawal state, and reviewer', boundary:'the source is missing, purposes differ, withdrawal is disputed, or permission must be interpreted', scenario:'A contact appears on a campaign list with a timestamp but no stored notice version, while another system shows an opt-out.' },
  { slug:'filipino-month-end-close-evidence-assistant', title:'A Filipino Month-End Close Evidence Assistant Brief', excerpt:'Prepare reconciliations and missing-source queues while accountants keep classification, adjustment, and sign-off authority.', queue:'month-end close evidence preparation', owner:'accounting or finance owner', fields:'account, period, ledger source, supporting record, variance, preparer, reviewer, open item, and sign-off state', boundary:'classification is uncertain, records conflict, an adjustment is proposed, or payment authority is involved', scenario:'The ledger contains a vendor charge with no invoice, while a later credit memo references the same amount and another entity.' },
];

function detail(b: Brief) {
  const sections = [
    { title:'Define the eligible queue', paragraphs:[`${b.queue} needs a written entry rule and one authoritative work list. Each item should retain ${b.fields}. Missing evidence stays visible instead of being inferred from a similar record.`,`Document the event that starts work, the action that marks administrative completion, and the named reviewer. This prevents an assistant from inheriting authority simply because an item is old or urgent.`] },
    { title:'Keep decisions with the accountable owner', paragraphs:[`The assistant may retrieve approved records, compare stated fields, apply client-defined labels, request missing documents, and assemble a review packet. The ${b.owner} keeps the consequential decision.`,`Stop when ${b.boundary}. An escalation should cite the conflicting source, identify the blocked action, and ask one question that the owner can answer.`] },
    { title:'Test the rule with a boundary case', paragraphs:[`${b.scenario} Preserve both sources and their retrieval times; do not silently choose the version that appears newest or most convenient.`,`Training should include this boundary case, one complete case, and one item with a missing required source. If reviewers choose different routes, revise the rule before increasing volume.`] },
    { title:'Limit access and exports', paragraphs:[`Provide named accounts with only the systems and actions needed for ${b.queue}. Use multifactor authentication where supported and set a removal trigger before access begins.`,`Mask personal, financial, health, legal, employment, or commercial fields that the task does not require. Store exports only in approved locations and record who received them.`] },
    { title:'Preserve corrections and handoffs', paragraphs:[`A correction log should keep the old value, new value, source, reason, actor, and event time. Replacing history with a clean final record makes later review less reliable.`,`At handoff, list items received, packets prepared, missing evidence, approaching deadlines, and the owner of each paused decision. Avoid using private chat as the only decision record.`] },
    { title:'Review a bounded first-week sample', paragraphs:[`From September 8 through September 14, 2026, review consecutive eligible items under one dated instruction version. Count completeness, source conflicts, corrections, owner questions, and exclusions rather than selecting only polished examples.`,`The result describes that queue and observation window only. It is not proof of provider quality, savings, compliance, or business impact; report outages and excluded records beside the totals.`] },
  ];
  return {
    datePublished: published, dateModified: published,
    image:{src:'/article-planning.svg',alt:`Planning board for ${b.queue}`,caption:'A bounded workflow keeps sources, decisions, access, and review ownership visible.'},
    shortAnswer:`A Filipino assistant can support ${b.queue} when eligibility, evidence, stop conditions, and the ${b.owner} are documented before live work begins.`,
    takeaways:['Define entry and completion events in writing.','Retain missing and conflicting source evidence.',`Keep consequential approval with the ${b.owner}.`,'Review consecutive work under a dated instruction version.'],
    sections,
    sourceArticleText:`${b.title}. ${b.excerpt} ${sections.flatMap(section=>section.paragraphs).join(' ')}`,
    sources:[
      {name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary guidance for purpose limitation, proportionality, accuracy, and security.'},
      {name:'NIST: Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/',note:'Primary guidance for identity, authentication, and access lifecycle controls.'},
    ],
    faqs:[
      {question:'What may the assistant complete?',answer:`The assistant may prepare, document, and route the defined ${b.queue} packet.`},
      {question:'Who decides an exception?',answer:`The ${b.owner} decides any consequential exception or approval.`},
      {question:'What should the first audit inspect?',answer:'Inspect consecutive complete, incomplete, and conflicting items against their original sources.'},
    ],
    tags:[b.queue,'Filipino outsourcing','Operations controls'],
    related:[{href:'/blog/filipino-procurement-intake-coordinator',label:'Review another controlled workflow'},{href:'/research/philippines-outsourcing-source-conflict-research-2026',label:'Read the source-conflict research'}],
  };
}

export const september14BlogPosts = briefs.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10,image:'/article-planning.svg'}));
export const september14BlogDetails = Object.fromEntries(briefs.map(brief => [brief.slug, detail(brief)]));
