const date = '2026-09-02' as const;
type Topic={slug:string;title:string;excerpt:string;lane:string;owner:string;inputs:string;stop:string;exception:string};
const topics:readonly Topic[]=[
{slug:'filipino-purchase-order-change-evidence-coordinator',title:'How to scope Filipino purchase order change evidence support',excerpt:'Prepare change records while procurement owners retain approval and supplier-commitment authority.',lane:'purchase order change evidence',owner:'procurement owner',inputs:'approved order, requested change, requester, supplier message, price source, delivery date, and approval history',stop:'approving price, changing an order, or promising delivery',exception:'the supplier changes delivery and also inserts an unapproved quantity'},
{slug:'filipino-customer-identity-correction-records-assistant',title:'How to plan Filipino customer identity correction records support',excerpt:'Organize correction requests without deciding identity, ownership, or verification outcomes.',lane:'customer identity correction records',owner:'privacy or account owner',inputs:'request, account identifier, current value, proposed value, verification status, source, and history',stop:'deciding identity, bypassing verification, or editing the authoritative record',exception:'the requested name conflicts with the email and verification record'},
{slug:'filipino-marketing-consent-evidence-coordinator',title:'How to scope Filipino marketing consent evidence coordination',excerpt:'Assemble consent and preference records while owners keep legal-basis and outreach decisions.',lane:'marketing consent evidence',owner:'privacy or marketing owner',inputs:'contact identifier, collection source, wording, timestamp, channel, preference history, and suppression status',stop:'interpreting legal basis, restoring a contact, or authorizing outreach',exception:'the CRM shows consent while the email platform records a later unsubscribe'},
{slug:'filipino-invoice-dispute-timeline-assistant',title:'How to plan Filipino invoice dispute timeline support',excerpt:'Build a sourced chronology without deciding liability, credit, collection action, or accounting treatment.',lane:'invoice dispute timeline preparation',owner:'accounts receivable owner',inputs:'invoice, contract reference, messages, delivery evidence, adjustment history, payment status, and notes',stop:'accepting fault, issuing credit, changing a ledger, or interpreting terms',exception:'delivery evidence supports completion but email records a scope change'},
{slug:'filipino-saas-renewal-notice-register-assistant',title:'How to scope Filipino SaaS renewal notice register support',excerpt:'Maintain renewal notice evidence while IT and finance owners retain cancellation, purchasing, and contract decisions.',lane:'SaaS renewal notice register',owner:'IT or finance owner',inputs:'vendor, product, contract source, renewal date, notice window, account owner, cost center, and approval status',stop:'canceling a service, interpreting terms, negotiating price, or approving spend',exception:'a renewal notice names a discontinued plan while active accounts remain assigned'},
{slug:'filipino-return-merchandise-evidence-assistant',title:'How to plan Filipino return merchandise evidence support',excerpt:'Prepare condition and shipment records while owners decide eligibility, remedy, and disposition.',lane:'return merchandise evidence',owner:'returns operations owner',inputs:'request, order, policy version, authorization, carrier event, received condition, supplied images, and prior remedy',stop:'approving a return, judging safety, issuing a refund, or choosing disposition',exception:'the carrier shows delivery but the warehouse lists another product identifier'},
{slug:'filipino-project-change-request-register-coordinator',title:'How to scope Filipino project change request register support',excerpt:'Record proposed scope changes while sponsors retain commitment, budget, and priority decisions.',lane:'project change request register',owner:'project sponsor',inputs:'request wording, requester, deliverable, reason, dependency, estimate source, status, and effective date',stop:'committing scope, approving budget, reprioritizing, or promising a deadline',exception:'a client asks for a deliverable while the estimate covers only a revision'},
{slug:'filipino-third-party-due-diligence-response-register-assistant',title:'How to plan Filipino third-party due diligence response register support',excerpt:'Track approved response sources without making assurances or inventing governance claims.',lane:'third-party due diligence response register',owner:'risk or compliance owner',inputs:'request version, question, approved response source, evidence owner, review date, sharing restriction, exception, and status',stop:'certifying compliance, interpreting a control, exposing restricted evidence, or submitting an answer',exception:'an approved response cites a process that changed after its last review date'},
{slug:'filipino-advertising-claim-source-assistant',title:'How to scope Filipino advertising claim source support',excerpt:'Link proposed claims to approved substantiation while owners retain wording and publication decisions.',lane:'advertising claim source preparation',owner:'legal or marketing owner',inputs:'claim, channel, audience, product version, source, approval, expiration, and qualification',stop:'creating substantiation, rewriting a claim, approving publication, or removing qualifications',exception:'a campaign repeats a figure from an expired product test'},
{slug:'filipino-facility-visitor-records-coordinator',title:'How to plan Filipino facility visitor records support',excerpt:'Maintain visit records while site owners decide admission, escort, and incident response.',lane:'facility visitor records',owner:'site security owner',inputs:'visitor request, host, purpose, site, arrival window, area, approval, credential, and departure',stop:'approving entry, waiving identification, granting access, or deciding incident response',exception:'an approved visitor requests access to an area absent from the approval'},
{slug:'filipino-training-completion-evidence-assistant',title:'How to scope Filipino training completion evidence support',excerpt:'Compile completion records while managers retain competency, exception, and employment decisions.',lane:'training completion evidence',owner:'learning or people owner',inputs:'requirement, learner, version, due date, completion, result, exception, and review',stop:'certifying competency, changing a result, granting an exception, or making employment decisions',exception:'completion is recorded against a retired course version'},
{slug:'filipino-data-retention-disposition-register-assistant',title:'How to plan Filipino data retention disposition register support',excerpt:'Prepare disposition evidence while records and legal owners retain retention and deletion authority.',lane:'data retention disposition register',owner:'records or privacy owner',inputs:'record category, system, owner, schedule, trigger, hold status, proposed action, and evidence',stop:'interpreting law, releasing a hold, deleting data, or certifying destruction',exception:'the schedule indicates disposition while an unresolved hold has no owner'},
];
function buildDetail(t:Topic){const sections=[
{title:'Define the source packet',paragraphs:[`A ${t.lane} queue begins with ${t.inputs}. Record the location, version, and checking time for each consequential field.`,`Completeness means ready for review, not approved. Keep the ${t.owner} beside every decision state.`]},
{title:'Write the authority boundary',paragraphs:[`A Filipino specialist may collect, label, compare, and route approved records. The role stops before ${t.stop}.`,`Use an explicit owner-review state. Deadlines, silence, and previous examples do not expand authority.`]},
{title:'Rehearse a real exception',paragraphs:[`Test this case before launch: ${t.exception}. Preserve both records, state the difference without inference, pause action, and route one focused question.`,`Also review an ordinary and an incomplete example. Put corrections into the controlled instruction, not only private chat.`]},
{title:'Control access and handoffs',paragraphs:[`Grant named, minimum access for ${t.lane}, with purpose, approver, review date, and removal path.`,`A handoff identifies the last source checked, open difference, current state, next owner, and approved substitute.`]},
{title:'Sample evidence against the source',paragraphs:[`Compare prepared packets with original evidence. Classify returns as missing input, transcription error, stale source, conflict, unclear instruction, or out-of-scope judgment.`,`Count arrivals, gaps, conflicts, returns, owner waits, and unresolved age. These are queue signals, not outcome guarantees.`]},
{title:'Expand only after repeatable review',paragraphs:[`A second reviewer should explain the intake, finish point, source hierarchy, stop case, access boundary, and ${t.owner} path.`,`Treat a new system, data class, audience, or decision as a scope change and review it before adding volume.`]}];
const sourceArticleText=`${t.title}. ${t.excerpt} `+sections.flatMap(s=>s.paragraphs).join(' ');return{datePublished:date,dateModified:date,image:{src:'/article-planning.svg',alt:`Planning board for ${t.lane}`,caption:`A bounded ${t.lane} queue keeps evidence and authority visible.`},shortAnswer:`Build ${t.lane} around a defined source packet, tested exception, minimum access, and named ${t.owner}.`,takeaways:['Define evidence and the finish point.','Keep missing and conflicting inputs visible.',`Route decisions to the ${t.owner}.`,'Expand after source-based review is repeatable.'],sections,sourceArticleText,sources:[{name:'National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Philippine privacy principles for controlled data handling.'}],faqs:[{question:'What can the role complete?',answer:'The role can prepare and route the documented evidence packet.'},{question:'Who resolves exceptions?',answer:`The ${t.owner} resolves exceptions and authorizes action.`},{question:'What should launch review cover?',answer:'An ordinary record, an incomplete record, and the stop case.'}],tags:[t.lane,'Philippines staffing','Workflow controls'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Onboarding checklist'}]}}
export const september2BlogPosts=topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:10}));
export const september2BlogDetails=Object.fromEntries(topics.map(t=>[t.slug,buildDetail(t)]));
