const published = '2026-09-09' as const;

type Brief = { slug:string; title:string; excerpt:string; work:string; owner:string; record:string; stop:string; example:string };

const briefs: readonly Brief[] = [
  {slug:'filipino-subscription-dunning-case-coordinator',title:'What a Filipino Subscription Dunning Coordinator Can Safely Own',excerpt:'Keep failed-payment follow-up orderly without handing over credit, cancellation, or account-change authority.',work:'subscription dunning case coordination',owner:'billing owner',record:'account, failed charge, approved message, attempt history, customer reply, next review date, and decision state',stop:'a customer disputes the charge, requests hardship terms, or asks to cancel',example:'A long-standing customer says the card is valid and claims the latest invoice contains an unapproved add-on.'},
  {slug:'filipino-freight-document-exception-assistant',title:'A Practical Brief for a Filipino Freight Document Exception Assistant',excerpt:'Prepare mismatched freight records for review while logistics owners decide release, correction, and carrier action.',work:'freight document exception preparation',owner:'logistics owner',record:'shipment, booking, bill of lading, commercial document, discrepancy, source, cutoff, and waiting owner',stop:'cargo details conflict, a cutoff may be missed, or a document needs formal amendment',example:'The packing list shows twelve cartons while the carrier record shows eleven and the warehouse has not confirmed the handoff.'},
  {slug:'filipino-grant-reporting-evidence-assistant',title:'How to Scope Filipino Grant Reporting Evidence Support',excerpt:'Organize grant evidence and due-date inputs without letting an assistant certify eligibility or spending compliance.',work:'grant reporting evidence support',owner:'program or finance owner',record:'award, reporting period, approved budget line, transaction reference, activity evidence, variance, and reviewer',stop:'eligibility is unclear, spending differs from the award, or a narrative claim lacks evidence',example:'A project invoice falls inside the reporting period but names a workstream that is absent from the approved budget.'},
  {slug:'filipino-field-service-warranty-claim-assistant',title:'Building a Filipino Field Service Warranty Claim Queue',excerpt:'Assemble service and warranty facts while technical and commercial owners retain coverage decisions.',work:'field service warranty claim preparation',owner:'service or warranty owner',record:'asset, serial number, coverage record, reported fault, visit notes, parts, photos, and review status',stop:'coverage is disputed, safety is involved, or the evidence points to installation damage',example:'The unit failed within the stated term, but the installation photo shows a component not listed on the original job sheet.'},
  {slug:'filipino-learning-management-enrollment-coordinator',title:'Boundaries for a Filipino Learning Management Enrollment Coordinator',excerpt:'Maintain enrollment records and access requests without deciding prerequisites, accommodations, or completion.',work:'learning management enrollment coordination',owner:'learning or HR owner',record:'learner, approved course, prerequisite state, manager request, access role, enrollment date, and exception',stop:'a prerequisite is missing, personal data conflicts, or special access is requested',example:'A manager requests urgent enrollment, but the employee record belongs to a different legal entity with another training policy.'},
  {slug:'filipino-insurance-certificate-tracking-assistant',title:'A Safe Routine for Filipino Insurance Certificate Tracking',excerpt:'Track certificate evidence and expiry signals while qualified owners interpret coverage and contractual sufficiency.',work:'insurance certificate tracking',owner:'risk, legal, or procurement owner',record:'supplier, certificate source, policy type, stated limits, effective dates, named entities, exception, and reviewer',stop:'coverage wording differs from the requirement, dates lapse, or an entity name does not match',example:'A current certificate lists the parent company, while the signed supplier agreement names a local subsidiary.'},
  {slug:'filipino-restaurant-menu-data-coordinator',title:'Planning Filipino Restaurant Menu Data Coordination',excerpt:'Keep menu records consistent across approved channels without allowing silent price, allergen, or availability decisions.',work:'restaurant menu data coordination',owner:'restaurant operations owner',record:'item, channel, approved description, price source, allergen statement, availability window, version, and approver',stop:'prices conflict, an allergen statement changes, or a channel requires an unsupported option',example:'The delivery marketplace lists a lower price and a gluten-free label that do not appear in the approved restaurant file.'},
  {slug:'filipino-construction-submittal-log-assistant',title:'How a Filipino Construction Submittal Log Assistant Fits the Review Chain',excerpt:'Maintain traceable submittal status while architects, engineers, and project owners retain technical approval.',work:'construction submittal log support',owner:'project design or construction owner',record:'package, specification reference, revision, sender, recipient, review due date, response, and superseded state',stop:'documents conflict, a reviewer changes disposition, or field work may rely on an unapproved revision',example:'A revised shop drawing arrives after the architect commented, but the transmittal does not say which comments were resolved.'},
  {slug:'filipino-charity-donor-restriction-record-assistant',title:'Scoping a Filipino Donor Restriction Record Assistant',excerpt:'Link gifts to documented restrictions while charity leaders retain accounting, legal, and stewardship judgments.',work:'donor restriction record preparation',owner:'fundraising or finance owner',record:'gift, donor communication, campaign, restriction wording, receipt, allocation state, source link, and reviewer',stop:'instructions conflict, a purpose is unavailable, or a record would change accounting treatment',example:'The online form names a general campaign while the donor email asks that the gift fund one specific activity.'},
  {slug:'filipino-laboratory-sample-accessioning-assistant',title:'A Controlled Filipino Laboratory Sample Accessioning Workflow',excerpt:'Prepare identifiers and routing records while laboratory professionals retain acceptance and testing decisions.',work:'laboratory sample accessioning support',owner:'authorized laboratory owner',record:'sample identifier, request, collection time, condition note, custody event, destination, consent state, and exception',stop:'identity, condition, consent, or requested testing is unclear',example:'The container label matches the request number, but the collection time is missing and the courier recorded a temperature excursion.'},
  {slug:'filipino-franchise-compliance-calendar-assistant',title:'Creating a Filipino Franchise Compliance Calendar Without Hidden Judgment',excerpt:'Track dated obligations and evidence while legal and operating owners interpret requirements and approve responses.',work:'franchise compliance calendar support',owner:'legal or franchise operations owner',record:'location, obligation, source document, stated date, responsible owner, evidence, reminder state, and exception',stop:'two documents state different dates, a deadline requires interpretation, or filing authority is requested',example:'The operations manual sets a monthly submission date while a later brand notice appears to move it for only some locations.'},
  {slug:'filipino-podcast-sponsorship-fulfillment-coordinator',title:'A Clear Brief for Filipino Podcast Sponsorship Fulfillment Support',excerpt:'Track approved placements and delivery evidence without transferring claims, pricing, or make-good authority.',work:'podcast sponsorship fulfillment coordination',owner:'commercial or production owner',record:'campaign, approved copy, episode, placement, publication evidence, tracking link, variance, and client response',stop:'copy changes, a claim lacks approval, delivery differs from the order, or a make-good is requested',example:'The host reads the approved message, but the episode publishes after the campaign window and the buyer asks for replacement inventory.'},
];

function detail(b: Brief) {
  const sections = [
    {title:'Start with the work record',paragraphs:[`Define ${b.work} as a bounded queue. The working record should contain ${b.record}. Missing information stays visibly missing; it is not guessed from a nearby case.`,`Give each item a source link, current state, last action, and next owner. That lets another shift reconstruct the handoff without relying on private messages.`]},
    {title:'Write the stop rule before launch',paragraphs:[`Pause and route the item when ${b.stop}. The ${b.owner} decides what happens next.`,`A coordinator can gather, compare, label, and route approved facts. The role does not approve exceptions, interpret professional requirements, change money or access, or make external commitments.`]},
    {title:'Rehearse a difficult item',paragraphs:[`${b.example} Preserve both records, describe the difference in neutral language, and ask the owner one focused question.`,`Test this case beside an ordinary record and an incomplete record. If reviewers choose different states, revise the written example before increasing volume.`]},
    {title:'Keep access proportional',paragraphs:[`Use named accounts, minimum permissions, multifactor authentication where available, and an agreed access-removal trigger. Store evidence in the approved system rather than personal files or chat.`,`Training examples should remove unnecessary personal, financial, health, or commercial information. Record who may view, edit, export, and approve each data class.`]},
    {title:'Make corrections visible',paragraphs:[`Retain the prior value, corrected value, source, reason, actor, and time. Silent replacement hides the path a reviewer needs to understand the case.`,`A clean handoff states what changed, what remains uncertain, which action is paused, and who owns the decision.`]},
    {title:'Measure the queue honestly',paragraphs:[`Track eligible volume, complete packets, exception categories, correction events, and time waiting for the ${b.owner}. Report the observation window, exclusions, and instruction version.`,`Do not turn queue counts into claims about worker quality or business outcomes. Missing inputs, unclear rules, system failures, and owner wait time need separate labels because they call for different fixes.`]},
  ];
  return {datePublished:published,dateModified:published,image:{src:'/article-planning.svg',alt:`Planning board for ${b.work}`,caption:`A visible work record keeps sources, stop rules, and decision ownership clear.`},shortAnswer:`A Filipino coordinator can support ${b.work} when the record, stop rules, access limits, and ${b.owner} are explicit.`,takeaways:['Name the source and required field for every item.','Keep missing and conflicting evidence visible.',`Route consequential decisions to the ${b.owner}.`,'Review corrections and exceptions before scaling.'],sections,sourceArticleText:`${b.title}. ${b.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,sources:[{name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official principles for proportionate, accurate, and secure personal-data handling.'},{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Practical named-account protection guidance.'}],faqs:[{question:'What can the coordinator complete?',answer:`The coordinator can prepare and route the defined ${b.work} record.`},{question:'Who decides an exception?',answer:`The ${b.owner} retains consequential decision and approval authority.`},{question:'How should the first week be reviewed?',answer:'Compare ordinary, incomplete, and conflicting items with their original sources each day.'}],tags:[b.work,'Filipino outsourcing','Workflow controls'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Build a staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Use the onboarding checklist'}]};
}

export const september9BlogPosts = briefs.map(({slug,title,excerpt}) => ({slug,title,excerpt,minutes:10,image:'/article-planning.svg'}));
export const september9BlogDetails = Object.fromEntries(briefs.map(brief => [brief.slug, detail(brief)]));
