const published = '2026-09-18' as const;

export type Brief = {
  slug: string; title: string; excerpt: string; service: string; queue: string;
  owner: string; inputs: string; stop: string; example: string; output: string;
};

export function buildSeptember18Detail(b: Brief) {
  const sections = [
    {title:'Define the work before access begins',paragraphs:[`Treat ${b.queue} as a bounded queue, not a broad assistant title. The written entry rule should name ${b.inputs}. The ${b.owner} should identify which system is authoritative for each field and what evidence is acceptable when a source is missing.`, `Define administrative completion as ${b.output}. Completion does not mean the underlying business decision is approved. It means the evidence is organized, the open question is visible, and an accountable owner can review the case without reconstructing it from private messages.`, `Use one queue identifier from intake through closure. If an item arrives through email, chat, a form, and a business system, link those events rather than creating four unrelated tasks. This protects the chronology and reduces duplicate effort.`]},
    {title:'Separate preparation from authority',paragraphs:[`The assistant may retrieve approved records, transcribe exact fields, apply client-defined labels, compare sources, request specified missing items, and route a packet. The ${b.owner} retains judgment, approval, external commitment, and any action that changes money, access, rights, safety, or the authoritative record.`, `A useful stop rule is concrete: stop when ${b.stop}. The escalation should quote or link the conflicting evidence, describe the action that cannot continue, and ask one decision question. “Please advise” without context only moves the research burden back to the owner.`, `Urgency never expands permission. If a deadline approaches, record the deadline source and notify the named owner through the approved channel. Do not resolve uncertainty by copying an earlier decision from a superficially similar case.`]},
    {title:'Build the minimum complete record',paragraphs:[`Create a required-field checklist from ${b.inputs}. Mark each field present, absent, conflicting, or not applicable. “Not applicable” should require a reason so it cannot become a convenient substitute for missing evidence.`, `Preserve the submitted record in its received form. Corrections belong in a new event with old value, proposed value, source, actor, time, and approval state. Silent cleanup makes a packet look complete while removing the history a reviewer needs.`, `Where personal or commercially sensitive data is involved, collect only what this queue needs. A complete packet is not the largest packet. It is the smallest set that answers the approved operational question and supports the reviewer’s decision.`]},
    {title:'Test a realistic boundary case',paragraphs:[`${b.example} A training exercise should require the assistant to keep every source, explain the discrepancy in neutral language, identify the stop condition, and route the case without deciding which party is correct.`, `Add two controls to that exercise: a normal case that can be completed and an incomplete case that must wait. Ask two reviewers to apply the written rule independently. If they select different paths, revise the instruction or example before increasing volume.`, `Do not score the worker on whether the owner likes the eventual outcome. Score the preparation against observable requirements: source traceability, field accuracy, preserved chronology, correct stop rule, protected access, and timely routing.`]},
    {title:'Limit systems, permissions, and exports',paragraphs:[`Provide a named account for only the systems and actions required by ${b.queue}. Use multifactor authentication where supported, prohibit shared credentials, and document the access owner, approval, review date, and removal trigger.`, `Prefer read access or a preparation workspace when the assistant does not need to change the authoritative record. Separate drafting from sending, comparison from merging, and packet preparation from approval. These technical boundaries reinforce the written operating boundary.`, `Exports require their own control. Name the approved storage location, file naming rule, retention owner, and deletion process. Do not move live records into personal drives or chat attachments simply because that makes review faster.`]},
    {title:'Run a controlled first week',paragraphs:[`Start with consecutive eligible items rather than a selection of easy examples. Review every early packet, then reduce review only after repeated accuracy under the same instruction version. Keep unusual items in the sample because they test whether the escalation path actually works.`, `A daily handoff should show items received, packets completed, missing evidence, source conflicts, approaching deadlines, and decisions waiting on the ${b.owner}. Counts need the same entry and completion definitions each day or apparent progress will be misleading.`, `Write corrections into the operating guide. Record the original instruction, the observed problem, the corrected rule, its effective time, and the owner who approved it. Do not retroactively judge earlier work against a rule that did not yet exist.`]},
    {title:'Measure the queue without inventing performance claims',paragraphs:[`Useful operating measures include eligible items, complete packets, missing-source cases, conflict cases, returned packets, owner-wait time, and age of the oldest open item. Report raw counts beside percentages so a small or changing denominator stays visible.`, `These measures describe the queue under a specific process and period. They do not by themselves prove savings, service quality, compliance, worker capability, or customer outcomes. Note outages, policy changes, staffing gaps, and exclusions beside the figures.`, `If a target is introduced, the business owner should approve its definition and consequence. The assistant may calculate from controlled records, but should not choose the denominator, suppress inconvenient exceptions, or reinterpret a missed target.`]},
    {title:'Review privacy, security, and evidence quality',paragraphs:[`The Philippines National Privacy Commission emphasizes transparency, legitimate purpose, and proportionality in personal-data processing. Apply those principles by stating why a field is needed, limiting access, and avoiding copies that are unrelated to ${b.queue}.`, `NIST guidance on digital identity and security controls supports named identities, authentication, least privilege, and auditable account lifecycle practices. CISA also recommends phishing-resistant multifactor authentication where available. The client remains responsible for selecting controls appropriate to its systems and risk.`, `Citations provide control principles, not a claim that the workflow is certified or legally sufficient. Sensitive healthcare, legal, financial, employment, safety, and identity matters may need qualified review and stricter client rules.`]},
    {title:'Decide whether the role is ready to expand',paragraphs:[`Expansion is reasonable only when the queue definition is stable, source locations are known, corrections are traceable, owner questions are answered promptly, and the worker consistently stops at the stated boundary. More volume is not a reason to remove approvals.`, `Before adding another workflow, compare its data, systems, consequences, reviewer, and authority. A task that sounds adjacent may need different access or professional oversight. Write a separate lane when the inputs or decision owner change materially.`, `A strong handoff leaves the business with a reusable operating record: scope, examples, permissions, stop rules, review notes, measures, and removal steps. That record supports continuity without pretending that documentation can replace accountable management.`]},
  ];
  return {
    datePublished:published,dateModified:published,
    image:{src:'/article-planning.svg',alt:`Planning board for ${b.queue}`,caption:'A practical role brief connects source evidence, boundaries, access, and a named reviewer.'},
    shortAnswer:`A Filipino assistant can support ${b.queue} when the source fields, completion event, stop rules, access limits, and ${b.owner} are written before live work begins.`,
    takeaways:[`Define ${b.output}.`,'Preserve missing and conflicting evidence.','Keep consequential decisions with the named client owner.','Review consecutive early work under one instruction version.'],
    sections,
    sourceArticleText:`${b.title} ${b.excerpt} ${sections.flatMap(s=>s.paragraphs).join(' ')}`,
    sources:[
      {name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine guidance for transparency, legitimate purpose, proportionality, accuracy, and security.'},
      {name:'NIST SP 800-63-4: Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/',note:'Primary guidance for identity, authentication, and account lifecycle controls.'},
      {name:'CISA: More than a Password',url:'https://www.cisa.gov/mfa',note:'Current first-party guidance on multifactor authentication.'},
    ],
    faqs:[{question:'What may the assistant complete?',answer:`The assistant may prepare and route the defined ${b.queue} output using approved sources and rules.`},{question:'Who decides exceptions?',answer:`The ${b.owner} decides exceptions, approvals, and consequential actions.`},{question:'How should early work be checked?',answer:'Review consecutive items for source traceability, field accuracy, stop-rule use, access handling, and clear owner questions.'}],
    tags:[b.service,'Filipino outsourcing','Role planning'],
    related:[{href:`/services/${b.service.replaceAll(' ','-')}`,label:`Explore ${b.service}`},{href:'/contact-us',label:'Discuss a bounded staffing role'}],
  };
}
