type Section = { title: string; paragraphs: string[] };
type Topic = { slug: string; title: string; excerpt: string; lane: string; focus: string; sections: Section[] };

const date = '2026-08-21' as const;
const imageFor = (slug: string, lane: string) => ({ src: `/images/blog-2026-08-21-${slug}.png`, alt: `Filipino ${lane} planning desk`, caption: `A practical ${lane} workflow keeps evidence and ownership visible.` });

const topics: Topic[] = [
  { slug: 'filipino-customer-onboarding-implementation-coordinator', title: 'How to scope Filipino customer onboarding implementation coordination', excerpt: 'Prepare setup requirements, owner questions, and handoff status without making technical or commercial promises.', lane: 'customer onboarding implementation coordination', focus: 'turn approved onboarding inputs into a visible implementation queue while leaving configuration and commitment decisions with the customer owner', sections: [
    { title: 'Start with an implementation map', paragraphs: ['List the customer objective, agreed deliverables, source documents, dependencies, owner, and next checkpoint. A coordinator can assemble the map and identify a missing input; they should not infer that a vague request is an approved requirement.', 'Use separate fields for customer-stated needs, internal assumptions, and decisions already approved. This prevents a planning note from becoming a promise that the delivery team has not accepted.'] },
    { title: 'Make the handoff testable', paragraphs: ['For each setup item, define the evidence that shows it is ready for review: a completed form, a confirmed account, an approved file, or a named technical answer. “Discussed” is not the same as “ready.”', 'A useful sample includes an ordinary setup task, a dependency waiting on the customer, and a request that changes scope. The third item should pause with a precise question rather than being quietly added to the queue.'] },
    { title: 'Keep configuration authority clear', paragraphs: ['The role may schedule meetings, reconcile task status, prepare questions, and update an approved tracker. It should not change production settings, promise an integration date, or decide that a customer’s data is safe to import.', 'Write the owner beside every decision-heavy field. If the source material conflicts, preserve both versions and state which person must resolve the conflict.'] },
    { title: 'Coordinate across time zones', paragraphs: ['Show the customer time zone, the Philippines schedule, and the agreed overlap in the record. A reminder should identify the action and owner; it should not imply that a missed meeting authorizes a new timeline.', 'When an owner is unavailable, retain the dependency and route it through the approved substitute path. Do not reconstruct a commitment from informal chat or memory.'] },
    { title: 'Review implementation evidence', paragraphs: ['A manager can sample a completed item, an incomplete item, and a scope-change item. Check the source link, status reason, timestamp, and next owner action. Classify corrections as missing evidence, stale status, transcription error, or unresolved decision.', 'Accepted corrections should update the instruction with an effective date. If earlier handoffs may be affected, identify them instead of silently rewriting their history.'] },
    { title: 'Measure readiness honestly', paragraphs: ['Track tasks received, blocked dependencies, owner questions, returned packets, and aging items. These measurements describe queue health; they do not promise activation speed, implementation success, or customer results.', 'Expand only when another reviewer can explain what enters, what proves completion, which systems are allowed, and where the coordinator must stop.'] },
  ] },
  { slug: 'filipino-revenue-operations-forecast-support-coordinator', title: 'How to plan Filipino revenue operations forecast support', excerpt: 'Prepare source-linked pipeline and forecast inputs while keeping forecasting judgment and commercial commitments with sales leadership.', lane: 'revenue operations forecast support', focus: 'make forecast inputs traceable and exceptions visible without turning record preparation into an unapproved sales prediction', sections: [
    { title: 'Define the forecast input set', paragraphs: ['Name the systems, fields, reporting period, source hierarchy, and cutoff time. The coordinator can assemble approved fields and flag blanks, but should not fill a missing close date or stage from intuition.', 'Keep opportunity facts separate from a manager’s forecast category. A dated activity record is evidence; confidence in a future outcome is a sales decision.'] },
    { title: 'Reconcile before summarizing', paragraphs: ['Compare the pipeline export with the approved CRM view and record the time of each check. Duplicates, stale owners, and inconsistent amounts should appear as exceptions with links to the source rows.', 'Do not select the value that makes the report look cleaner. When two sources disagree, show the difference and ask which system or owner controls.'] },
    { title: 'Protect commercial boundaries', paragraphs: ['A support role may prepare a review packet, request a missing field, and organize a meeting agenda. It must not change pricing, discount terms, probability, customer commitments, or opportunity stage without delegated authority.', 'Stop when a request asks for an unsupported projection or a customer-facing statement. Route the evidence and the exact decision needed to sales leadership.'] },
    { title: 'Build a useful exception log', paragraphs: ['Use reason codes such as missing next step, stale activity, conflicting amount, duplicate record, or owner confirmation needed. The code should tell the reviewer what action is possible next.', 'Aging should show whether the bottleneck is data collection or a business decision. A single “forecast issue” label hides that distinction and invites unnecessary editing.'] },
    { title: 'Sample the reporting cycle', paragraphs: ['Review one ordinary opportunity, one incomplete record, and one conflicting-source case. Check the source path, filter, period, calculation, and handoff note. Preserve the original export so later reviewers can reproduce the result.', 'Record corrections by cause. A recurring missing field may call for a better sales process, while a conflicting amount needs an owner decision.'] },
    { title: 'Keep the scorecard bounded', paragraphs: ['Measure records checked, exceptions by reason, unresolved owner questions, duplicate candidates, and reviewer corrections. These are control signals, not claims about revenue, win rate, or forecast accuracy.', 'Scope can expand when the sales owner can explain the source hierarchy, review cadence, access list, and commercial decisions outside the role.'] },
  ] },
  { slug: 'filipino-hr-policy-documentation-coordinator', title: 'How to scope Filipino HR policy documentation coordination', excerpt: 'Organize policy versions, acknowledgment status, and employee questions without interpreting policy or making employment decisions.', lane: 'HR policy documentation coordination', focus: 'keep approved people-operations guidance and acknowledgment records organized while routing interpretation to the authorized HR owner', sections: [
    { title: 'Create a policy register', paragraphs: ['Record policy name, owner, version, effective date, audience, approval status, and source location. The coordinator can maintain the register and identify a missing field; they should not declare that an unsigned draft is active.', 'Treat an old version as evidence requiring review, not as proof that the policy is wrong. Preserve the prior file and the decision that supersedes it.'] },
    { title: 'Separate publication from interpretation', paragraphs: ['Formatting, distribution lists, acknowledgment tracking, and question routing are bounded tasks. Explaining whether a rule applies to a person or situation belongs to HR or another authorized owner.', 'If an employee asks for an exception, record the question without promising an answer. Include the relevant policy version and route it through the approved confidential path.'] },
    { title: 'Handle sensitive records narrowly', paragraphs: ['Use the minimum employee information needed to track delivery or acknowledgment. Keep medical, disciplinary, compensation, and identity information in the approved system and do not create convenience copies.', 'Access should name the purpose, approving owner, review date, and removal step. A coordinator does not need broad HR administration rights to maintain a policy index.'] },
    { title: 'Make questions answerable', paragraphs: ['A good escalation names the policy section, employee-facing question, source version, and requested HR decision. Avoid replacing an uncertain answer with a paraphrase that sounds definitive.', 'Track whether the question is awaiting HR, legal, manager, or employee input. Different waiting states protect confidentiality and make continuity possible.'] },
    { title: 'Audit acknowledgments', paragraphs: ['Sample a completed acknowledgment, a missing acknowledgment, and a record attached to the wrong version. Check recipient, delivery date, source version, and owner. Keep corrections traceable.', 'A status report should distinguish sent, opened, acknowledged, returned, and exception. It should not infer agreement or compliance from an unverified click.'] },
    { title: 'Expand by policy family', paragraphs: ['Measure documents inventoried, version conflicts, unanswered questions, acknowledgments by state, access exceptions, and reviewer corrections. These are workflow measures, not legal conclusions or employment outcomes.', 'Add another policy family only after HR confirms its owner, audience, confidentiality rule, and interpretation boundary.'] },
  ] },
  { slug: 'filipino-ecommerce-refund-case-preparation-coordinator', title: 'How to plan Filipino ecommerce refund case preparation', excerpt: 'Assemble order evidence and customer history for refund review without authorizing remedies or changing commercial policy.', lane: 'ecommerce refund case preparation', focus: 'give an ecommerce owner a complete, source-linked refund packet while keeping approval, fraud, and policy decisions outside the preparation role', sections: [
    { title: 'Assemble the case spine', paragraphs: ['Use order identifier, payment state, fulfillment events, customer message, return evidence, prior contacts, and applicable policy version. Each field needs a source and check time.', 'Do not replace the customer’s words with a conclusion. “Package arrived damaged” is a reported claim; verification and remedy remain with the authorized reviewer.'] },
    { title: 'Classify without deciding', paragraphs: ['Reason codes can describe missing item, late arrival, duplicate charge, damaged goods, or policy question. They help routing, but they must not silently determine eligibility.', 'If evidence fits more than one category, retain the competing possibilities and state the question. A clean-looking label is less useful than an honest exception.'] },
    { title: 'Preserve payment boundaries', paragraphs: ['The coordinator may gather records, request a photo, and prepare a neutral timeline. They should not issue a refund, change a payment record, promise a credit, or disclose internal fraud rules.', 'Use an approved response for receipt and next steps. Route unusual requests, charge disputes, and account-access concerns with the evidence attached.'] },
    { title: 'Close duplicate work', paragraphs: ['Before opening a case, check the order and customer identifiers against active queues. If two cases refer to one event, link them and keep the original notes.', 'A reviewer should be able to see why a case is open, what evidence is missing, and who decides next. “Pending” without a reason creates repeat contacts.'] },
    { title: 'Review the customer record', paragraphs: ['Sample a routine request, a missing-evidence request, and a case where order and customer records conflict. Compare sources, timestamps, policy version, and escalation destination.', 'Corrections should identify whether the issue was a missing field, duplicate, wrong source, or remedy decision. Never erase the evidence to make the case easier to close.'] },
    { title: 'Measure preparation quality', paragraphs: ['Track cases received, evidence gaps, duplicate links, owner waits, policy questions, and reviewer corrections. These signals describe preparation work, not refund speed, fraud detection, or customer satisfaction.', 'Expand after the owner confirms the policy source, access limits, approved messages, and stop rules for the next case category.'] },
  ] },
  { slug: 'filipino-website-analytics-reporting-coordinator', title: 'How to scope Filipino website analytics reporting coordination', excerpt: 'Prepare repeatable traffic and content reports with definitions and source notes while leaving interpretation and strategy with the site owner.', lane: 'website analytics reporting coordination', focus: 'turn approved analytics views into a reproducible reporting packet without presenting a metric as a business conclusion', sections: [
    { title: 'Agree on the question first', paragraphs: ['Write the reporting question, property, date range, filters, audience, and intended reader before exporting anything. A metric without a definition can answer the wrong question convincingly.', 'The coordinator can reproduce an approved view and document its settings. They should not choose a flattering metric or infer a reason for movement without an owner-approved analysis plan.'] },
    { title: 'Preserve measurement context', paragraphs: ['Record collection source, timezone, attribution setting, exclusions, and extraction time. Keep the raw export or approved link beside the formatted summary.', 'If a dashboard and export disagree, show both values and route the discrepancy. Do not overwrite one with the other because the difference is inconvenient.'] },
    { title: 'Separate numbers from narratives', paragraphs: ['A report can state that a page had a certain count under a defined view. Explaining why visitors behaved that way, or deciding what to change, belongs to the marketing or site owner.', 'Use labels such as observed, definition-dependent, and owner interpretation. This keeps a coordination deliverable from becoming unsupported advice.'] },
    { title: 'Make content questions traceable', paragraphs: ['Link page paths, report rows, and the relevant content record. A route change or duplicate page should be visible as a data question rather than silently merged.', 'When a requested report includes personal or sensitive data, pause and confirm the approved fields and audience before exporting.'] },
    { title: 'Reproduce a reporting run', paragraphs: ['Sample a normal report, a filtered report, and a source mismatch. A second reviewer should be able to follow the settings, source, and calculation without private explanation.', 'Keep corrections dated and identify whether they concern a filter, definition, transcription, or interpretation. Only the owner approves changes to the reporting question.'] },
    { title: 'Use process metrics carefully', paragraphs: ['Track reports delivered, missing definitions, source mismatches, returned summaries, and review corrections. Do not convert these into claims about traffic growth, ranking, or conversion performance.', 'Expand when the owner can explain the data source, privacy boundary, report consumer, and decision that remains outside the coordinator’s role.'] },
  ] },
  { slug: 'filipino-vendor-compliance-records-coordinator', title: 'How to plan Filipino vendor compliance records coordination', excerpt: 'Track supplier documents, review dates, and missing evidence without making compliance determinations or approving vendors.', lane: 'vendor compliance records coordination', focus: 'maintain a controlled supplier evidence queue while leaving acceptance, legal interpretation, and risk decisions with procurement or compliance owners', sections: [
    { title: 'Define the evidence register', paragraphs: ['List supplier identifier, document type, issuing source, received date, expiration or review date, owner, and status. The coordinator can check presence and legibility against an approved checklist.', 'Do not call a vendor compliant because a file exists. Completeness and validity are separate questions for the responsible owner.'] },
    { title: 'Keep documents authentic', paragraphs: ['Preserve the submitted file, source reference, and version. If a document appears altered, expired, or inconsistent, record the observable issue and route it rather than editing or replacing it.', 'A clear reason code should distinguish missing, unreadable, expired, conflicting, and owner-review items.'] },
    { title: 'Route sensitive questions', paragraphs: ['Tax, banking, insurance, identity, and legal records require narrow access. Use the approved system and minimum necessary fields; do not move supplier documents into personal folders.', 'The escalation should identify the record, evidence, uncertainty, and owner decision. Avoid language that promises approval or continuation.'] },
    { title: 'Manage renewal dates', paragraphs: ['A reminder should show the source date, responsible owner, and next action. It should not state that a supplier remains approved after an expiration if the owner has not decided.', 'When dates conflict across documents, preserve both values and ask which source governs. Never pick the later date merely to avoid a follow-up.'] },
    { title: 'Review the queue by cause', paragraphs: ['Sample a complete record, an expired record, and a conflicting record. Check identifiers, source links, access, and routing. Record whether corrections arose from intake, transcription, version, or owner judgment.', 'A dated review log helps procurement see recurring supplier or form problems without turning them into unsupported performance claims.'] },
    { title: 'Expand only with approval', paragraphs: ['Measure records received, missing evidence, upcoming reviews, owner decisions, access exceptions, and reviewer corrections. These are queue signals, not compliance results.', 'Add a new document family only after the owner confirms its checklist, confidentiality level, reviewer, and decision boundary.'] },
  ] },
  { slug: 'filipino-product-support-release-notes-coordinator', title: 'How to scope Filipino product support release-notes coordination', excerpt: 'Organize approved change details and support guidance while leaving release claims, dates, and customer commitments with product owners.', lane: 'product support release-notes coordination', focus: 'turn approved product changes into a traceable support packet without publishing an unverified capability, date, or promise', sections: [
    { title: 'Start from the approved change', paragraphs: ['Record change identifier, product area, approved description, audience, release state, owner, and source. The coordinator can compare the draft with the ticket or specification.', 'A request to “make it clearer” does not authorize adding behavior, availability, or customer impact that the source does not support.'] },
    { title: 'Write for support use', paragraphs: ['Organize what changed, who may encounter it, what support should check, and where questions go. Keep internal implementation detail out of public copy unless the product owner approves it.', 'Use separate blocks for confirmed behavior, known limitation, and unresolved question. This helps support teams avoid treating a draft as a guarantee.'] },
    { title: 'Control dates and channels', paragraphs: ['A coordinator may maintain the release calendar and route an approved note. They should not move a publication date, announce a release, or promise availability without authorization.', 'Channel-specific versions need their own reviewer and source identity. Do not assume that a help-center note and an internal briefing have the same audience or approval.'] },
    { title: 'Handle customer-facing risk', paragraphs: ['Stop when a change affects data access, billing, security, contractual commitments, or a customer’s workflow in a way the approved brief does not explain.', 'The escalation should quote the relevant source location, state the missing decision, and identify the owner. A polished sentence cannot substitute for product approval.'] },
    { title: 'Sample editorial control', paragraphs: ['Review a routine change, a change with a limitation, and a change whose date moved. Check source, audience, terminology, reviewer, and route. Keep the prior approved version available.', 'Classify corrections as terminology, missing limitation, source conflict, date change, or owner decision. Apply only approved corrections.'] },
    { title: 'Measure the handoff', paragraphs: ['Track change packets received, source gaps, reviewer returns, unresolved product questions, channel variants, and corrections. These describe publishing control, not adoption, satisfaction, or product outcomes.', 'Expand after product and support owners agree on the source hierarchy, public language boundary, and final approval step.'] },
  ] },
  { slug: 'filipino-insurance-claims-intake-coordinator', title: 'How to plan Filipino insurance claims intake coordination', excerpt: 'Organize claim documents, chronology, and missing evidence while leaving coverage, liability, and settlement decisions with authorized reviewers.', lane: 'insurance claims intake coordination', focus: 'make a claim file complete and traceable without interpreting coverage or promising a claim outcome', sections: [
    { title: 'Build a neutral claim file', paragraphs: ['Use claim identifier, policy reference, incident date, claimant statement, submitted documents, contact history, and assigned owner. Preserve source wording and received timestamps.', 'The coordinator can identify a missing page or conflicting date. They should not decide whether an event is covered or describe liability as established.'] },
    { title: 'Use chronology before conclusions', paragraphs: ['Place reported events, documents, and communications in order with a source attached. Distinguish what the claimant said from what a document shows.', 'A chronology with an unresolved gap is valuable. Filling the gap with a likely event can mislead the claims reviewer and the claimant.'] },
    { title: 'Protect confidential information', paragraphs: ['Use approved systems and narrow permissions for identity, health, financial, and incident records. Do not download a full claim file for convenience.', 'Access questions, suspected exposure, or unusual requests should stop the lane and follow the approved privacy or claims escalation.'] },
    { title: 'Route missing evidence', paragraphs: ['A request for an additional document should be specific and approved. Avoid wording that promises acceptance, payment, or a timeline that the claims owner has not given.', 'Track whether the next action belongs to the claimant, adjuster, supervisor, legal reviewer, or system owner.'] },
    { title: 'Review file integrity', paragraphs: ['Sample a complete claim, one with missing evidence, and one with conflicting sources. Check identifiers, version, chronology, and escalation. Preserve original records while corrections are made.', 'A reviewer should be able to distinguish an intake mistake from a coverage question. That distinction keeps the role useful and safe.'] },
    { title: 'Define safe expansion', paragraphs: ['Measure claims received, missing-document reasons, duplicate files, owner waits, privacy escalations, and reviewer corrections. These are operating indicators, not claims outcomes.', 'Add another claim type only after the authorized owner approves its checklist, access level, message set, and stop rules.'] },
  ] },
  { slug: 'filipino-community-moderation-queue-coordinator', title: 'How to scope Filipino community moderation queue coordination', excerpt: 'Organize reported content, rule references, and reviewer status without making unapproved enforcement or safety decisions.', lane: 'community moderation queue coordination', focus: 'make reported-content evidence reviewable while keeping removal, account, and safety decisions with the authorized moderation owner', sections: [
    { title: 'Define the report packet', paragraphs: ['Record report identifier, content link, reporter context allowed by policy, rule reference, received time, and reviewer status. The coordinator can organize evidence and identify duplicates.', 'Do not infer intent, severity, or truth from a report alone. Those judgments require the approved policy and authorized reviewer.'] },
    { title: 'Preserve context safely', paragraphs: ['Keep the reported item, surrounding context, and source timestamp as the approved system permits. Avoid copying sensitive or harmful material into broad notes.', 'If a report involves a threat, vulnerable person, or urgent safety issue, use the named escalation route immediately rather than waiting for routine queue handling.'] },
    { title: 'Separate routing from enforcement', paragraphs: ['The role may tag a report by an approved category, link the policy section, and route it to a reviewer. It should not remove content, suspend an account, or promise an appeal result unless explicitly authorized.', 'When the rule does not fit, mark policy ambiguity and preserve the evidence. An invented category creates inconsistent enforcement.'] },
    { title: 'Make reviewer decisions legible', paragraphs: ['A decision record should identify the rule considered, evidence reviewed, action owner, and effective time. The coordinator can check that required fields exist without second-guessing the decision.', 'Keep reversals and appeals linked to the original report. Do not delete the first decision because a later action differs.'] },
    { title: 'Review queue quality', paragraphs: ['Sample an ordinary report, a duplicate, and a safety escalation. Check access, context, category, route, and response status. Corrections should identify whether the issue was evidence, policy, routing, or decision authority.', 'A second reviewer should be able to find the same source and understand what remains unresolved.'] },
    { title: 'Measure without gaming', paragraphs: ['Track reports received, duplicates, waiting reasons, escalations, reviewer returns, and unresolved policy questions. These are queue measures, not claims about community health, safety, or enforcement quality.', 'Expand only after the moderation owner confirms the policy set, privacy boundary, urgent escalation path, and action permissions.'] },
  ] },
  { slug: 'filipino-learning-content-qa-coordinator', title: 'How to plan Filipino learning content QA coordination', excerpt: 'Check approved course materials for completeness, source links, and review status while leaving instructional and grading decisions with educators.', lane: 'learning content QA coordination', focus: 'organize repeatable content checks and reviewer questions without changing educational meaning or certifying learning outcomes', sections: [
    { title: 'Define a lesson-ready packet', paragraphs: ['List course, module, version, learning objective, asset links, accessibility checks, reviewer, and approval state. The coordinator can run the agreed checklist and record observations.', 'A missing answer key or conflicting objective is a reviewer question, not an invitation to write a replacement from guesswork.'] },
    { title: 'Check content against sources', paragraphs: ['Compare terminology, references, links, and examples against the approved source. Record the exact page, lesson, or element where a mismatch appears.', 'Keep factual checking separate from deciding whether an exercise is pedagogically appropriate. Those require different owners and evidence.'] },
    { title: 'Protect learner information', paragraphs: ['Use sample or redacted learner records for QA where possible. Keep submissions, grades, and identity details in the approved system with minimum access.', 'If a test reveals a privacy or safety concern, pause the ordinary queue and route it through the named owner.'] },
    { title: 'Manage versioned changes', paragraphs: ['A content change should show old version, proposed version, source, requester, reviewer, and effective date. Do not overwrite the approved lesson before review.', 'When a link or asset changes, check every dependent lesson identified by the owner. A local fix can create a wider inconsistency.'] },
    { title: 'Sample the learner path', paragraphs: ['Review a complete module, a missing-asset module, and a source conflict. Check navigation, labels, links, version, and reviewer status. Keep observations distinct from recommendations.', 'A reviewer can approve corrections; the coordinator records them and confirms that the approved change reached the intended item.'] },
    { title: 'Set an honest scorecard', paragraphs: ['Track modules checked, broken links, missing assets, source questions, returned items, and reviewer corrections. These describe content operations, not completion, comprehension, or course results.', 'Expand by module family only after the educator owner confirms the checklist, access controls, and meaning-changing boundaries.'] },
  ] },
  { slug: 'filipino-business-continuity-records-coordinator', title: 'How to scope Filipino business continuity records coordination', excerpt: 'Maintain recovery contacts, dependency records, and exercise notes without making resilience or recovery guarantees.', lane: 'business continuity records coordination', focus: 'keep continuity evidence current and reviewable while leaving risk acceptance, recovery priorities, and emergency decisions with leadership', sections: [
    { title: 'Inventory continuity dependencies', paragraphs: ['Record process, owner, system, supplier, contact, dependency, review date, and source. The coordinator can find missing fields and request confirmation; they should not invent a recovery priority.', 'Separate current-state evidence from a proposed continuity plan. A draft contact list is not proof that a response will work.'] },
    { title: 'Keep contact evidence current', paragraphs: ['Use the approved directory and record the last confirmation, channel, time zone, and alternate path. Avoid copying personal contact details into broad documents.', 'If a contact cannot be confirmed, mark the dependency and route it. Do not declare coverage because an old number still exists.'] },
    { title: 'Document exercises neutrally', paragraphs: ['Capture exercise date, scenario approved by the owner, participants, observed actions, unresolved questions, and follow-up owner. The coordinator records what happened; leadership decides risk acceptance.', 'Do not present an exercise as proof that every real incident will be handled. Keep limitations and assumptions visible.'] },
    { title: 'Handle urgent records carefully', paragraphs: ['A continuity queue may surface a missing supplier, inaccessible system, or safety concern. Use the named escalation path and preserve the source; do not improvise a crisis instruction.', 'Access to plans can itself be sensitive. List who may read or edit each record and when that access should be reviewed.'] },
    { title: 'Review evidence by dependency', paragraphs: ['Sample an ordinary dependency, an expired contact, and an exercise follow-up. Check source, owner, date, access, and next action. Classify corrections as stale data, missing ownership, source conflict, or leadership decision.', 'Keep a dated decision log so a later reviewer can tell what was known at the time.'] },
    { title: 'Measure continuity preparation', paragraphs: ['Track dependencies inventoried, confirmations pending, overdue reviews, exercise actions, access exceptions, and owner decisions. These do not promise recovery time, resilience, or business continuity.', 'Expand only after leadership confirms the scope, confidentiality, escalation path, and risk-acceptance boundary.'] },
  ] },
  { slug: 'filipino-customer-feedback-evidence-coordinator', title: 'How to plan Filipino customer feedback evidence coordination', excerpt: 'Organize survey, interview, and support feedback with traceable sources while leaving interpretation and prioritization with the customer team.', lane: 'customer feedback evidence coordination', focus: 'preserve customer feedback as inspectable evidence without turning collection notes into unsupported sentiment or product conclusions', sections: [
    { title: 'Define the feedback question', paragraphs: ['State the question, source channels, time window, audience, and coding rules before collecting records. The coordinator can organize approved responses and note missing context.', 'Do not change a customer’s wording to fit a theme. Keep an excerpt, source, date, and any permitted context together.'] },
    { title: 'Keep evidence separate from themes', paragraphs: ['A repeated phrase can be counted under an approved code, but the meaning and priority of the theme belong to the research or customer owner.', 'If a response could support several codes, retain the uncertainty or apply the approved multi-code rule. A forced single label can erase important context.'] },
    { title: 'Protect identities and permissions', paragraphs: ['Use participant or account codes where possible and keep identifiable details in the approved system. Do not export raw feedback into an open working document.', 'Check whether a source permits internal use, quotation, or follow-up. If permission is unclear, stop and route the question.'] },
    { title: 'Prepare an evidence packet', paragraphs: ['A useful packet includes method, sample definition, raw-source links, coding notes, exclusions, and open questions. It lets the owner inspect how a summary was made.', 'Never claim that a small or filtered set represents every customer. State the boundary of the evidence and let the owner decide how to use it.'] },
    { title: 'Review disagreements', paragraphs: ['Sample a clear response, an ambiguous response, and a record with missing permission. Check source, code, privacy, and reviewer. Classify corrections as transcription, coding rule, source gap, or interpretation.', 'Keep changes dated and preserve the prior coding decision when it may matter to a later comparison.'] },
    { title: 'Measure collection, not outcomes', paragraphs: ['Track responses received, permission gaps, uncoded items, code questions, owner reviews, and corrections. These are evidence-management signals, not claims about satisfaction or product demand.', 'Expand after the owner confirms the question, source permissions, coding rule, and decision boundary for the next channel.'] },
  ] },
];

const august21DirectDateBindings: Record<string, '2026-08-21'> = {
  'filipino-customer-onboarding-implementation-coordinator': '2026-08-21',
  'filipino-revenue-operations-forecast-support-coordinator': '2026-08-21',
  'filipino-hr-policy-documentation-coordinator': '2026-08-21',
  'filipino-ecommerce-refund-case-preparation-coordinator': '2026-08-21',
  'filipino-website-analytics-reporting-coordinator': '2026-08-21',
  'filipino-vendor-compliance-records-coordinator': '2026-08-21',
  'filipino-product-support-release-notes-coordinator': '2026-08-21',
  'filipino-insurance-claims-intake-coordinator': '2026-08-21',
  'filipino-community-moderation-queue-coordinator': '2026-08-21',
  'filipino-learning-content-qa-coordinator': '2026-08-21',
  'filipino-business-continuity-records-coordinator': '2026-08-21',
  'filipino-customer-feedback-evidence-coordinator': '2026-08-21',
};

const makeDetail = (topic: Topic) => ({
  datePublished: august21DirectDateBindings[topic.slug],
  dateModified: august21DirectDateBindings[topic.slug],
  publishedLabel: 'August 21, 2026',
  image: imageFor(topic.slug, topic.lane),
  lead: topic.excerpt,
  shortAnswer: `For FilipinoOutsource.com, ${topic.lane} works best as a bounded support lane: ${topic.focus}. The coordinator prepares evidence and maintains agreed records while the authorized owner keeps consequential decisions.`,
  takeaways: ['Name the recurring queue and its finished output.', 'Show a normal item, an incomplete item, and a stop-rule item.', 'Use named access limited to the first queue.', 'Keep source facts, interpretation, and owner decisions separate.', 'Expand only after a second reviewer can reproduce the handoff.'],
  sections: [...topic.sections, {
    title: 'Keep the operating record reviewable',
    paragraphs: [
      `A durable ${topic.lane} record should show the item identifier, approved source, received time, fields checked, current state, reason code, worker note, named owner, and handoff date. Keep original wording when it affects meaning, and link to the source rather than copying more sensitive material than the queue needs. A specific waiting state tells the owner whether the next action belongs to the sender, a reviewer, a system owner, or a decision-maker. That distinction makes the lane easier to resume across Philippine and client working hours.`,
      `Write stop rules before the first live handoff for ${topic.lane}. Pause when evidence conflicts, a request could change a customer commitment, payment or remedy might be authorized, account access might change, a privacy or policy question appears, an employment consequence is implied, or a public claim lacks approval. The escalation should state what the source shows, what is uncertain, which evidence is attached, and what decision the owner must make. A dated owner response should link back to the example that prompted the question.`,
      `Access should follow the queue rather than the title of the role. List every system, permission level, purpose, approving owner, review date, and removal step for ${topic.lane}. Use named accounts and approved authentication controls where available. Avoid shared credentials, broad administrator rights, and convenience exports that move sensitive records away from the approved system. If the work expands into a new system or a new kind of decision, pause and obtain a revised approval instead of treating an informal request as part of the original brief.`,
      `Quality review should compare the source record, written instruction, and resulting handoff. A named reviewer can sample an ordinary item, an incomplete item, and a stop-rule item. Classify corrections as a missed rule, weak example, source conflict, execution mistake, or unsettled owner question. Only the owner can approve a change to policy or scope. Record accepted corrections with an effective date and identify earlier records that may need another look.`,
      `Continuity matters when a regular worker is unavailable or a queue crosses time zones. Keep current status, last source checked, unresolved question, next owner action, handoff date, and access limitation together. A substitute should preserve the item and escalate it rather than reconstructing private chat history or guessing. For ${topic.lane}, this record is more useful than a broad narrative because another person can see exactly what is complete and what remains with the owner.`,
      `Review the first live batch at a deliberate cadence. Compare a routine item with the approved example, then inspect an item that stopped and ask whether the escalation contains enough evidence for a decision. If the reviewer repeatedly answers the same question, update the written instruction only after the owner confirms the rule. If questions remain genuinely judgment-heavy, keep them out of the queue and make the boundary more explicit.`,
      `Measure received, completed, returned, waiting, escalated, missing fields, reason codes, reviewer corrections, and age of open decisions for ${topic.lane}. These signals improve the workflow; they are not promises about savings, speed, accuracy, coverage, resilience, satisfaction, or any other business outcome. A higher escalation count can indicate that the role is correctly stopping at a consequential boundary rather than failing to process work.`,
      `Before expanding ${topic.lane}, ask a manager who did not write the brief to explain the source, finish point, examples, stop rules, access limits, reviewer, and decisions outside the role. If that explanation depends on memory, narrow the queue or settle the missing rule first. The intended evidence for FilipinoOutsource.com staffing planning is a small operating lane that is teachable, inspectable, and safe to hand back to the business owner.`,
    ],
  }],
  metrics: { title: 'A bounded launch scorecard', intro: `Track review signals for ${topic.lane}; do not treat them as promises.`, items: [{ value: '1', label: 'queue', note: 'A defined recurring lane.' }, { value: '3', label: 'examples', note: 'Normal, incomplete, and exception.' }, { value: '1', label: 'owner', note: 'A named reviewer.' }, { value: '0', label: 'guessed decisions', note: 'Stop cases have a route.' }], note: 'The scorecard supports inspection rather than outcome claims.' },
  comparisonTitle: 'Open-ended help versus bounded support',
  comparison: [{ question: 'What enters?', weak: 'Anything related to the function.', useful: `Items matching the ${topic.lane} intake rule.` }, { question: 'What happens when evidence conflicts?', weak: 'The worker fixes it.', useful: 'Sources stay attached and the owner receives a precise question.' }, { question: 'Who decides exceptions?', weak: 'The person in the queue.', useful: 'The named business owner.' }],
  sources: [{ name: 'CISA: Require multifactor authentication', url: 'https://www.cisa.gov/secure-our-world/require-multifactor-authentication', note: 'Account security reference.' }],
  faqs: [{ question: `What belongs in the first ${topic.lane} queue?`, answer: 'Recurring work with approved inputs, examples, a clear finish point, and a named reviewer.' }, { question: 'When should the role stop?', answer: 'When evidence conflicts, a sensitive judgment is required, or the request exceeds approved examples.' }, { question: 'When can the scope expand?', answer: 'After sample review is reproducible and repeated questions have been resolved in writing.' }],
  tags: [topic.lane, 'Role brief', 'Philippines staffing'],
  related: [{ href: '/blog/Filipino-outsource-staffing-planning', label: 'Staffing plan' }, { href: '/blog/Filipino-outsource-staffing-onboarding-checklist', label: 'Launch checklist' }],
});

export const august21BlogPosts = topics.map(({ slug, title, excerpt }) => ({ slug, title, excerpt, minutes: 11 }));
export const august21BlogDetails = Object.fromEntries(topics.map((topic) => [topic.slug, makeDetail(topic)]));
