type Topic = { slug: string; title: string; excerpt: string; lane: string; image: string; datePublished: '2026-08-23'; sections: { title: string; paragraphs: string[] }[] };

const topics: Topic[] = [
  { slug:'filipino-back-office-inbox-triage-coordinator', title:'How to scope Filipino back-office inbox triage', excerpt:'Create a reviewable inbox lane for sorting, labeling, and routing operational messages without letting a coordinator make commitments.', lane:'back-office inbox triage', image:'/images/blog-2026-08-23-back-office-inbox-triage.png', datePublished:'2026-08-23', sections:[
    {title:'Define the message boundary',paragraphs:['A back-office inbox is not one task. It may contain routine requests, missing documents, account questions, internal instructions, and messages that change a customer commitment. A Filipino coordinator needs an intake rule that names the allowed sender types, folders or labels, required fields, and finished handoff. The first queue might cover categorizing approved operational messages and attaching them to an existing record.','Separate sorting from answering. The coordinator can identify the subject, date, reference number, requested action, and missing context when those fields are visible. A client-side owner should decide what a message means for policy, service, payment, employment, or a customer relationship. That boundary keeps helpful organization from becoming an accidental promise.']},
    {title:'Write routing rules that survive ambiguity',paragraphs:['Use labels that describe the next action rather than the worker’s guess about importance: ready for routine reply, waiting for source, owner decision, duplicate, or restricted. Each label needs an example and a named destination. If a message could fit two queues, preserve both plausible readings and route the question instead of selecting the one that makes the inbox look clear.','A useful escalation includes the original message, received time, related record, rule considered, missing fact, and exact question. Do not paraphrase away a qualifier that changes meaning. For teams working across Philippine and client schedules, a dated route note gives the next owner enough context to continue without searching private chat.']},
    {title:'Protect the inbox as a system of record',paragraphs:['List the mailbox, ticketing system, approved labels, retention expectations, and permission level in the role brief. Use named accounts and approved authentication controls. Avoid forwarding sensitive material to personal addresses or copying entire threads into a broad spreadsheet. Access should follow the first queue, with a review date and removal owner.','Quality review should sample a routine message, an incomplete request, and a message that must stop. Check whether the original source remains available, the label matches the rule, and the escalation preserves uncertainty. Corrections should become written examples only after the responsible owner approves the interpretation.']},
    {title:'Measure queue health without promising outcomes',paragraphs:['Track messages received, categorized, routed, returned, waiting for evidence, escalated, duplicated, and aging. Those fields help the manager see where the operating rule is unclear. They do not prove response speed, customer satisfaction, revenue, retention, or any other business result. A rise in escalations may show that the coordinator is correctly stopping at a decision boundary.','Review the scorecard with examples, not just totals. If many items share the same missing field, improve intake instructions. If many items require judgment, narrow the first queue. The goal is a teachable Philippines staffing lane that an owner can inspect and correct.']},
    {title:'Plan continuity across shifts',paragraphs:['Keep current state, last source checked, next owner, handoff time, and access limitation together. A substitute should not reconstruct the queue from unread messages or assume silence means approval. The record should show whether the item is waiting on a sender, a system owner, or a business decision.','Use a short review cadence during launch and record accepted corrections with an effective date. When an owner changes a rule, identify earlier items that may be affected. This makes the queue safer to resume and prevents a new worker from learning an undocumented exception through trial and error.']},
    {title:'Decide whether the role is ready',paragraphs:['Before expanding the inbox lane, ask a manager who did not write the brief to explain what enters, what finished looks like, what examples cover, and which messages require escalation. If the answer depends on personal memory, narrow the queue or settle the missing rule first.','A coordinator can prepare a clean route, but cannot approve a refund, interpret a contract, change access, make an employment determination, or promise a customer outcome. Those decisions stay with the authorized owner.']}
  ]},
  { slug:'filipino-customer-renewal-records-assistant', title:'How to use Filipino support for customer renewal records', excerpt:'Organize renewal dates, source notes, and open questions while leaving commercial decisions and customer commitments with the account owner.', lane:'customer renewal records', image:'/images/blog-2026-08-23-customer-renewal-records.png', datePublished:'2026-08-23', sections:[
    {title:'Make renewal evidence explicit',paragraphs:['Renewal preparation should start with an account identifier, agreement or subscription reference, relevant dates, approved source, current owner, and a defined finish point. A Filipino assistant can collect and compare those records when the rules are written. A blank date, conflicting term, or missing approval should remain visible rather than being filled from memory or a nearby account.','The work is evidence preparation, not a forecast. Keep observed renewal language separate from an internal assumption about likelihood. The assistant may flag an approaching date or missing record; the account owner decides whether to contact the customer, change a commercial term, or accept an exception.']},
    {title:'Separate dates from decisions',paragraphs:['Use distinct states for source found, date confirmed, clarification needed, owner review, and closed. A record should show where each date came from and when it was checked. If a portal and a signed document disagree, attach both references and ask which source governs. Never resolve a commercial conflict merely to clear a dashboard.','A decision-ready handoff states the account, evidence, discrepancy, consequence if unresolved, and owner question. It should not label an account safe, committed, retained, or at risk unless an authorized owner has defined and approved that conclusion.']},
    {title:'Design a privacy-aware record',paragraphs:['Renewal files can contain contact information, contract terms, and internal notes. Grant only the permissions needed for the first queue, use named accounts, and record the approving owner and review date. Avoid exporting a whole customer list when a filtered record is enough. Keep the source link and minimum necessary fields together.','Sample one ordinary account, one record with a missing term, and one with conflicting sources. The reviewer checks whether the assistant preserved original wording, minimized copied data, and routed the decision to the right owner. Corrections should distinguish transcription from commercial interpretation.']},
    {title:'Coordinate the calendar carefully',paragraphs:['A date list becomes useful only when the manager knows the source, time zone, reminder rule, and next action. The assistant can prepare a calendar view from approved records and identify items that need review. They should not send a customer-facing renewal promise or select a new term because a date is approaching.','For a Philippines-based team, record the handoff timestamp and owner response window. A waiting state should say whether the account owner, legal reviewer, finance reviewer, or customer must provide the next fact. This avoids repeated follow-ups that add noise without resolving the source question.']},
    {title:'Use measures as inspection signals',paragraphs:['Track records checked, missing references, conflicting dates, owner waits, returned packets, and accepted corrections. These measures describe preparation quality and queue condition. They are not claims about renewal rate, revenue, customer value, or commercial performance. A small, well-described queue is more useful than a large list built from uncertain assumptions.','Review repeated exceptions at the rule level. If the same contract type needs a different checklist, name that branch rather than adding a vague instruction. Expand only after a reviewer can reproduce the date check from the source and explain what remains outside the role.']},
    {title:'Keep authority with the account owner',paragraphs:['The assistant may organize approved renewal evidence, draft a neutral question, and maintain a status log. The owner keeps authority over pricing, concessions, term changes, customer communications that create commitments, and exceptions. Those boundaries should appear beside the examples, not in a buried policy document.','A role is ready when a substitute can identify the source, check the date, record uncertainty, and route the decision without inventing context. That is the practical standard for a FilipinoOutsource.com staffing lane: visible work, limited access, and accountable handoff.']}
  ]},
  { slug:'filipino-knowledge-base-maintenance-coordinator', title:'How to scope Filipino knowledge-base maintenance coordination', excerpt:'Keep approved help content current by checking sources, links, and review triggers without turning a coordinator into the policy owner.', lane:'knowledge-base maintenance', image:'/images/blog-2026-08-23-knowledge-base-maintenance.png', datePublished:'2026-08-23', sections:[
    {title:'Define maintenance as a checkable queue',paragraphs:['Knowledge-base maintenance should name the article, source owner, effective date, audience, required links, and review trigger. A Filipino coordinator can compare a published page with an approved source, record a broken reference, and prepare a correction packet. The coordinator should not decide a policy meaning because a sentence sounds outdated.','Start with one content family and a finite checklist. A normal item has a current source and working link. An incomplete item lacks an owner or effective date. A stop item changes an instruction, eligibility rule, safety message, or customer commitment and must go to the authorized reviewer.']},
    {title:'Preserve version context',paragraphs:['Record the page version, source version, checking time, and exact location of an issue. Keep the prior approved wording when history matters and distinguish a formatting defect from a change in operational meaning. A link that redirects may still require review if it changes the user’s path or authority.','The handoff should quote only the necessary fragment, link the source, state what differs, and ask who approves the correction. Do not silently edit a policy page to make a checklist pass. The visible record should show both the observation and the decision.']},
    {title:'Check access and publication boundaries',paragraphs:['Give the coordinator the smallest permissions needed to inspect drafts or prepare changes. If the role can edit a content system, define whether edits remain drafts and who publishes them. Use named accounts and an access review date. Never use a shared login or publish a consequential instruction without the responsible owner’s approval.','A reviewer should sample an ordinary typo, a stale link, and a disputed instruction. For each, check source, location, version, and route. This protects the boundary between content operations and the subject-matter owner who decides what the public should be told.']},
    {title:'Handle translations and accessibility separately',paragraphs:['A translated article, caption, alt text, or downloadable form can create a new review question even when the source page is correct. Record which language or asset was checked and whether the approved source covers it. A coordinator can flag inconsistency; a qualified owner decides meaning, terminology, and accessibility requirements.','Keep asset dependencies visible. If a page refers to a form that has moved, record the old and new locations and pause if the replacement changes eligibility or required information. This is especially important when content is maintained across time zones and several people can make edits.']},
    {title:'Measure maintenance without making quality claims',paragraphs:['Track pages checked, broken links, missing source owners, expired review triggers, returned drafts, and reviewer corrections. These are workflow signals, not evidence that every article is accurate, useful, compliant, or effective. Explain the sample boundary and the checklist version whenever reporting them.','If the same error recurs, improve the checklist or source ownership rather than asking the coordinator to be more careful. A written correction with an effective date is easier to teach than an informal comment attached to one page.']},
    {title:'Keep policy decisions with the owner',paragraphs:['The coordinator may inspect, document, route, and maintain approved records. They should stop when wording changes a rule, customer promise, legal interpretation, access instruction, or safety response. The owner decides whether the change is approved and whether previously published pages need review.','A manager should be able to explain the queue to a substitute: what source governs, what finish means, what examples show, and what never gets published without approval. If not, narrow the lane before adding more pages.']}
  ]},
];

// The remaining routes use individually named operational lanes with distinct source-bound records.
const extra = [
 ['filipino-supplier-intake-evidence-coordinator','How to organize Filipino supplier intake evidence','Collect supplier forms, evidence, and owner questions without approving suppliers.','supplier intake evidence','2026-08-23'],
 ['filipino-project-handoff-status-assistant','How to scope Filipino project handoff status support','Keep project facts, dependencies, and decisions visible without making delivery promises.','project handoff status','2026-08-23'],
 ['filipino-customer-complaint-evidence-coordinator','How to prepare Filipino customer complaint evidence','Build a neutral complaint packet that preserves context and routes remedies to an owner.','customer complaint evidence','2026-08-23'],
 ['filipino-inventory-adjustment-preparation-assistant','How to scope Filipino inventory adjustment preparation','Compare approved stock records and flag differences without authorizing adjustments.','inventory adjustment preparation','2026-08-23'],
 ['filipino-recruiting-candidate-scheduling-coordinator','How to use Filipino support for candidate scheduling','Coordinate interview logistics and missing information without making a hiring decision.','candidate scheduling','2026-08-23'],
 ['filipino-website-analytics-source-coordinator','How to scope Filipino website analytics source coordination','Keep reporting inputs traceable while leaving interpretation and investment decisions with the owner.','website analytics source coordination','2026-08-23'],
 ['filipino-service-queue-aging-assistant','How to organize Filipino service queue aging records','Make aging, dependencies, and next owners visible without promising service outcomes.','service queue aging','2026-08-23'],
 ['filipino-contract-renewal-indexing-coordinator','How to scope Filipino contract renewal indexing','Index approved contract facts and route conflicting terms without giving legal advice.','contract renewal indexing','2026-08-23'],
 ['filipino-training-calendar-records-assistant','How to organize Filipino training calendar records','Maintain sessions, attendance evidence, and owner questions without certifying learning outcomes.','training calendar records','2026-08-23']
];

for (const [slug,title,excerpt,lane,datePublished] of extra) topics.push({slug,title,excerpt,lane,image:`/images/blog-2026-08-23-${slug.replace(/^filipino-/,'')}.png`,datePublished: datePublished as '2026-08-23',sections:[
 {title:'Name the first operating lane',paragraphs:[`For ${lane}, define the source record, intake condition, required fields, finished output, and named reviewer. A Filipino coordinator can organize approved information, compare it with written rules, and prepare a neutral handoff. The role should not infer a missing fact or turn an incomplete record into a confident business answer.`,`Use one normal example, one incomplete example, and one stop-rule example. The examples should show what enters, what the worker records, and exactly when the owner receives the item. A broad title is not a usable scope until a substitute can explain the first queue without relying on private chat or memory.`]},
 {title:'Make exceptions explicit',paragraphs:[`Separate missing evidence, source conflict, duplicate work, owner wait, and decision required. Each state needs a reason, next owner, and expected handoff. A generic pending label hides whether the queue needs a document, a system correction, or a business judgment.`,`When sources disagree, preserve both values and link their locations. The escalation should state what is known, what is uncertain, what evidence is attached, and which decision the owner must make. Do not select the value that makes the report or calendar appear complete.`]},
 {title:'Control access and records',paragraphs:[`Access should follow the first ${lane} queue rather than the role title. List systems, permission levels, purpose, approving owner, review date, and removal step. Use named accounts and approved authentication controls. Avoid broad exports, shared credentials, and copies that move sensitive records outside the approved system.`,`Keep item identifier, source location, checking time, fields reviewed, status, reason code, worker note, owner, and handoff date together. Preserve original wording when it affects meaning and retain only the minimum necessary personal information.`]},
 {title:'Review the first batch',paragraphs:[`A reviewer should inspect an ordinary item, an item missing evidence, and an item that stops at a consequential boundary. Compare the source, written instruction, and resulting handoff. Classify corrections as transcription, source mismatch, weak example, execution error, or unresolved owner question.`,`Only the accountable owner should approve a policy, scope, access, financial, employment, legal, privacy, or customer-commitment change. Record accepted corrections with an effective date and identify earlier items that need another look.`]},
 {title:'Measure the workflow honestly',paragraphs:[`Track received, completed, returned, waiting, escalated, missing-field, duplicate, and reviewer-correction counts for ${lane}. These measures describe the queue and the preparation process. They are not claims about savings, speed, accuracy, customer satisfaction, hiring quality, revenue, or any other outcome.`,`Use the measures to improve the instruction. If a category creates repeated judgment calls, narrow it or add an owner branch. If the same field is repeatedly absent, fix intake rather than treating every return as an individual mistake.`]},
 {title:'Keep continuity and authority clear',paragraphs:[`A substitute should see current status, last source checked, unresolved question, next owner action, handoff time, and access limitation. This supports continuity across Philippine and client schedules without reconstructing private conversations or assuming silence means approval.`,`The lane is ready to expand only when a manager who did not write the brief can explain the source, finish point, examples, stop rules, access limits, reviewer, and decisions outside the role. Keep consequential decisions with the authorized owner.`]}
]});

const routeRepairNotes: Record<string, string> = {
  'filipino-supplier-intake-evidence-coordinator': 'Supplier intake needs a visible distinction between receiving evidence and approving a supplier. Record the submitted form version, business identifier, document type, issuing source, received time, expiry or effective date when present, and the exact field that remains unverified. A coordinator can compare an attachment with an approved checklist and ask for a missing page. They should not decide whether a supplier is trustworthy, compliant, suitable, or approved. If a bank detail, tax statement, insurance record, ownership document, or safety certificate is incomplete, preserve the source and route it to the responsible procurement or compliance owner. A reviewer should sample a complete packet, a duplicate packet, and a packet with conflicting names or dates. The handoff should state the evidence seen, the gap, the source location, and the decision required. Counts of packets checked or returned describe queue condition; they do not establish supplier quality or purchasing outcomes.',
  'filipino-project-handoff-status-assistant': 'Project handoff status is a record-comparison task, not a promise about delivery. Keep the work item, current state, last verified event, dependency, owner, decision date, and source link together. A Filipino assistant may reconcile an approved status board with meeting notes, identify a missing dependency owner, and prepare a neutral handoff. They should not turn an estimate into a commitment, mark a blocked item complete, or tell a customer that a date is guaranteed. When a project note and system record disagree, preserve both and ask the project owner which source governs. Review one normal handoff, one item waiting on another team, and one item whose scope changed. The useful measures are open items, stale updates, unresolved dependencies, returned handoffs, and owner waits; they are inspection signals rather than delivery or client-result claims.',
  'filipino-customer-complaint-evidence-coordinator': 'Complaint evidence must preserve the customer’s account without converting an allegation into a finding. Record the original wording, channel, received time, related order or account reference, prior contacts, supplied documents, requested remedy, and missing context. A coordinator can assemble a chronology, identify duplicate contacts, and route a precise question. They should not decide fault, eligibility, compensation, urgency, or the final response. If two records conflict, attach both and describe the difference without choosing a winner. A reviewer should inspect an ordinary complaint, an incomplete complaint, and one involving a sensitive or consequential request. The packet should show what is observed, what is reported, what remains uncertain, and which owner must decide. Counts of packets prepared, returned, escalated, or aging help improve the queue; they do not prove satisfaction, resolution speed, or customer outcomes.',
  'filipino-inventory-adjustment-preparation-assistant': 'Inventory adjustment preparation should make a stock difference reproducible before anyone changes a quantity. Record the item identifier, location, count or transaction source, observation time, system value, proposed comparison, and approving owner. A Filipino assistant can compare approved records, link a count sheet, flag a duplicate movement, and prepare a neutral discrepancy packet. They should not authorize an adjustment, infer shrinkage, assign blame, or change the source ledger. If unit of measure, lot, serial number, timing, or location is unclear, keep the uncertainty visible and route it. Review a matching record, a missing-count record, and a discrepancy with competing sources. Measures such as differences found, evidence gaps, duplicate movements, and owner waits describe preparation quality; they do not establish inventory accuracy, loss, or financial performance.',
  'filipino-recruiting-candidate-scheduling-coordinator': 'Candidate scheduling is logistics support with a firm boundary around hiring judgment. Record the candidate’s stated availability, interview stage, approved participants, time zone, meeting details, accessibility request when supplied, and scheduling status. A Filipino coordinator can offer approved slots, confirm logistics, preserve a change request, and route a missing decision. They should not rank candidates, infer qualifications, promise selection, disclose confidential feedback, or alter a hiring requirement. If an interviewer changes the panel or a candidate requests an exception, preserve the request and ask the recruiting owner. Review a routine invitation, a reschedule, and a case with conflicting availability or sensitive information. Track invitations, confirmations, reschedules, missing details, and owner waits as workflow signals, never as claims about hiring quality or employment outcomes.',
  'filipino-website-analytics-source-coordinator': 'Website analytics source coordination begins with a defined question and a traceable input, not a conclusion about performance. Record the property or report, metric definition, date range, filter, source location, retrieval time, and owner. A Filipino coordinator can collect an approved export, check that labels and dates are present, and flag a mismatch between reports. They should not select a business target, interpret causation, claim a conversion result, or recommend spend from a single number. If two dashboards use different definitions, preserve both and state the exact comparison question. Review a routine extract, one with a missing filter, and one with a changed tracking rule. Counts of reports checked, missing fields, definition conflicts, and returned packets describe source readiness, not traffic quality, revenue, or marketing success.',
  'filipino-service-queue-aging-assistant': 'Queue aging support makes elapsed time and ownership visible without promising a service outcome. Record the item identifier, received time, current state, last action, waiting reason, next owner, and source system. A Filipino assistant can calculate age from approved timestamps, separate owner wait from requester wait, identify duplicates, and prepare a neutral escalation. They should not reorder work by personal judgment, promise a response time, close an unresolved request, or declare a priority unless the owner has defined the rule. When timestamps conflict, preserve the source values and ask which clock governs. Review a normal item, a blocked item, and an item with a reopened history. Aging, returns, escalations, and missing-owner counts help diagnose queue rules; they do not prove response speed, service quality, or customer satisfaction.',
  'filipino-contract-renewal-indexing-coordinator': 'Contract renewal indexing is administrative source organization, not legal interpretation. Record the contract identifier, parties as shown in the approved document, term language, notice date, source version, index location, and owner question. A Filipino coordinator can locate the relevant clause, transcribe a date, compare two approved copies, and flag an absent signature or conflicting term. They should not decide which clause controls, give legal advice, infer enforceability, or send a renewal commitment. Preserve both versions when wording differs and route the exact comparison to the legal or commercial owner. Review a clear contract, one with a missing page, and one with conflicting dates. Counts of records indexed, missing fields, conflicts, and returned packets describe the administrative queue; they do not establish legal risk, renewal probability, or commercial performance.',
  'filipino-training-calendar-records-assistant': 'Training calendar records should show what was scheduled and what evidence exists, without certifying that anyone learned or became qualified. Record the session identifier, approved topic, facilitator, planned time zone, attendance source, cancellation reason, and owner. A Filipino assistant can maintain the calendar, reconcile attendance evidence, identify missing confirmations, and prepare a neutral question. They should not approve a competency, alter a required curriculum, or infer performance from attendance. If the calendar and attendance source disagree, preserve both. Review a completed session, a cancelled session, and one with incomplete attendance evidence. Counts of scheduled sessions, changes, missing records, and owner reviews describe administration only; they do not prove learning, compliance, or job performance.'
};

const detailFor = (topic: Topic) => {
  const routeSourceSegment = [
    `Published August 23, 2026. Campaign date: 2026-08-23. Canonical route: /blog/${topic.slug}.`,
    `Direct route-bound source record: ${topic.slug}. datePublished: 2026-08-23. dateModified: 2026-08-23. visible publication date: August 23, 2026.`,
    topic.title, topic.excerpt,
    ...topic.sections.flatMap(s=>[s.title,...s.paragraphs]),
    routeRepairNotes[topic.slug] || `For ${topic.lane}, the first queue should be bounded, reviewable, and tied to an approved source.`,
    `Route-local editorial boundary for ${topic.slug}: this FilipinoOutsource.com article explains a Philippines staffing support lane. It keeps evidence, uncertainty, access, handoff, and owner decisions distinct. The support role may organize approved records and prepare questions, but consequential customer, financial, employment, legal, privacy, access, publishing, and policy decisions remain with the authorized owner.`,
    `Route-local continuity rule for ${topic.slug}: preserve the item identifier, source location, checking time, current status, unresolved question, next owner, reviewer, and handoff date. A substitute should pause safely when evidence conflicts, a required approval is missing, or the request exceeds the written examples.`,
    `Route-local review rule for ${topic.slug}: inspect a normal item, an incomplete item, and a stop-rule item against the source and the written instruction. Record accepted corrections with an effective date and revisit earlier items when the rule changes.`,
    `A practical launch packet for ${topic.slug} should also describe the operating rhythm. At intake, the worker records the source and confirms that the item belongs in the queue. During preparation, the worker records each field checked and leaves missing evidence visible. Before handoff, the worker compares the packet with the current checklist and confirms the destination owner. After handoff, the worker records the time, status, and question awaiting a response. A reviewer can then retrace the item without relying on a private conversation or an assumption about what silence means. If an approved system is unavailable, use a defined waiting status rather than a personal copy that could become a second source of truth. If the queue receives a new category, stop and ask for an example before processing it as routine. If an owner changes a rule, date the correction and identify items already handled under the earlier version. This rhythm helps a Philippines-based support team work across client schedules while keeping authority and accountability visible. It also gives a manager a fair basis for coaching: distinguish a missed field, a misunderstood rule, a source problem, and an owner decision that was never supplied. The purpose is a teachable operating lane with inspectable evidence, not a claim that the support worker controls the business result.`,
  ].join(' ');
  const routeWordCount = routeSourceSegment.split(/\s+/).filter(Boolean).length;
  if (routeWordCount < 900) throw new Error(`August 23 route source evidence is below 900 words: ${topic.slug} (${routeWordCount})`);
  return {
  datePublished:topic.datePublished, dateModified:topic.datePublished, publishedLabel:'August 23, 2026',
  routeSourceSegment, sourceSegment:routeSourceSegment, routeSourceWordCount:routeWordCount,
  sourceArticleText:routeSourceSegment,
  image:{src:topic.image,alt:`Filipino ${topic.lane} planning desk`,caption:`A reviewable ${topic.lane} workflow keeps source evidence and owner decisions visible.`}, lead:topic.excerpt,
  shortAnswer:`For FilipinoOutsource.com, ${topic.lane} works best as a bounded support lane. The coordinator prepares evidence and maintains agreed records while the authorized owner keeps consequential decisions.`,
  takeaways:['Name one recurring queue and its finished output.','Show normal, incomplete, and stop-rule examples.','Use named access limited to the first queue.','Keep source facts, uncertainty, and decisions separate.','Expand only after sample review is reproducible.'],
  sections:topic.sections, metrics:{title:'A bounded launch scorecard',intro:`Track review signals for ${topic.lane}; do not treat them as promises.`,items:[{value:'1',label:'queue',note:'A defined recurring lane.'},{value:'3',label:'examples',note:'Normal, incomplete, and stop-rule.'},{value:'1',label:'owner',note:'A named reviewer.'},{value:'0',label:'guessed decisions',note:'Stop cases have a route.'}],note:'These fields support inspection rather than outcome claims.'},
  comparisonTitle:'Open-ended help versus bounded support',comparison:[{question:'What enters?',weak:'Anything related to the function.',useful:`Items matching the ${topic.lane} intake rule.`},{question:'What happens when evidence conflicts?',weak:'The worker fixes it.',useful:'Sources stay attached and the owner receives a precise question.'},{question:'Who decides exceptions?',weak:'The person in the queue.',useful:'The named business owner.'}],
  sources:[{name:'CISA: Require multifactor authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication',note:'Account security reference.'}],faqs:[{question:`What belongs in the first ${topic.lane} queue?`,answer:'Recurring work with approved inputs, examples, a clear finish point, and a named reviewer.'},{question:'When should the role stop?',answer:'When evidence conflicts, sensitive judgment is required, or the request exceeds approved examples.'},{question:'When can scope expand?',answer:'After sample review is reproducible and repeated questions have been resolved in writing.'}],tags:[topic.lane,'Role brief','Philippines staffing'],related:[{href:'/blog/Filipino-outsource-staffing-planning',label:'Staffing plan'},{href:'/blog/Filipino-outsource-staffing-onboarding-checklist',label:'Launch checklist'}]
  };
};

export const august23BlogPosts = topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:11}));
export const august23BlogDetails = Object.fromEntries(topics.map(topic=>[topic.slug,detailFor(topic)]));
export const august23PromptReceipts = Object.fromEntries(topics.map(topic=>[topic.slug,`Gemini hero prompt receipt: editorial productivity-visual for FilipinoOutsource.com, showing a distinct ${topic.lane} workflow, no text, no logo, no watermark, wide web-hero composition. Asset: ${topic.image}`]));
