const topics = [
  ['filipino-podcast-production-assistant', 'How to scope a Filipino podcast production assistant', 'Plan episode research, guest coordination, and handoff checks without giving away editorial control.', 'podcast production'],
  ['filipino-video-editing-coordinator', 'How to plan Filipino video editing coordination', 'Create a clean footage queue, naming rules, feedback loop, and approval boundary for video work.', 'video editing coordination'],
  ['filipino-accounts-payable-data-support', 'How to scope Filipino accounts payable data support', 'Organize invoice intake and coding preparation while keeping payment approval with your finance owner.', 'accounts payable data'],
  ['filipino-accounts-receivable-follow-up', 'How to plan Filipino accounts receivable follow-up', 'Define reminder queues, record updates, and escalation rules for overdue account follow-up.', 'accounts receivable follow-up'],
  ['filipino-employee-onboarding-coordinator', 'How to scope a Filipino employee onboarding coordinator', 'Turn forms, access requests, and first-week reminders into a reviewable onboarding workflow.', 'employee onboarding'],
  ['filipino-training-materials-assistant', 'How to plan Filipino training materials support', 'Build a controlled workflow for lesson drafts, file organization, and manager-approved updates.', 'training materials'],
  ['filipino-translation-project-coordinator', 'How to scope Filipino translation project coordination', 'Set source files, terminology checks, reviewer handoffs, and delivery rules before work begins.', 'translation coordination'],
  ['filipino-website-content-migration', 'A safe Filipino website content migration workflow', 'Use inventories, staging checks, redirects, and rollback ownership for routine content moves.', 'website content migration'],
  ['filipino-podcast-show-notes', 'How to plan Filipino podcast show notes support', 'Create a repeatable research and draft queue with fact checks and final editorial approval.', 'podcast show notes'],
  ['filipino-customer-feedback-analysis', 'How to scope Filipino customer feedback analysis', 'Turn feedback exports into coded themes, evidence samples, and a clear manager review.', 'customer feedback analysis'],
  ['filipino-returns-processing-workflow', 'How to plan Filipino ecommerce returns processing', 'Define intake checks, status updates, exception paths, and approvals for customer returns.', 'returns processing'],
  ['filipino-vendor-records-coordinator', 'How to scope Filipino vendor records coordination', 'Keep supplier records, renewal reminders, and missing documents organized with bounded access.', 'vendor records'],
  ['filipino-compliance-document-coordinator', 'How to plan Filipino compliance document coordination', 'Track evidence requests and document versions while leaving compliance judgments with the owner.', 'compliance documentation'],
  ['filipino-property-listing-coordinator', 'How to scope a Filipino property listing coordinator', 'Set listing intake, photo checks, update rules, and approval boundaries for property teams.', 'property listing coordination'],
  ['filipino-sales-operations-data-support', 'How to plan Filipino sales operations data support', 'Create a clean queue for pipeline updates, field checks, and exception escalation.', 'sales operations data'],
  ['filipino-product-research-assistant', 'How to scope Filipino product research support', 'Define research questions, source records, comparison fields, and evidence review.', 'product research'],
  ['filipino-community-management-assistant', 'How to plan Filipino community management support', 'Set moderation categories, response examples, escalation rules, and owner approvals.', 'community management'],
  ['filipino-document-control-assistant', 'How to scope a Filipino document control assistant', 'Manage file naming, version logs, and review queues without approving technical content.', 'document control'],
  ['filipino-event-coordination-assistant', 'How to plan Filipino event coordination support', 'Turn registrations, vendor follow-ups, and run-of-show updates into a controlled queue.', 'event coordination'],
  ['filipino-logistics-coordination-assistant', 'How to scope Filipino logistics coordination support', 'Define shipment records, status checks, exception handling, and handoffs to the operations owner.', 'logistics coordination'],
  ['filipino-executive-calendar-coordinator', 'How to plan Filipino executive calendar coordination', 'Create scheduling rules, meeting context, travel buffers, and escalation paths without taking decision ownership.', 'executive calendar coordination'],
  ['filipino-insurance-claims-data-support', 'How to scope Filipino insurance claims data support', 'Organize intake fields, document checks, status updates, and reviewer handoffs for claims operations.', 'insurance claims data'],
  ['filipino-legal-intake-coordinator', 'How to plan Filipino legal intake coordination', 'Build a bounded intake queue for matter details, conflict-check preparation, and attorney review.', 'legal intake coordination'],
  ['filipino-medical-billing-data-assistant', 'How to scope Filipino medical billing data support', 'Set up coding preparation, missing-field checks, payer queues, and billing-owner approvals.', 'medical billing data'],
  ['filipino-real-estate-transaction-coordinator', 'How to plan Filipino real estate transaction coordination', 'Track documents, deadlines, client updates, and exception handoffs across a property transaction.', 'real estate transaction coordination'],
  ['filipino-marketplace-operations-assistant', 'How to scope Filipino marketplace operations support', 'Define catalog checks, order exceptions, seller messages, and approval rules for marketplace work.', 'marketplace operations'],
  ['filipino-crm-data-cleanup-assistant', 'How to plan Filipino CRM data cleanup', 'Use field rules, duplicate checks, audit samples, and owner approvals to improve CRM records safely.', 'CRM data cleanup'],
  ['filipino-procurement-coordinator', 'How to scope Filipino procurement coordination', 'Organize request intake, quote comparisons, supplier records, and purchase approval boundaries.', 'procurement coordination'],
  ['filipino-payroll-preparation-assistant', 'How to plan Filipino payroll preparation support', 'Prepare timesheet checks and payroll inputs while keeping final payroll review and approval with the owner.', 'payroll preparation'],
  ['filipino-social-content-coordinator', 'How to scope Filipino social content coordination', 'Turn approved topics into a calendar, draft queue, asset checklist, and manager review process.', 'social content coordination'],
  ['filipino-webinar-operations-assistant', 'How to plan Filipino webinar operations support', 'Coordinate registrations, speaker assets, reminders, and post-event handoffs with clear approval points.', 'webinar operations'],
  ['filipino-quality-assurance-coordinator', 'How to scope Filipino quality assurance coordination', 'Create test queues, evidence capture rules, defect labels, and escalation paths for product checks.', 'quality assurance coordination'],
  ['filipino-customer-success-operations', 'How to plan Filipino customer success operations support', 'Maintain customer task queues, renewal signals, meeting notes, and manager-owned account decisions.', 'customer success operations'],
  ['filipino-grant-research-assistant', 'How to scope Filipino grant research support', 'Define search criteria, source logs, eligibility checks, and nonprofit review before any submission decision.', 'grant research'],
  ['filipino-donor-records-coordinator', 'How to plan Filipino nonprofit donor records support', 'Keep donor records, acknowledgments, missing details, and access boundaries organized for nonprofit teams.', 'donor records coordination'],
  ['filipino-construction-project-administrator', 'How to scope Filipino construction project administration', 'Coordinate submittal logs, meeting actions, document versions, and project-manager approvals.', 'construction project administration'],
  ['filipino-travel-booking-coordinator', 'How to plan Filipino business travel booking coordination', 'Set traveler preferences, approval rules, itinerary checks, and exception escalation before booking work begins.', 'business travel coordination'],
  ['filipino-interview-scheduling-coordinator', 'How to scope Filipino interview scheduling support', 'Manage candidate availability, interviewer calendars, reminders, and confidential escalation rules.', 'interview scheduling'],
  ['filipino-inventory-reconciliation-assistant', 'How to plan Filipino inventory reconciliation support', 'Compare records, flag variances, document evidence, and keep adjustment approval with the inventory owner.', 'inventory reconciliation'],
  ['filipino-knowledge-base-coordinator', 'How to scope Filipino knowledge base coordination', 'Maintain article inventories, feedback queues, version checks, and subject-matter review boundaries.', 'knowledge base coordination'],
  ['filipino-email-marketing-operations', 'How to plan Filipino email marketing operations support', 'Coordinate approved campaigns, audience checks, asset readiness, and send-review ownership.', 'email marketing operations'],
  ['filipino-financial-reporting-data-support', 'How to scope Filipino financial reporting data support', 'Prepare recurring report inputs, reconciliation notes, source links, and finance-owner review checkpoints.', 'financial reporting data'],
  ['filipino-supplier-onboarding-coordinator', 'How to plan Filipino supplier onboarding coordination', 'Track supplier forms, required records, system setup requests, and procurement approvals.', 'supplier onboarding'],
  ['filipino-project-status-reporting-assistant', 'How to scope Filipino project status reporting support', 'Collect updates, flag dependencies, maintain action logs, and keep project decisions with the manager.', 'project status reporting'],
  ['filipino-digital-asset-coordinator', 'How to plan Filipino digital asset coordination', 'Organize asset requests, naming rules, approvals, and delivery records for a repeatable creative queue.', 'digital asset coordination'],
] as const;

export const dailyBlogPosts = topics.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 9 }));

// Repair-owned publication evidence: each accepted route has an explicit source
// date field introduced by the date repair commit.
export const aug10PublicSourceDates: Record<string, string> = {
  'filipino-executive-calendar-coordinator': '2026-08-10',
  'filipino-insurance-claims-data-support': '2026-08-10',
  'filipino-legal-intake-coordinator': '2026-08-10',
  'filipino-medical-billing-data-assistant': '2026-08-10',
  'filipino-real-estate-transaction-coordinator': '2026-08-10',
  'filipino-marketplace-operations-assistant': '2026-08-10',
  'filipino-crm-data-cleanup-assistant': '2026-08-10',
  'filipino-procurement-coordinator': '2026-08-10',
  'filipino-payroll-preparation-assistant': '2026-08-10',
  'filipino-social-content-coordinator': '2026-08-10',
  'filipino-webinar-operations-assistant': '2026-08-10',
  'filipino-quality-assurance-coordinator': '2026-08-10',
  'filipino-customer-success-operations': '2026-08-10',
  'filipino-grant-research-assistant': '2026-08-10',
  'filipino-donor-records-coordinator': '2026-08-10',
  'filipino-construction-project-administrator': '2026-08-10',
  'filipino-travel-booking-coordinator': '2026-08-10',
  'filipino-interview-scheduling-coordinator': '2026-08-10',
  'filipino-inventory-reconciliation-assistant': '2026-08-10',
  'filipino-knowledge-base-coordinator': '2026-08-10',
  'filipino-email-marketing-operations': '2026-08-10',
  'filipino-financial-reporting-data-support': '2026-08-10',
  'filipino-supplier-onboarding-coordinator': '2026-08-10',
  'filipino-project-status-reporting-assistant': '2026-08-10',
  'filipino-digital-asset-coordinator': '2026-08-10',
};

export const dailyBlogDetails = Object.fromEntries(topics.map(([slug, title, excerpt, lane], index) => {
  const firstLink = index % 2 === 0 ? '/blog/Filipino-outsource-staffing-planning' : '/blog/Filipino-outsource-staffing-onboarding-checklist';
  const secondLink = index % 2 === 0 ? '/services/data-processing-support' : '/services/customer-support-operations';
  return [slug, {
    datePublished: aug10PublicSourceDates[slug], dateModified: aug10PublicSourceDates[slug],
    image: { src: '/blog-daily-2026-08-10.svg', alt: `Planning board for ${lane}`, caption: `A clear ${lane} brief keeps tasks, limits, and review visible.` },
    shortAnswer: `${title.replace(/^How to |^A practical |^A controlled /, '')} works best when the first queue is narrow, examples are current, access is limited, and a named manager reviews the launch.`,
    takeaways: ['Start with one repeatable queue.', 'Show normal work and an exception.', 'Keep sensitive approvals with a named manager.', 'Expand only after the first lane is stable.'],
    inlineAnchors: [
      { phrase: 'staffing plan', href: firstLink },
      { phrase: 'onboarding checklist', href: secondLink },
      { phrase: 'CISA multifactor authentication', href: 'https://www.cisa.gov/secure-our-world/require-multifactor-authentication', external: true },
    ],
    sections: [
      { title: 'Start with one queue', paragraphs: [`Define the finished result for ${lane} before discussing a broad job title. A useful staffing plan names the source, the output, the finish point, and the person who checks the work.`, `Use a small set of examples for ${lane}: one normal item, one incomplete item, and one case that must stop for approval. Link the onboarding checklist so the first handoff is documented.`] },
      { title: 'Write the stop rules', paragraphs: ['Stop rules should cover unusual customer requests, payments, policy changes, access changes, legal questions, and records that need special handling. The worker should know when to pause and who can decide.', 'Keep judgment-heavy decisions with the business owner or named manager. A clear boundary lets the Filipino team member complete repeatable work without guessing.'] },
      { title: 'Prepare access and review', paragraphs: ['Give only the systems needed for the first queue. Use named accounts, a password manager, and CISA multifactor authentication guidance. Record the permission owner and same-day removal step.', 'Review a small sample each day at launch. Write corrections into the process so the next batch improves without requiring a longer meeting.'] },
      { title: 'Measure the handoff', paragraphs: [`Track completed items, accuracy, exceptions, response time, and manager corrections for ${lane}. These measures are planning signals, not promised service levels.`, 'If the same question appears twice, improve the example or stop rule. Do not add a second queue until the first one is easy to explain and inspect.'] },
      { title: 'Expand carefully', paragraphs: ['Add work only when the first lane is accurate, the reviewer can describe the standard, and access remains appropriate. New work should receive its own examples and approval boundaries.', 'Keep a written weekly summary of completed work, blocked items, decisions needed, and process changes. That record supports continuity and replacement planning.'] },
      { title: 'Final readiness check', paragraphs: ['Before live work begins, ask a manager who did not write the brief to explain the role back in plain language. Confusion identifies missing examples or unclear ownership.', 'A ready role states what starts first, what good work looks like, when to stop, which tools are allowed, and who owns the final decision.'] },
    ],
    metrics: { title: 'A small launch scorecard', intro: 'Use these fields to keep the first handoff reviewable.', items: [{ value: '1', label: 'first queue', note: 'One recurring lane.' }, { value: '3+', label: 'examples', note: 'Normal, incomplete, and stop-rule cases.' }, { value: '1', label: 'reviewer', note: 'A named manager checks launch work.' }, { value: '0', label: 'shared logins', note: 'Use named access.' }], note: 'Adjust the review pace for work involving sensitive records or high-impact decisions.' },
    comparisonTitle: 'Loose scope versus useful scope',
    comparison: [{ question: 'What starts first?', weak: 'Anything that needs help.', useful: 'One queue with examples and a finish point.' }, { question: 'Who approves exceptions?', weak: 'The assistant decides.', useful: 'A named manager owns stop-rule decisions.' }, { question: 'How is quality checked?', weak: 'A general status update.', useful: 'Samples, written corrections, and a review cadence.' }],
    sources: [{ name: 'CISA: Require multifactor authentication', url: 'https://www.cisa.gov/secure-our-world/require-multifactor-authentication', note: 'Account security guidance.' }],
    faqs: [{ question: 'How narrow should the first queue be?', answer: 'Narrow enough to explain with examples and inspect with a short review routine.' }, { question: 'When can the role expand?', answer: 'After the first queue is accurate, documented, and easy for the reviewer to check.' }, { question: 'Who owns sensitive decisions?', answer: 'A named business manager should approve exceptions, access changes, and commitments.' }],
    tags: [lane, 'Role brief', 'Philippines staffing'],
    related: [{ href: firstLink, label: 'Staffing plan' }, { href: secondLink, label: 'Service workflow' }, { href: '/blog/Filipino-outsource-staffing-onboarding-checklist', label: 'Launch checklist' }],
  }];
}));
