export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'executive-assistance', title: 'Executive Assistance', desc: 'Build a Philippines-based executive assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-support-operations', title: 'Customer Support Operations', desc: 'Build a Philippines-based customer support operations workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'bookkeeping-support', title: 'Bookkeeping Support', desc: 'Build a Philippines-based bookkeeping support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'recruitment-coordination', title: 'Recruitment Coordination', desc: 'Build a Philippines-based recruitment coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'digital-marketing-support', title: 'Digital Marketing Support', desc: 'Build a Philippines-based digital marketing support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'ecommerce-operations', title: 'Ecommerce Operations', desc: 'Build a Philippines-based ecommerce operations workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'sales-development-support', title: 'Sales Development Support', desc: 'Build a Philippines-based sales development support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'data-processing-support', title: 'Data Processing Support', desc: 'Build a Philippines-based data processing support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'property-management-support', title: 'Property Management Support', desc: 'Build a Philippines-based property management support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'healthcare-administration', title: 'Healthcare Administration', desc: 'Build a Philippines-based healthcare administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring business operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
