import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'National Privacy Commission — Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST — Security and Privacy Controls for Information Systems and Organizations',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'CISA — Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'Philippine Statistics Authority — Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = {slug:string;title:string;excerpt:string;cluster:string;question:string;settings:string;record:string;caseStudy:string;limitation:string;finding:string;labels:readonly [string,string,string]};
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-reopen-rate-measurement-research-2026',title:'What Does a Reopen Rate Actually Measure in Outsourced Queues?',excerpt:'A source-bounded study of reopened work, changed evidence, and the limits of treating every return as an error.',cluster:'Quality Measurement',question:'Can a reopen rate distinguish faulty preparation from later evidence, changed instructions, and an owner-requested revision?',settings:'billing cases, freight documents, warranty claims, and sponsorship fulfillment',record:'eligible closure, closure definition, reopen event, initiator, reason category, new evidence, instruction version, and final owner',caseStudy:'A billing case is complete under the approved checklist, then reopens when the customer supplies a contract amendment that was not in the original system.',limitation:'No production queue or provider was observed, so this study cannot estimate a typical reopen rate or compare worker performance.',finding:'A reopen count becomes interpretable only when its reason, later evidence, eligibility rule, and instruction version remain attached.',labels:['Reopens','New evidence','Error verdict']},
  {slug:'philippines-outsourcing-small-sample-review-research-2026',title:'How Much Can a Small Quality Sample Tell an Outsourcing Buyer?',excerpt:'Methodological research on what a short record review can reveal—and what it cannot establish about a larger queue.',cluster:'Review Design',question:'What claims are supportable after a buyer reviews a small set of outsourced records?',settings:'enrollment, menu data, submittal logs, and certificate tracking',record:'eligible population, selection rule, sample size, review period, pass definition, exception type, reviewer, and disagreement',caseStudy:'A manager reviews ten recently completed records, all from one quiet shift, and wants to describe the result as the monthly accuracy rate.',limitation:'The designed examples do not produce a statistically representative estimate, confidence interval, or vendor benchmark.',finding:'A small review can test whether instructions are usable and surface failure modes, but it cannot by itself establish a stable performance rate.',labels:['Records read','Selection rule','Population claim']},
  {slug:'philippines-outsourcing-source-system-conflict-research-2026',title:'When Two Source Systems Disagree in Outsourced Operations',excerpt:'Qualitative research on preserving conflicting system evidence without asking coordinators to invent a source hierarchy.',cluster:'Data Governance',question:'What minimum record supports a safe handoff when approved systems show different values?',settings:'laboratory accessioning, donor restrictions, freight records, and field service claims',record:'entity, field, value from each system, retrieval time, system owner, freshness signal, downstream action, and decision owner',caseStudy:'A sample request and courier manifest agree on the identifier but show different collection times, with no written rule naming the controlling source.',limitation:'The examples do not determine which system is legally, clinically, financially, or operationally authoritative in a real organization.',finding:'A coordinator should preserve both values and their retrieval context; the client must define or decide source authority.',labels:['Systems','Conflicts','Authority decision']},
  {slug:'philippines-outsourcing-queue-exclusion-research-2026',title:'Why Queue Exclusions Need Their Own Audit Trail',excerpt:'A desk study of how undocumented exclusions can make outsourced completion and quality rates look stronger than the underlying workload.',cluster:'Reporting Controls',question:'Which fields let a reviewer understand why an item left the eligible population?',settings:'compliance calendars, warranty work, grant reporting, and insurance records',record:'item, original eligibility, exclusion event, reason, evidence, actor, approval requirement, period, and reinstatement state',caseStudy:'Incomplete grant files are removed from a weekly denominator while the report still describes the result as the completion rate for received files.',limitation:'This conceptual analysis does not estimate the frequency or financial effect of exclusion practices in any provider or country.',finding:'An exclusion is part of the measurement record, not housekeeping; it needs a reason, evidence, effective time, and stated effect on the denominator.',labels:['Eligible items','Exclusions','Rate claim']},
  {slug:'philippines-outsourcing-instruction-version-lag-research-2026',title:'How Instruction Version Lag Creates Avoidable Remote-Work Errors',excerpt:'Research on recording when revised instructions reached a queue, reviewer, and shift before attributing an error.',cluster:'Process Research',question:'How can a buyer separate failure to follow an instruction from failure to distribute the current version?',settings:'restaurant menus, training enrollment, franchise calendars, and construction submittals',record:'instruction identifier, version, approval time, publication time, recipient, acknowledgement, first applicable item, and superseded version',caseStudy:'A menu coordinator applies Monday’s approved price file on Tuesday morning, but the replacement file was posted only in a manager’s private chat overnight.',limitation:'The hypothetical cases do not establish an optimal acknowledgement window or show causal effects on real teams.',finding:'A version-related error claim needs evidence that the current instruction was approved, available, applicable, and received before the item was handled.',labels:['Versions','Receipt events','Error claim']},
];

function makeStudy(s: Study): ResearchPost {
  const [first,second,third]=s.labels;
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:'September 9, 2026',datePublished:'2026-09-09',dateModified:'2026-09-09',readTime:'11 minute read',cluster:s.cluster,cardHighlight:s.finding,
    keyTakeaways:[s.finding,'Every rate needs an eligible population, time window, exclusions, and definition version.','Source facts, coordinator labels, inferences, and client decisions should remain separate.'],
    stats:[{label:first,value:'5',width:76},{label:second,value:'1',width:42},{label:third,value:'0',width:18}],graphicCaption:`The method separates ${first.toLowerCase()}, ${second.toLowerCase()}, and the limits of an ${third.toLowerCase()}.`,heroImage:'/images/research-2026-08-21-source-attribution.png',
    sections:[
      {heading:'Research question and scope',paragraphs:[s.question,`This desk analysis uses ${s.settings} as bounded examples. It examines records a coordinator can preserve before an authorized client owner acts. It does not assess a provider, workforce, or business result.`]},
      {heading:'Methodology and evidence',paragraphs:[`We applied four public sources to five hypothetical records. Philippine privacy principles informed purpose, proportionality, accuracy, and security; NIST audit guidance informed event records and accountability; CISA informed named-account safeguards; and PSA technical notes informed definitions, coverage, and reference periods. Applying those sources to outsourced queue design is FilipinoOutsource.com analysis, not a requirement stated by the publishers.`,`For each example we separated source facts, coordinator classification, owner decision, and later outcome. The proposed minimum record was: ${s.record}. A second reading tested whether another reviewer could reconstruct the state from approved evidence.`]},
      {heading:'Finding and inference limits',paragraphs:[`${s.finding} A count does not establish cause. It must travel with the eligible population, observation period, exclusions, and written definition used at that time.`,`Coordinators may maintain records and flag client-defined conditions. Staffing, access, policy, compliance, payment, safety, clinical, or commercial decisions remain with authorized owners. The examples support process design, not judgments about individual workers.`]},
      {heading:'Boundary case',paragraphs:[s.caseStudy,`The defensible handoff preserves the original record and later evidence, identifies what changed, and names the paused action. Quietly replacing the first state would make the history easier to read but harder to audit.`]},
      {heading:'A small validation routine',paragraphs:[`Start with five consecutive eligible items and one deliberately selected exception. Ask a second reviewer to locate the sources, apply the written definitions, identify the waiting owner, and reproduce each state. Record disagreement rather than resolving it from memory.`,`If reviewers interpret a category differently, revise its inclusion and exclusion examples, assign an effective date, and retain the superseded version. Earlier periods should not be silently restated.`]},
      {heading:'Limitations and conclusion',paragraphs:[s.limitation,`The narrow conclusion is that ${s.finding.toLowerCase()} Buyers should validate the fields against their own systems, owners, data classes, contractual duties, and professional requirements before scaling.`,`This is qualitative workflow research, not legal, accounting, clinical, employment, security, safety, or statistical advice. No country, vendor, worker, or outcome comparison was conducted.`]},
    ],
    methodology:`Qualitative desk analysis applying official Philippine privacy guidance, NIST audit-control guidance, CISA account-security guidance, and PSA technical-note practices to five hypothetical ${s.cluster.toLowerCase()} records. Scope was limited to observable workflow evidence; no live provider, worker, customer, or outcome data was collected. Inferences were reviewed only for internal reconstructability.`,
    faq:[{q:'Does this study establish a benchmark?',a:'No. It proposes observable fields and interpretation limits for a buyer to test in its own queue.'},{q:'Can a coordinator make the underlying decision?',a:'A coordinator can document and route evidence; an authorized client owner makes consequential decisions.'},{q:'What is the smallest useful test?',a:'Review five consecutive eligible items and one exception against original sources with a second reviewer.'}],sources,related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Review the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]};
}

export const september9ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
