import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST: Digital Identity Guidelines, Authentication and Lifecycle Management',url:'https://pages.nist.gov/800-63-4/sp800-63b.html'},
  {name:'CISA: Logging Made Easy',url:'https://www.cisa.gov/resources-tools/services/logging-made-easy'},
  {name:'Philippine Statistics Authority: Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = {slug:string;title:string;excerpt:string;cluster:string;question:string;contexts:string;fields:string;caseStudy:string;limitation:string;finding:string;labels:readonly [string,string,string]};
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-approval-wait-time-research-2026',title:'What Approval Wait Time Reveals in Outsourced Operations',excerpt:'A bounded method for separating completed preparation from time spent waiting on an authorized client decision.',cluster:'Operations Measurement',question:'How can a buyer measure approval wait time without treating every pause as coordinator delay?',contexts:'access requests, rebate claims, lease renewals, chargeback cases, and maintenance exceptions',fields:'eligible item, ready-for-review event, approving owner, decision request, response event, returned-for-evidence event, paused intervals, and final state',caseStudy:'A chargeback packet is ready on Monday, the payment owner asks for one additional carrier record on Wednesday, and the assistant supplies it that afternoon before approval on Friday.',limitation:'No live queue was observed. The examples cannot establish a normal approval time, a service level, or the cause of delay in a real team.',finding:'Approval wait time is interpretable only when readiness, owner questions, evidence returns, and excluded pauses are separate events.',labels:['Ready packets','Owner events','Delay verdict']},
  {slug:'philippines-outsourcing-evidence-freshness-research-2026',title:'How Evidence Freshness Changes an Outsourced Work Queue',excerpt:'Qualitative research on timestamps, validity windows, and the boundary between checking freshness and deciding sufficiency.',cluster:'Evidence Controls',question:'Which fields let a reviewer tell whether evidence was current when an outsourced record was prepared?',contexts:'insurance certificates, user access, fleet service, supplier programs, and property agreements',fields:'evidence identity, issuing source, retrieval time, stated effective date, stated expiry date, applicable event, replacement source, freshness rule version, and decision owner',caseStudy:'A supplier certificate was valid when downloaded, expired before contract review, and was replaced after the assistant completed the original packet.',limitation:'The study does not determine legal validity, coverage adequacy, required retention, or the correct freshness period for any organization.',finding:'Freshness needs an event-relative rule; a document can be current at collection and stale when an owner acts.',labels:['Sources','Time points','Validity ruling']},
  {slug:'philippines-outsourcing-correction-log-research-2026',title:'Can a Correction Log Distinguish Cleanup From Concealment?',excerpt:'A source-based study of retaining former values, reasons, and actors when remote operations records change.',cluster:'Auditability',question:'What minimum history allows a second reviewer to reconstruct a corrected outsourced record?',contexts:'utility bills, mortgage intake, clinical site files, manufacturing changes, and legal hold tracking',fields:'record identity, field, former value, corrected value, source for each value, change reason, actor, event time, instruction version, and downstream notification',caseStudy:'An assistant corrects a meter number after receiving a clearer image, but the billing exception had already been routed using the first number.',limitation:'The hypothetical records cannot show whether any correction was lawful, material, fraudulent, or sufficient under a sector-specific rule.',finding:'A usable correction log preserves both states and the handoff effect instead of presenting the latest value as if it had always been known.',labels:['Changed fields','Source links','Intent claim']},
  {slug:'philippines-outsourcing-escalation-specificity-research-2026',title:'Does a More Specific Escalation Produce a Better Handoff?',excerpt:'A desk study of questions, cited conflicts, and paused actions in outsourced exception routing.',cluster:'Handoff Design',question:'Which observable features make an escalation answerable without transferring the decision to the coordinator?',contexts:'veterinary referrals, advertising trafficking, lease records, SaaS access, and rebate cases',fields:'item, governing instruction, source conflict, missing evidence, already completed steps, paused action, named owner, focused question, sent time, and response',caseStudy:'Instead of asking whether an access request looks acceptable, an assistant cites the approved role matrix and asks whether one named administrator permission is authorized for the requester.',limitation:'The method does not test response speed, decision quality, or worker performance, and it does not prove that specificity causes a better outcome.',finding:'An answerable escalation names the evidence conflict, the stopped action, the decision owner, and one question within that owner’s authority.',labels:['Source facts','Focused question','Outcome claim']},
  {slug:'philippines-outsourcing-consecutive-case-review-research-2026',title:'Why Consecutive Case Review Matters in an Outsourcing Pilot',excerpt:'Methodological research on selection transparency when a manager checks a small run of completed and exceptional work.',cluster:'Review Design',question:'What does reviewing consecutive eligible cases add to an early outsourcing pilot?',contexts:'document intake, creative trafficking, fleet records, site files, and billing exceptions',fields:'population rule, start event, end event, case order, inclusion state, exclusion reason, instruction version, reviewer result, disagreement, and correction',caseStudy:'A pilot presents five polished examples chosen by the coordinator, while three incomplete cases received in the same period remain outside the review set.',limitation:'A short consecutive review is still not a representative performance estimate and cannot supply a benchmark, confidence interval, or causal conclusion.',finding:'Consecutive selection makes omissions and exception mix easier to see, but the result remains a diagnostic review of one defined run.',labels:['Eligible cases','Exclusions','Performance rate']},
];

function makeStudy(s: Study): ResearchPost {
  const [first,second,third]=s.labels;
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:'September 10, 2026',datePublished:'2026-09-10',dateModified:'2026-09-10',readTime:'11 minute read',cluster:s.cluster,cardHighlight:s.finding,
    keyTakeaways:[s.finding,'Definitions, source timestamps, exclusions, and instruction versions must accompany any count.','Observable facts, coordinator labels, analyst inferences, and owner decisions are different evidence classes.'],
    stats:[{label:first,value:'5',width:74},{label:second,value:'2',width:46},{label:third,value:'0',width:16}],graphicCaption:`The framework records ${first.toLowerCase()} and ${second.toLowerCase()} while withholding an unsupported ${third.toLowerCase()}.`,heroImage:'/images/research-2026-08-21-source-attribution.png',
    sections:[
      {heading:'Research question and scope',paragraphs:[s.question,`This qualitative desk study uses ${s.contexts} as designed examples. Its scope is the observable record between task preparation and an authorized owner decision. It does not evaluate a staffing provider, country, worker, or business result.`]},
      {heading:'Methodology and source use',paragraphs:[`We applied four primary public sources to five hypothetical records. Philippine privacy law informed purpose limitation, proportionality, accuracy, and security. NIST identity guidance informed account lifecycle evidence. CISA logging guidance informed event capture. PSA technical notes informed definitions, reference periods, and coverage statements. The workflow application is FilipinoOutsource.com analysis, not a rule published by those institutions.`,`Each record was read twice using this proposed field set: ${s.fields}. The second reading asked whether a reviewer could reproduce the recorded state without private messages or an unstated source hierarchy.`]},
      {heading:'Finding and inference boundary',paragraphs:[`${s.finding} The finding concerns record design. It does not show that a particular event caused a delay, error, saving, compliance result, or customer outcome.`,`An assistant can retrieve approved evidence, record events, apply client-defined labels, and route an exception. Access, financial, clinical, legal, safety, employment, regulatory, and commercial decisions stay with authorized owners.`]},
      {heading:'Boundary case',paragraphs:[s.caseStudy,`The reviewable response keeps the original state, later evidence, event times, and paused action. It does not rewrite the earlier record merely because the later state is clearer.`]},
      {heading:'A limited validation routine',paragraphs:[`Select five consecutive eligible records from a declared start event, plus every exclusion encountered before the fifth completion. A second reviewer should locate each source, reconstruct the timeline, apply the written rule, and name the waiting owner.`,`Record disagreement as a result. If the reviewers use different definitions, revise the instruction with inclusion and exclusion examples, give it an effective time, and retain the old version for earlier records.`]},
      {heading:'Limitations and conclusion',paragraphs:[s.limitation,`The supported conclusion is narrow: ${s.finding.toLowerCase()} A buyer must validate fields, retention, access, definitions, owners, and sector obligations in its own environment before increasing volume.`,`This article is workflow research, not legal, financial, statistical, security, clinical, employment, or compliance advice. No live personal data, customer records, production systems, vendors, or workers were studied.`]},
    ],
    methodology:`Qualitative desk analysis of five designed ${s.cluster.toLowerCase()} records. FilipinoOutsource.com applied primary guidance from the Philippine National Privacy Commission, NIST, CISA, and the Philippine Statistics Authority. The study separated source facts, administrative labels, analyst inferences, and owner decisions. It collected no live provider, worker, client, customer, or outcome data and makes no benchmark or causal claim.`,
    faq:[{q:'Does this research establish a performance benchmark?',a:'No. It proposes observable fields and a small validation method for a buyer to test in its own queue.'},{q:'What may a coordinator decide?',a:'A coordinator may apply written administrative labels and route evidence. Authorized owners retain consequential decisions.'},{q:'What is the smallest review described here?',a:'Five consecutive eligible records, every intervening exclusion, and a second reviewer using the same dated instructions.'}],sources,related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Review the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]};
}

export const september10ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
