import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'National Privacy Commission — Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST SP 800-53 Rev. 5 — Audit and Accountability',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'CISA — Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'Philippine Statistics Authority — Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = {slug:string;title:string;excerpt:string;cluster:string;question:string;settings:string;record:string;caseStudy:string;limitation:string;finding:string;labels:readonly [string,string,string]};
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-owner-wait-time-research-2026',title:'Should Owner-Wait Time Be Separated in Outsourced Queue Reporting?',excerpt:'A source-bounded study of distinguishing preparation time from time paused for an authorized client decision.',cluster:'Operations Measurement',question:'Can an operations report separate coordinator work from time awaiting a client owner without implying blame?',settings:'vendor changes, account disputes, access reviews, and contract renewals',record:'eligible item, ready-for-owner timestamp, owner role, question asked, response timestamp, source refresh, restart timestamp, and closure reason',caseStudy:'A complete vendor-change packet waits two days for finance review, then new bank evidence restarts the verification step.',limitation:'No live workforce or provider queue was observed, so the study does not estimate typical response times or productivity.',finding:'Owner-wait time is interpretable only when readiness, later evidence, and restart events remain visible and separately defined.',labels:['Queue events','Owner pause','Productivity claim']},
  {slug:'philippines-outsourcing-correction-traceability-research-2026',title:'What Makes a Correction Traceable in Outsourced Record Work?',excerpt:'Qualitative research on preserving prior values, sources, and approvals when operational records are corrected.',cluster:'Quality Governance',question:'What minimum evidence lets a reviewer understand a correction without treating the newest value as the whole history?',settings:'customer-health registers, bid comparisons, work-order closeouts, and rights records',record:'record identifier, prior value, corrected value, source for each, reason, requester, reviewer, timestamp, and downstream notification',caseStudy:'A facilities closeout photo is attached to the wrong site, then replaced without a note after an invoice review begins.',limitation:'The hypothetical cases do not establish a universal retention period or satisfy industry-specific recordkeeping rules.',finding:'A correction is reproducible when the earlier state, new source, reason, actor, time, and affected handoffs remain linked.',labels:['Prior states','Source link','Accuracy verdict']},
  {slug:'philippines-outsourcing-exception-category-drift-research-2026',title:'How Can Exception Category Drift Distort Remote Operations Reports?',excerpt:'A desk study of definition drift when similar queue exceptions acquire different labels over time.',cluster:'Reporting Controls',question:'How can a team detect when an exception label changes meaning across reviewers, systems, or periods?',settings:'returns, referral routing, seller verification, license reviews, and receivables disputes',record:'label, written definition, inclusion example, exclusion example, reviewer, effective date, superseded version, and affected report period',caseStudy:'One reviewer labels a mismatched serial number as identity missing while another labels the same pattern as condition evidence incomplete.',limitation:'Five designed examples cannot estimate drift prevalence or compare teams, vendors, countries, or industries.',finding:'Trend counts become defensible only when category definitions, examples, effective dates, and disagreements travel with the report.',labels:['Definitions','Reviewer match','Trend claim']},
  {slug:'philippines-outsourcing-evidence-freshness-trigger-research-2026',title:'When Should Evidence Freshness Trigger a New Client Review?',excerpt:'Research on recording evidence age and change events without inventing a universal expiry rule.',cluster:'Evidence Operations',question:'What can an outsourced coordinator observe when evidence may be stale, and what must remain an owner decision?',settings:'seller documents, asset licenses, renewal files, vendor records, and training evidence',record:'evidence type, source, captured date, stated validity date, policy version, material change event, last review, and decision owner',caseStudy:'A supplier document has no printed expiry date, but the legal entity changed after it was collected.',limitation:'The cited sources do not specify freshness thresholds for these workflows; regulated and contractual requirements vary.',finding:'Freshness is a client-defined review trigger built from source dates, stated validity, and material change events—not age alone.',labels:['Source dates','Change event','Validity decision']},
  {slug:'philippines-outsourcing-denominator-change-research-2026',title:'Why Denominator Changes Matter in Outsourced Quality Metrics',excerpt:'A methodological study of preserving eligible-population definitions when reporting rates across periods.',cluster:'Process Research',question:'What record prevents a quality rate from silently comparing different eligible populations?',settings:'dispute files, bid packets, return reviews, referral records, and customer-success signals',record:'metric name, numerator event, eligible denominator, exclusions, period, system source, definition version, approver, and restatement choice',caseStudy:'A completeness rate improves after items waiting on customer documents are removed from the eligible queue.',limitation:'This conceptual analysis uses hypothetical records and does not establish any provider benchmark or causal effect.',finding:'A rate supports a period comparison only when denominator rules, exclusions, source systems, and definition changes are explicit.',labels:['Eligible items','Exclusions','Performance claim']},
];

function makeStudy(s: Study): ResearchPost {
  const [first,second,third]=s.labels;
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:'September 8, 2026',datePublished:'2026-09-08',dateModified:'2026-09-08',readTime:'11 minute read',cluster:s.cluster,cardHighlight:s.finding,
    keyTakeaways:[s.finding,'A useful measure names its event, population, observation window, exclusions, and owner.','Source facts, coordinator classifications, inferences, and business decisions should remain distinct.'],
    stats:[{label:first,value:'5',width:76},{label:second,value:'1',width:42},{label:third,value:'0',width:18}],graphicCaption:`The method separates ${first.toLowerCase()}, ${second.toLowerCase()}, and the limits of any ${third.toLowerCase()}.`,heroImage:'/images/research-2026-08-21-evidence-freshness.png',
    sections:[
      {heading:'Research question and scope',paragraphs:[s.question,`The desk analysis uses ${s.settings} as bounded examples. It examines records a coordinator can preserve before an authorized client owner acts. It does not transfer approval authority or treat a workflow measure as a promise of business performance.`]},
      {heading:'Methodology and sources',paragraphs:[`We applied four public sources to five hypothetical records. Philippine privacy principles informed purpose, proportionality, accuracy, and security; NIST audit guidance informed event and accountability records; CISA informed named-account safeguards; and PSA technical notes informed definitions and reference periods. Their application here is FilipinoOutsource.com analysis, not a requirement stated by those sources.`,`For each example we separated source facts, coordinator labels, owner decisions, and later outcomes. The proposed minimum record was: ${s.record}. A second reading tested whether another reviewer could reconstruct the state without private explanation.`]},
      {heading:'Finding and inference limits',paragraphs:[`${s.finding} Counts alone do not establish cause. Every figure needs an eligible population, observation period, exclusions, and the instruction version used during that period.`,`A coordinator may maintain the record and flag a client-defined condition. Decisions about staffing, access, policy, compliance, payment, or customer treatment remain with an authorized owner. The examples support process design, not judgments about a worker or provider.`]},
      {heading:'Boundary case',paragraphs:[s.caseStudy,`The defensible handoff preserves the original state and the later evidence, identifies what changed, and names the paused action. Replacing the first record would make the timeline look cleaner while removing review context.`]},
      {heading:'Practical test routine',paragraphs:[`Start with five consecutive eligible items and one intentionally selected exception. Have a second reviewer locate the sources, apply the written definitions, identify the waiting owner, and reproduce the final state. Record disagreement instead of forcing agreement after the fact.`,`If reviewers use a category differently, revise its inclusion and exclusion examples, assign an effective date, and retain the superseded version. Do not recalculate earlier periods silently.`]},
      {heading:'Limitations and conclusion',paragraphs:[s.limitation,`This research supports a narrow conclusion: ${s.finding.toLowerCase()} A buyer should validate the proposed fields with its own systems, owners, data classes, and review obligations before scaling the routine.`,`Legal, accounting, clinical, employment, security, safety, and commercial determinations require the appropriate client owner or qualified professional. Nothing in this study is a country, provider, or worker comparison.`]},
    ],
    methodology:`Qualitative desk analysis applying official Philippine privacy guidance, NIST audit-control guidance, CISA account-security guidance, and PSA technical-note practices to five hypothetical ${s.cluster.toLowerCase()} records. No provider, worker, customer, or business outcome was measured.`,
    faq:[{q:'Does this study set a performance benchmark?',a:'No. It proposes observable fields and interpretation limits for a buyer to test in its own queue.'},{q:'Can a coordinator make the underlying decision?',a:'The coordinator can document and route evidence; the authorized client owner makes consequential decisions.'},{q:'What is the smallest useful validation?',a:'Review five eligible items and one exception against original sources with a second reviewer.'}],sources,related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Review the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]};
}

export const september8ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
