import type { ResearchPost } from './fleet-data';

type Study = {
  slug:string; title:string; cluster:string; question:string; finding:string; caseStudy:string;
  sourceName:string; sourceUrl:string; sourceScope:string; limitations:string; fields:string[];
};

const studies: readonly Study[] = [
  { slug:'philippines-outsourcing-personal-data-correction-workflow-research-2026', title:'Philippines Outsourcing Personal-Data Correction Workflow Research 2026', cluster:'Privacy Operations', question:'How can a remote support queue prepare a personal-data correction request without deciding identity, disclosure, or the authoritative value?', finding:'NPC materials support a workflow that records purpose, source, access, modification history, and owner decisions instead of treating a requested value as automatically correct.', caseStudy:'A customer asks to replace an address, but the requested value conflicts with a controlled transaction record and the identity check is still pending.', sourceName:'National Privacy Commission: Data Privacy Act', sourceUrl:'https://privacy.gov.ph/data-privacy-act/', sourceScope:'Philippine privacy principles for personal-information processing; it does not determine a specific company’s lawful basis or resolve an individual request.', limitations:'This is an operating analysis, not legal advice. The public sources do not reveal a buyer’s systems, notices, retention duties, or jurisdictional obligations.', fields:['request as received','identity-check status','field and record locations','source provenance','authorized decision','change confirmation'] },
  { slug:'philippines-remote-support-source-access-register-research-2026', title:'Philippines Remote Support Source-Access Register Research 2026', cluster:'Access Governance', question:'What evidence should a buyer retain when a Philippines-based support role receives access to customer or business records?', finding:'NPC rules emphasize necessary processing, defined duties, access management, monitoring, and records of processing. A practical access register therefore needs purpose and removal evidence, not only a username.', caseStudy:'A worker needs a reporting dashboard for one queue, but the available role also permits exports and access to unrelated customer fields.', sourceName:'National Privacy Commission: Data Privacy Act IRR', sourceUrl:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/', sourceScope:'Philippine privacy and security obligations concerning personal-data processing; it is not a universal cybersecurity certification standard.', limitations:'The analysis does not test technical controls or establish compliance. Appropriate access depends on the actual data, purpose, systems, contract, and owner review.', fields:['system and account','declared purpose','permission level','approving owner','review date','removal confirmation'] },
  { slug:'philippines-ecommerce-return-evidence-workflow-research-2026', title:'Philippines Ecommerce Return-Evidence Workflow Research 2026', cluster:'Ecommerce Operations', question:'How should a support team prepare online return evidence while consumer remedy decisions stay with the merchant’s authorized owner?', finding:'DTI materials make return policies, transaction records, and complaint channels relevant, but they do not authorize a coordinator to decide a refund from an incomplete packet.', caseStudy:'A returned item arrives with a different serial number from the authorization, while the customer reports that the package was never opened.', sourceName:'DTI Ecommerce consumer FAQs', sourceUrl:'https://ecommerce.dti.gov.ph/faqs/', sourceScope:'Public Philippine consumer information and complaint guidance; it does not adjudicate the hypothetical return or replace applicable policy and legal review.', limitations:'The study does not determine consumer rights for a specific transaction, product, platform, or jurisdiction. Merchant records may be incomplete or use different terminology.', fields:['order and authorization','customer statement','carrier events','condition evidence','policy version','owner remedy decision'] },
  { slug:'philippines-services-workforce-role-design-boundaries-research-2026', title:'Philippines Services Workforce Role-Design Boundaries Research 2026', cluster:'Philippines Market Data', question:'What can current labor-force statistics tell a buyer about designing a Philippines-based support role, and what can they not prove?', finding:'PSA reported that services represented 63.0% of employed persons in March 2026. That describes national workforce composition, not the readiness or performance of an individual worker or outsourced workflow.', caseStudy:'A buyer sees a large services workforce and assumes a broad “operations assistant” role needs no examples, access plan, or daily reviewer.', sourceName:'Philippine Statistics Authority: March 2026 Labor Force Survey', sourceUrl:'https://psa.gov.ph/system/files/iesd/Press-Release-for-March-2026-LFS.pdf', sourceScope:'A nationwide household survey describing employment at the stated reference period; it does not measure outsourcing providers or predict a hiring result.', limitations:'Preliminary survey estimates have sampling and non-sampling limits. Sector share does not reveal role-specific skill, connectivity, schedule fit, quality, or availability.', fields:['survey period','population and estimate','sector definition','role output','workflow evidence','manager decision'] },
  { slug:'philippines-consumer-complaint-handoff-evidence-research-2026', title:'Philippines Consumer Complaint Handoff Evidence Research 2026', cluster:'Customer Support', question:'Which evidence distinctions help a remote support coordinator prepare a consumer complaint without turning an allegation into a finding?', finding:'DTI complaint channels show the value of a documented digital handoff. The safer operating model separates the customer’s statement, observed records, missing evidence, requested remedy, and owner decision.', caseStudy:'A customer reports an unauthorized charge through three channels, producing duplicate tickets with conflicting timestamps and different requested remedies.', sourceName:'DTI Consumer Complaints Assistance and Resolution System', sourceUrl:'https://consumercare.dti.gov.ph/', sourceScope:'Information about the Philippine consumer complaint and online resolution channel; it does not decide a private company complaint or prove fault.', limitations:'This qualitative workflow does not measure resolution outcomes or define a merchant’s legal response. Sensitive or high-impact cases may need legal, privacy, fraud, or safety review.', fields:['original customer wording','channel and timestamp','account evidence','duplicate relationship','requested remedy','authorized response'] },
];

function buildStudy(study: Study): ResearchPost {
  const sections = [
    { heading:'Research question and decision boundary', paragraphs:[study.question, `${study.finding} The research question is deliberately narrower than “can this work be outsourced?” It asks which evidence can be prepared repeatably and which conclusion remains with a client-side owner.`] },
    { heading:'Source scope and reading method', paragraphs:[`The anchor publication is ${study.sourceName}. Its scope is: ${study.sourceScope}`, `The method records the source publisher, publication or reference period, population or subject, definition used, and the claim the source can support. The operational interpretation is then labeled separately. A public authority can establish context without endorsing FilipinoOutsource.com or a particular staffing arrangement.`] },
    { heading:'Evidence fields for a reproducible handoff', paragraphs:[`The proposed record contains ${study.fields.join(', ')}. Each field carries a source location, checking time, and status so another reviewer can retrace the preparation.`, `A missing field remains missing; it does not become a negative finding. A reported statement remains attributed to its speaker. A calculation shows its inputs. An owner decision records the person and effective time. Those distinctions reduce false certainty when a queue crosses Philippine and client working hours.`], bullets:study.fields },
    { heading:'Applied case analysis', paragraphs:[study.caseStudy, `The coordinator first preserves the original records, then links duplicates, states the exact disagreement, and routes one focused question. The coordinator does not select the more convenient source, infer approval from silence, or communicate a consequential outcome. The client-side owner decides what governs and records that decision in the approved system.`] },
    { heading:'Sampling and measurement', paragraphs:[`A first-cycle review should include one ordinary item, one incomplete item, and the case above. For each sample, compare the written rule, source fields, access used, status, escalation, and reviewer correction.`, `Useful measures are items received, missing-source fields, conflicts, duplicates, returns, owner waits, and age of unresolved decisions. These describe preparation and queue condition. They do not prove accuracy, compliance, savings, response speed, customer satisfaction, worker quality, or a future business result.`] },
    { heading:'Limitations', paragraphs:[study.limitations, `The field list is a proposed operating control, not a claim that six fields are sufficient for every buyer. Public pages can move or change, definitions may differ across systems, and an official source can still be too broad for a company-specific conclusion. A qualified owner should review sensitive legal, privacy, security, financial, employment, health, or safety questions.`] },
    { heading:'Evidence-led conclusion', paragraphs:[`The evidence supports a bounded preparation role: collect approved sources, preserve disagreements, minimize access, and give the owner a reproducible question. It does not support transferring the owner’s judgment merely because the record is organized.`, `For FilipinoOutsource.com buyers, the practical test is whether a second reviewer can trace each consequential field and explain the stop rule without private context. If not, narrow the queue or improve the example before adding volume.`] },
  ];
  return {
    slug:study.slug,title:study.title,excerpt:`A source-backed analysis of ${study.question.charAt(0).toLowerCase()+study.question.slice(1)}`,
    published:'August 31, 2026',datePublished:'2026-08-31',readTime:'10 minute read',cluster:study.cluster,
    cardHighlight:study.finding,keyTakeaways:[study.finding,'Source facts, operating interpretation, and owner decisions should remain separate.','A normal, incomplete, and stop-case sample make the workflow testable.','Queue measures are not business-outcome claims.'],
    stats:[{label:'Evidence fields',value:String(study.fields.length),width:78},{label:'Review samples',value:'3',width:58},{label:'Decision owner',value:'1',width:38}],
    graphicCaption:`A bounded evidence model for ${study.title.replace(' Research 2026','').toLowerCase()}.`,sections,
    table:{heading:'Evidence-to-owner handoff',headers:['Stage','Record','Boundary'],rows:[['Intake',study.fields.slice(0,2).join(' and '),'Preserve source and wording'],['Preparation',study.fields.slice(2,4).join(' and '),'Label gaps and conflicts'],['Decision',study.fields.slice(4).join(' and '),'Named owner decides']]},
    methodology:`Qualitative source-scope analysis using ${study.sourceName} as the anchor publication. The method separates source claims from a proposed FilipinoOutsource.com workflow, applies the fields to one hypothetical exception, and states limitations. It does not measure provider performance or establish compliance.`,
    faq:[{q:'Does this research approve a specific workflow?',a:'No. It provides a source-backed preparation model; the buyer’s authorized owner must approve the actual workflow and access.'},{q:'Why use three samples?',a:'An ordinary, incomplete, and stop-case sample exposes gaps that a normal example alone may hide.'}],
    sources:[{name:study.sourceName,url:study.sourceUrl},{name:'National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'Philippine Statistics Authority: Labor Force Survey',url:'https://psa.gov.ph/statistics/labor-force-survey/index'}],
    related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Use the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'},{label:'Review data processing support',href:'/services/data-processing-support'}]
  };
}

export const august31ResearchPosts: readonly ResearchPost[] = studies.map(buildStudy);
