import type { ResearchPost } from './fleet-data';

const published = '2026-09-14' as const;
const sources = [
  {name:'National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST: Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/'},
  {name:'CISA: Logging Made Easy',url:'https://www.cisa.gov/resources-tools/services/logging-made-easy'},
  {name:'Philippine Statistics Authority: Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = { slug:string; title:string; excerpt:string; cluster:string; question:string; records:string; boundaryCase:string; finding:string; limitation:string; labels:readonly [string,string,string] };
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-source-conflict-research-2026',title:'How Source Conflicts Should Be Recorded in Outsourced Operations',excerpt:'A bounded desk study of competing records, retrieval times, and decision ownership in remote support queues.',cluster:'Evidence Controls',question:'Which fields let a second reviewer reconstruct a source conflict without relying on private context?',records:'source identity, retrieved time, stated effective time, field in conflict, prior action, paused action, owner, and final disposition',boundaryCase:'A shipment system says delivered while a customer correction and carrier image point to another address.',finding:'A conflict becomes reviewable when both source states and the consequential action held for an owner remain visible.',limitation:'Designed records cannot establish the frequency, cause, materiality, or legal effect of real source conflicts.',labels:['2 source states','1 paused action','No causal claim']},
  {slug:'philippines-outsourcing-access-removal-research-2026',title:'When Should Outsourced Access Removal Evidence Be Reviewed?',excerpt:'Qualitative research on named accounts, removal triggers, exceptions, and proof of completed access changes.',cluster:'Access Governance',question:'What record is needed to verify that access was reviewed and removed after a role or assignment changed?',records:'person, named account, application, approved role, approver, trigger event, requested time, completion evidence, and exception owner',boundaryCase:'A contractor leaves a project, but still owns a shared automation and appears in a group inherited from another team.',finding:'Removal evidence is stronger when the trigger, request, system result, inherited access, and unresolved ownership are separate events.',limitation:'The study did not inspect a live identity provider and does not prove that any access control is sufficient or compliant.',labels:['Named accounts','Trigger events','Owner review']},
  {slug:'philippines-outsourcing-correction-history-research-2026',title:'Can Correction History Improve Outsourced Record Review?',excerpt:'A reconstruction study of former values, supporting sources, downstream handoffs, and reviewer disagreement.',cluster:'Auditability',question:'What correction history allows a reviewer to distinguish a documented cleanup from an unexplained overwrite?',records:'record ID, field, former value, corrected value, source for each state, actor, reason, event time, and downstream notification',boundaryCase:'A coordinator fixes a vendor identifier after a payment packet was already routed under the former value.',finding:'A usable correction record preserves the former state and its handoff effect instead of presenting the new value as always known.',limitation:'Hypothetical corrections cannot show intent, fraud, financial accuracy, compliance, or the adequacy of a real audit trail.',labels:['Former values','Source links','Handoff effects']},
  {slug:'philippines-outsourcing-consecutive-review-research-2026',title:'Why Consecutive Review Changes an Outsourcing Pilot',excerpt:'Methodological analysis of selection rules, exclusions, and reviewer disagreement in small operational samples.',cluster:'Review Design',question:'What does a consecutive-case rule reveal that a hand-picked showcase cannot?',records:'population rule, start event, case order, inclusion state, exclusion reason, instruction version, reviewer result, and correction',boundaryCase:'A pilot presents five polished cases while two incomplete records and one system outage between them are omitted.',finding:'Consecutive review exposes exclusions and exceptions that disappear when examples are selected after outcomes are known.',limitation:'Five designed cases are not a statistical sample and cannot establish error rates, service levels, or provider performance.',labels:['Declared start','All exclusions','No benchmark']},
  {slug:'philippines-outsourcing-escalation-record-research-2026',title:'What Makes an Outsourced Escalation Answerable?',excerpt:'A desk analysis of cited evidence, stopped actions, focused questions, and accountable decision owners.',cluster:'Handoff Design',question:'Which observable features help an authorized owner answer an escalation without transferring the decision to a coordinator?',records:'item, instruction version, source conflict, completed step, stopped action, owner, focused question, sent time, response, and disposition',boundaryCase:'An access request asks for administrator rights not listed in the approved role template, but the manager approval names only the application.',finding:'An answerable escalation names the conflict, the stopped action, one decision owner, and one question within that owner’s authority.',limitation:'The method does not measure response speed or decision quality and cannot show that specificity causes a better outcome.',labels:['Cited conflict','Focused question','Decision owner']},
];

function makeStudy(s: Study): ResearchPost {
  return {
    slug:s.slug, title:s.title, excerpt:s.excerpt, published:'Published September 14, 2026', datePublished:published, dateModified:published,
    readTime:'9 minute read', cluster:s.cluster, cardHighlight:s.finding,
    keyTakeaways:[s.finding,'Keep source facts separate from administrative labels and owner decisions.','Report exclusions and reviewer disagreement rather than hiding them.'],
    stats:[{label:s.labels[0],value:'Document',width:82},{label:s.labels[1],value:'Separate',width:68},{label:s.labels[2],value:'Respect',width:54}],
    graphicCaption:'A qualitative workflow model. Bar widths illustrate review emphasis and are not measured performance results.',
    sections:[
      {heading:'Research question and scope',paragraphs:[s.question,`This study examines designed Filipino outsourcing workflow records containing ${s.records}. It tests whether a second reviewer can reconstruct the administrative state without private messages.`]},
      {heading:'Source framework',paragraphs:[`National Privacy Commission guidance informed purpose limitation, proportionality, accuracy, and security. NIST informed identity and access lifecycle concepts; CISA informed event logging; PSA technical notes informed definitions and reference periods.`,`Those institutions did not evaluate FilipinoOutsource.com or endorse this workflow. Their publications are source frameworks; the operational application is our analysis.`]},
      {heading:'Record-reading method',paragraphs:[`Five designed records were read in their original order, including incomplete and conflicting cases. The field set was ${s.records}.`,`The first reading separated source facts from client-defined labels. The second asked whether another reviewer could reproduce the timeline, identify the paused action, and locate the accountable owner.`]},
      {heading:'Boundary case',paragraphs:[s.boundaryCase,'The reviewable response retains the earlier state, later evidence, retrieval times, and any downstream handoff. It does not silently rewrite history or decide which consequential outcome should follow.']},
      {heading:'Finding and decision boundary',paragraphs:[s.finding,'An assistant may retrieve approved evidence, record events, apply written labels, and route exceptions. Legal, financial, clinical, security, employment, safety, regulatory, and commercial decisions remain with authorized owners.']},
      {heading:'Limitations and validation',paragraphs:[s.limitation,'A buyer should test the field definitions, retention, access, reviewer agreement, and exception ownership in its own systems before increasing volume. No live workers, providers, clients, customers, or production outcomes were studied.']},
    ],
    methodology:`Qualitative desk analysis of five designed ${s.cluster.toLowerCase()} records. The fixed observation window was September 1 through September 14, 2026. Records were evaluated twice against a declared field set, with every incomplete record and exclusion retained. This was not a statistical sample; no live personal data, production systems, providers, workers, customers, or outcomes were observed, and no benchmark or causal claim is made.`,
    faq:[{q:'Does this study establish a performance benchmark?',a:'No. It proposes observable fields and a bounded validation method for a buyer to test.'},{q:'What may an assistant decide?',a:'An assistant may apply written administrative labels and route evidence; authorized owners retain consequential decisions.'},{q:'What was the observation window?',a:'The designed desk review covered September 1 through September 14, 2026.'}],
    sources,
    related:[{label:'Scope a controlled support queue',href:'/blog/filipino-customer-refund-evidence-assistant'},{label:'Review access-control workflow design',href:'/blog/filipino-employee-onboarding-access-assistant'}],
    heroImage:'/article-planning.svg',
  };
}

export const september14ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
