import type { ResearchPost } from './fleet-data';

const date = '2026-09-24' as const;
const checked = 'Accessed September 24, 2026';

type Topic = {
  slug: string; title: string; excerpt: string; cluster: string; subject: string; question: string;
  facts: readonly string[]; controls: readonly string[]; boundary: string; uncertainty: string;
  sources: readonly { name: string; url: string }[];
  service: { heading: string; copy: string; label: string; href: string };
  related: readonly { label: string; href: string }[];
};

const irr = { name: `National Privacy Commission — Implementing Rules and Regulations of the Data Privacy Act (${checked})`, url: 'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/' };
const security = { name: `National Privacy Commission — Circular 2023-06 security requirements overview (${checked})`, url: 'https://privacy.gov.ph/npc-issues-circulars-to-strengthen-personal-data-protection-in-ph/' };

const topics: readonly Topic[] = [
  {
    slug: 'philippines-outsourcing-data-subject-request-handoff-research-2026',
    title: 'How Should an Outsourced Team Handle a Data-Subject Request?',
    excerpt: 'A primary-source framework for receiving, authenticating, scoping, routing, fulfilling, and recording privacy-rights requests in a Philippines outsourcing workflow.',
    cluster: 'Privacy Operations', subject: 'data-subject request handoff',
    question: 'What may a Philippines-based support worker do when a person asks to access, correct, object to, erase, block, or receive a copy of personal data?',
    facts: [
      'The Data Privacy Act framework gives data subjects rights that include being informed, access, objection, rectification, erasure or blocking, damages, complaint, and data portability, subject to the law’s conditions and limitations.',
      'The NPC explains that personal information controllers and processors handling personal details are responsible for respecting data-subject rights, while some rights may be exercised by an authorized assignee or lawful heir.',
      'The implementing rules require notice about the controller, purpose, recipients, retention, rights, and complaint route, and describe circumstances in which an objection changes whether processing may continue.',
      'A support inbox can receive and organize a request, but the existence, scope, identity evidence, exemptions, third-party data, response content, and secure release method require decisions by the accountable controller and qualified owners.'
    ],
    controls: [
      'Create one request record with received time, channel, requester identity claimed, represented person, right asserted, systems named, requested period, exact wording, acknowledgement status, responsible controller, decision owner, due-date basis, and current state.',
      'Use an approved identity-check path proportionate to the requested data. Keep identity evidence separate from the response package, prevent the support worker from inventing extra questions, and provide a route for representatives, minors, or deceased persons.',
      'Search only approved systems and preserve system, query scope, custodian, result time, exclusions, conflicting identities, third-party information, and redaction questions. A blank result must record where the team looked rather than becoming an unsupported claim that no data exists.',
      'Require an authorized reviewer to decide scope, limitation, correction, deletion, retention conflict, objection, portability format, refusal, extension, and final wording. Log delivery channel, recipient check, release time, package identifier, and later correction without placing sensitive response data in an open ticket.'
    ],
    boundary: 'A customer writes “delete everything” in a support chat. The account also contains transaction records, another user’s messages, an unresolved dispute, and marketing preferences stored in a separate platform. The agent must preserve and route the request, not promise immediate deletion or silently close the account.',
    uncertainty: 'Applicable rights, response periods, identity checks, exceptions, retention duties, controller location, other jurisdictions, and acceptable delivery safeguards depend on the real request and records. This study is an operating framework, not a legal determination or a substitute for the controller’s privacy process.',
    sources: [{ name: `National Privacy Commission — Data Subject Rights (${checked})`, url: 'https://privacy.gov.ph/data-subject-rights/' }, { name: `National Privacy Commission — Advisory No. 2021-01, Data Subject Rights (${checked})`, url: 'https://privacy.gov.ph/pips-and-pics/advisories-circulars/' }, irr],
    service: { heading: 'Build a controlled request queue', copy: 'Use the customer support operations guide to define intake language, authentication handoffs, system searches, approval ownership, and secure release before requests arrive.', label: 'Review customer support operations', href: '/services/customer-support-operations' },
    related: [{ label: 'Review data export coordination', href: '/research/philippines-data-export-request-coordination-research-2026' }, { label: 'Plan data processing support', href: '/services/data-processing-support' }]
  },
  {
    slug: 'philippines-outsourcing-privacy-impact-assessment-research-2026',
    title: 'When Does an Outsourced Workflow Need a Privacy Impact Assessment?',
    excerpt: 'A source-led method for screening a Philippines outsourcing workflow for privacy risk before granting access, moving data, adding tools, or changing purpose.',
    cluster: 'Privacy Operations', subject: 'privacy-impact-assessment readiness',
    question: 'What evidence should a buyer assemble before an accountable privacy owner decides whether and how to assess a proposed outsourced workflow?',
    facts: [
      'NPC guidance describes a privacy impact assessment as a process for identifying potential privacy effects of a process, system, program, software, device, or other initiative that processes personal information and for treating identified risk.',
      'The NPC says assessment begins early enough to influence an initiative and continues through and after deployment; it is not a one-time document completed after design choices are fixed.',
      'Current NPC security guidance identifies privacy impact assessment and a privacy management program among the general obligations of controllers and processors and connects security to access, storage, continuity, training, and incident management.',
      'An outsourcing proposal changes the factual map when another organization, worker population, location, account, device, integration, or support channel can receive or influence personal data, even if the business purpose appears unchanged.'
    ],
    controls: [
      'Screen the initiative before access: purpose, accountable controller, processor and subprocessor roles, people affected, data elements, sensitive fields, sources, systems, locations, transfers, automated steps, decisions, recipients, retention, deletion, and incident route.',
      'Map the current state and proposed state separately. Record which party determines purpose and means, which party follows instructions, where data is copied or synchronized, who can export it, what audit evidence exists, and what happens during support, failure, and termination.',
      'Give the privacy owner concrete design choices rather than a generic approval request: narrower fields, redaction, synthetic training data, browser-only access, disabled exports, named accounts, shorter retention, separated duties, additional review, or no outsourcing for the high-risk step.',
      'Maintain a decision record with assessor, stakeholders consulted, risks, affected rights, likelihood and impact basis, chosen measures, residual risk owner, conditions, implementation evidence, review trigger, and closure. Reopen it when facts change rather than copying the former conclusion.'
    ],
    boundary: 'A buyer wants a remote coordinator to clean a customer spreadsheet. During scoping, the file is found to contain health notes, identity documents, children’s information, free-text complaints, and links to a new AI enrichment tool. “Spreadsheet cleanup” no longer describes the actual processing.',
    uncertainty: 'The required assessment depth, consultation, lawful basis, transfer safeguards, security controls, residual-risk acceptance, and whether processing should proceed depend on the actual parties, data, technology, consequences, and applicable laws. A completed template does not itself establish compliance or safety.',
    sources: [{ name: `National Privacy Commission — Five Pillars: Privacy Impact Assessment (${checked})`, url: 'https://privacy.gov.ph/5-pillars-of-compliance-2/' }, { name: `National Privacy Commission — Guidelines on Privacy Impact Assessment, Advisory 2017-03 (${checked})`, url: 'https://www.privacy.gov.ph/wp-content/uploads/2022/01/NPC_AdvisoryNo.2017-03.pdf' }, security],
    service: { heading: 'Map the data before staffing the task', copy: 'Use the data processing support guide to identify minimum fields, systems, access levels, reviewers, exceptions, and removal evidence for the proposed role.', label: 'Review data processing support', href: '/services/data-processing-support' },
    related: [{ label: 'Review BYOD controls', href: '/research/philippines-outsourcing-byod-controls-research-2026' }, { label: 'Review data processing support', href: '/services/data-processing-support' }]
  },
  {
    slug: 'philippines-outsourcing-dpo-escalation-design-research-2026',
    title: 'What Should an Outsourcing Workflow Escalate to a Data Protection Officer?',
    excerpt: 'A practical division of work between a Philippines-based operations team, the accountable business owner, and the organization’s data protection officer.',
    cluster: 'Privacy Operations', subject: 'data-protection-officer escalation design',
    question: 'How can a buyer involve its data protection officer without turning every routine ticket into a privacy decision or making support staff act as privacy counsel?',
    facts: [
      'The NPC states that appointing a data protection officer is a legal requirement for personal information controllers and processors under the Data Privacy Act and that the DPO remains the organization’s contact with the Commission.',
      'NPC accountability guidance places privacy governance with the organization, including policies, assessment, security, training, rights, breach management, and demonstrable compliance rather than with whichever worker first encounters a record.',
      'Current security guidance calls for designation and registration of a DPO, privacy impact assessment, privacy management, personnel training, and compliance with NPC orders as part of controller and processor obligations.',
      'A DPO contact field is useful only if the workflow distinguishes urgent incidents, rights requests, new processing, policy exceptions, routine operational corrections, and questions that belong to legal, security, HR, finance, or another owner.'
    ],
    controls: [
      'Publish an escalation map that names the DPO and backup, secure channel, expected acknowledgement, after-hours route, and categories: suspected incident, data-subject request, new vendor or tool, new data category or purpose, cross-border change, recurring policy conflict, complaint, and regulator contact.',
      'Require the operations handoff to state the record or system, observed fact, people affected, data involved, time discovered, evidence preserved, action already taken, action paused, instruction checked, urgency reason, and one focused question. Avoid copying sensitive data into a broad chat merely to obtain attention.',
      'Keep ownership explicit. Operations may preserve evidence and stop an unapproved action; security may contain a technical event; counsel may interpret law; HR may decide employment matters; the controller’s business owner may decide purpose. The DPO advises and monitors within the organization’s real governance model.',
      'Close the loop with a decision reference, conditions, effective time, implementer, verification evidence, communication owner, and next review. Trend repeated escalations by cause and revise unclear instructions; do not score staff negatively for using a required stop path.'
    ],
    boundary: 'A support coordinator sees a customer record in an unauthorized shared folder. The worker can stop sharing and preserve the link under an approved playbook, but should not decide whether the event is legally reportable, delete evidence, notify customers, or declare that no harm occurred.',
    uncertainty: 'DPO independence, reporting lines, registration, professional qualifications, conflict management, response duties, and interaction with other specialists depend on the organization and current requirements. This article does not allocate statutory responsibility or determine who must hold a particular office.',
    sources: [{ name: `National Privacy Commission — Appointing a Data Protection Officer (${checked})`, url: 'https://privacy.gov.ph/appointing-a-data-protection-officer/' }, { name: `National Privacy Commission — Accountability overview (${checked})`, url: 'https://privacy.gov.ph/accountability/' }, security, irr],
    service: { heading: 'Put the privacy route inside daily operations', copy: 'Use the data processing support guide to define worker actions, pause conditions, evidence fields, and the client-side owners who make privacy and security decisions.', label: 'Review data processing support', href: '/services/data-processing-support' },
    related: [{ label: 'Review breach escalation records', href: '/research/philippines-outsourcing-data-breach-escalation-research-2026' }, { label: 'Review data processing support', href: '/services/data-processing-support' }]
  },
  {
    slug: 'philippines-outsourcing-contractor-registration-due-diligence-research-2026',
    title: 'What Does Philippine Contractor Registration Prove—and Not Prove?',
    excerpt: 'A buyer-side review of Department Order No. 174 records, contracting facts, worker protections, and the limits of registration as outsourcing due diligence.',
    cluster: 'Buyer Governance', subject: 'contractor-registration due diligence',
    question: 'When a Philippines provider presents a contractor registration, what should a buyer verify before treating the labor arrangement, service scope, and operating controls as settled?',
    facts: [
      'Department of Labor and Employment Department Order No. 174 governs covered contracting and subcontracting arrangements where an employer-employee relationship exists and states that non-permissible arrangements undermine workers’ security of tenure.',
      'The order defines the principal, contractor or subcontractor, contractor employee, substantial capital, and related terms, and distinguishes permissible contracting from prohibited labor-only contracting through facts rather than a marketing label.',
      'The order includes contractor registration requirements and addresses the service agreement, employment contracts, rights of contractor employees, records, renewal, cancellation, and enforcement within its scope.',
      'A certificate can evidence a registration event for a named entity and period. It does not independently prove that the seller named in a website, invoice, bank account, employment contract, operating team, and client agreement is the same party or that every real practice matches the submitted records.'
    ],
    controls: [
      'Match the certificate’s legal name, registration number, issuing regional office, validity period, authorized representative, address, and stated scope with the contracting entity, invoice, payment beneficiary, worker employer, and current public or directly verified DOLE record.',
      'Obtain a responsibility map for recruitment, employment contracts, wages and benefits, supervision, tools and equipment, workplace rules, schedule, leave, discipline, replacement, grievance, health and safety, data access, and termination. Record which party acts, approves, pays, and retains evidence.',
      'Review the service agreement and representative worker documents with qualified Philippine counsel. Operations staff may assemble and reconcile identifiers, dates, and missing documents, but should not label an arrangement permissible or decide employment status from a checklist.',
      'Set renewal and change triggers for expiration, cancellation, new entity, merger, new region, materially changed service, new subcontractor, worker complaint, inconsistent payroll or supervision facts, or a request that changes who controls the work. Preserve the former record and decision.'
    ],
    boundary: 'A sales proposal uses one brand, the registration names another company, invoices come from a third entity, and daily instructions would be issued directly to workers by the overseas buyer. The registration image does not resolve the mismatch or the real allocation of control.',
    uncertainty: 'Whether Department Order No. 174 applies, whether a specific arrangement is permissible, who is an employer, and what liabilities follow require current facts and qualified Philippine legal advice. Government rules and records can change; registration is neither a quality rating nor a guarantee of compliance.',
    sources: [{ name: `Department of Labor and Employment — Department Order No. 174, Series of 2017 (${checked})`, url: 'https://www.ble.dole.gov.ph/wp-content/uploads/2023/02/DO-174-17-Rules-Implementing-Articles-106-to-109-of-the-Labor-Code-As-Amended1.pdf' }, { name: `DOLE Regional Office XI — Contracting and Subcontracting overview (${checked})`, url: 'https://ro11.dole.gov.ph/organizational-outcome-1-2/' }, { name: `Department of Labor and Employment — Labor Code of the Philippines (${checked})`, url: 'https://dole.gov.ph/labor-code-of-the-philippines/' }],
    service: { heading: 'Turn provider evidence into a role plan', copy: 'Use the staffing planning guide to reconcile the provider, employer, supervisor, accounts, schedule, review owner, and decisions that remain with the buyer.', label: 'Read the staffing plan guide', href: '/blog/Filipino-outsource-staffing-planning' },
    related: [{ label: 'Review provider verification research', href: '/research/philippines-outsourcing-provider-verification-research-2026' }, { label: 'Questions before hiring Filipino talent', href: '/blog/Filipino-outsource-staffing-provider-questions' }]
  },
  {
    slug: 'philippines-outsourcing-instruction-register-research-2026',
    title: 'What Should an Outsourcing Instruction Register Contain?',
    excerpt: 'A primary-source framework for keeping client purpose, permitted processing, changes, exceptions, and proof of instruction visible in a Philippines outsourcing relationship.',
    cluster: 'Buyer Governance', subject: 'outsourcing instruction control',
    question: 'How should a buyer and Philippines processing team prove what the provider was instructed to do, what remained prohibited, and which later changes were actually approved?',
    facts: [
      'The Data Privacy Act implementing rules distinguish a personal information controller that controls processing from a processor to whom the controller outsources or instructs processing of personal data.',
      'NPC guidance on outsourcing emphasizes that only an activity authorized under the Data Privacy Act may be delegated or subcontracted; outsourcing does not create authority that the controller did not have.',
      'The implementing rules require controllers to use contractual or other reasonable means to ensure comparable protection when personal data is processed by a third party and identify minimum matters for outsourcing agreements.',
      'A signed agreement sets a baseline, but daily instructions also arrive through tickets, field maps, macros, integrations, access grants, change requests, and verbal decisions. If those artifacts conflict, workers need a controlled source and a safe stop.'
    ],
    controls: [
      'Give each instruction a stable identifier, controller and processor entity, business purpose, data subjects and fields, source systems, permitted actions, prohibited actions, recipients, locations, subprocessors, access roles, output, retention, deletion, security controls, owner, approval, effective time, and review date.',
      'Link the instruction to its contract and privacy record, then keep operational examples and decision rules in a versioned procedure. A worker should see the effective version for the exact queue and know whether a client message proposes a change or merely applies an existing rule.',
      'Use a change record that captures requester, reason, affected cases, new data or system, privacy and security review, commercial impact, approver, testing, activation, communication, rollback, and verification. Do not overwrite the former instruction while earlier cases still depend on it.',
      'Audit a consecutive sample from source request to output. Check that processing matched purpose, fields were necessary, access was named, exceptions stopped, approvals preceded action, exports reached only approved recipients, and retention or deletion evidence exists. Record disagreement rather than forcing a clean score.'
    ],
    boundary: 'A manager asks in chat for a coordinator to export a complete customer table to a new analytics vendor “just this once.” The current register permits only a weekly aggregate report and names no vendor. The worker should preserve and route the proposed change, not treat seniority or urgency as authority.',
    uncertainty: 'Controller-processor roles, lawful authority, contractual requirements, cross-border rules, subprocessor conditions, security measures, and retention obligations depend on the actual relationship and jurisdictions. An instruction register supports accountability but does not cure an unlawful purpose or replace professional review.',
    sources: [irr, { name: `National Privacy Commission — Advisory Opinion 2020-018, Outsourcing the Processing of Personal Data (${checked})`, url: 'https://privacy.gov.ph/wp-content/uploads/2022/01/NPC_AdvisoryOpinionNo._2020-018.pdf' }, { name: `National Privacy Commission — Manage Legal guidance for outsourcing contracts (${checked})`, url: 'https://privacy.gov.ph/manage-legal/' }, security],
    service: { heading: 'Convert contract scope into daily instructions', copy: 'Use the data processing support guide to define allowed fields, systems, actions, reviewers, exception routes, and exit evidence for a controlled first queue.', label: 'Review data processing support', href: '/services/data-processing-support' },
    related: [{ label: 'Review subprocessor change control', href: '/research/philippines-outsourcing-subprocessor-change-control-research-2026' }, { label: 'Review data processing agreements', href: '/research/philippines-outsourcing-data-processing-agreement-research-2026' }]
  }
];

function makePost(t: Topic): ResearchPost {
  return {
    slug: t.slug, title: t.title, excerpt: t.excerpt, published: 'Published September 24, 2026', datePublished: date,
    readTime: '12 minute read', cluster: t.cluster, cardHighlight: t.controls[0],
    keyTakeaways: [t.facts[0], t.controls[0], t.uncertainty],
    stats: [{ label: 'Primary sources', value: String(t.sources.length), width: 82 }, { label: 'Control checks', value: String(t.controls.length), width: 68 }, { label: 'Decision owner', value: 'Named', width: 54 }],
    graphicCaption: 'A planning view of source coverage and operating checks. Bar widths are illustrative and do not report measured performance.',
    sections: [
      { heading: 'The decision this research supports', paragraphs: [t.question, `This desk study is for buyers designing Philippines-based support. It examines ${t.subject} as an operating decision, not as a promise about a provider, worker, product, or legal result. The aim is to make purpose, authority, evidence, handoffs, and unresolved questions visible before volume or access expands.`, 'Cited authorities establish rules or guidance only within their scope. The workflow design in this article is FilipinoOutsource.com analysis. The publishers have not reviewed or endorsed the design, and the analysis must be tested against the buyer’s actual contracts, systems, data, locations, and accountable owners.', 'Facts, analysis, inference, and uncertainty are deliberately separated. Source propositions appear in the next section. Recommended fields and controls are operational inferences. The boundary case is hypothetical. Limitations explain what this desk review cannot decide.'] },
      { heading: 'What the primary sources establish', paragraphs: [t.facts.map((fact, i) => `${i + 1}. ${fact}`).join(' '), `The ${t.sources.length} primary sources were checked on September 24, 2026. A checked date establishes when the research team reviewed the public material; it does not guarantee that a page, rule, register, interpretation, or organization-specific fact will remain unchanged. The accountable owner should recheck the authority before a consequential decision.`, 'Do not collapse a source statement into a broader commercial claim. A rule about controller accountability does not prove that a vendor is secure. A registration record does not prove service quality. A policy does not prove implementation. A completed ticket does not prove that the requester had authority or that the resulting action was accurate.', 'Local facts often decide the hard question: which entity contracted, who employs the worker, who determines purpose, which fields were visible, which account performed the action, where a copy remained, and who approved the exception. Those facts need contemporaneous evidence rather than confident language.'] },
      { heading: 'A minimum operating record', paragraphs: [t.controls.map((item, i) => `${i + 1}. ${item}`).join(' '), 'Separate proposal, approval, implementation, verification, and correction. A proposal records what someone wants to happen. Approval records who had authority and any conditions. Implementation records what actually changed. Verification compares the result with the decision. Correction preserves what was wrong, who fixed it, why, and which downstream records or people were affected.', 'A stable record should link to evidence without duplicating sensitive content into less controlled tools. Use identifiers for the case, instruction version, contract, system, account, source, decision, and output. Apply access and retention rules to the evidence itself; an audit trail can create a second exposure when it indiscriminately copies personal data.', 'Record negative evidence carefully. “No export found” should name the logs and period checked. “No new recipient” should identify the system boundary reviewed. “No sensitive field used” should state the field list and sample. An absence observed in one place and time is not a permanent claim about the entire organization.'] },
      { heading: 'Boundary case and escalation', paragraphs: [t.boundary, 'The first safe move is to preserve the request, identify the current instruction, and pause only the action that exceeds it. The support worker should state the mismatch in concrete terms and ask one question of a named owner. Broad messages such as “please advise” delay decisions and tempt others to infer missing context.', 'An escalation should include the case identifier, observed facts, source evidence, relevant instruction and version, data or people affected, action completed, action not completed, deadline, immediate risk, receiving owner, and requested decision. Sensitive attachments should remain in an approved repository with controlled access instead of being copied into group chat.', 'The owner may reject the request, narrow it, require new evidence, add safeguards, obtain specialist review, approve a limited test, or authorize the change with conditions. The response must be captured with author, scope, effective time, and expiry. Approval for one case, dataset, tool, audience, or period should not silently become a standing rule.', 'After action, a different check should compare the real result with the decision. Verify access, affected records, recipients, output, logs, retained copies, notices, and cleanup. If the system cannot produce enough evidence, record the gap and narrow the workflow instead of treating lack of visibility as proof that nothing went wrong.'] },
      { heading: 'Access, handoff, correction, and exit', paragraphs: ['Access should follow the required output. Use named accounts, least practical privileges, approved devices and storage, strong authentication, and separate authorization for exports, settings, mass changes, payments, publication, or deletion. Record the approver, grant time, review date, and removal trigger.', 'A cross-time-zone handoff needs item status, evidence checked, completed action, paused action, deadline, affected customer or system, and receiving owner. “Done” is not an adequate state when an authorization, exception, correction, communication, or release remains outstanding. The next shift must be able to reconstruct the issue from controlled records.', 'Correction history should preserve the prior value, corrected value, source for each, actor, reason, event time, and downstream effect. Silent overwrites can conceal which state drove an earlier decision. Where notification or remediation may be needed, the qualified owner decides it and the operations role records execution evidence.', 'Exit is part of design. Decide how accounts, sessions, tokens, shared links, local files, synchronized folders, exports, backups, printed records, integrations, and subprocessor access are removed or transferred. Obtain observable evidence and record unresolved residual copies rather than accepting a generic statement that access was turned off.'] },
      { heading: 'How to test before scaling', paragraphs: ['Begin with five consecutive eligible cases after a declared start point. Do not select polished examples after seeing the result. Retain incomplete, paused, corrected, and disputed cases when they naturally occur, and state why any case is excluded. This can test whether an instruction is usable; it cannot establish a provider-wide rate.', 'For each case, ask whether purpose was identifiable, inputs were necessary, source evidence was preserved, the current instruction was used, access stayed within scope, exceptions stopped, the owner received an answerable question, and the final state matched the recorded decision. Preserve reviewer disagreement as evidence about the rule.', 'Useful measures are descriptive: eligible cases, missing sources, identity conflicts, unapproved systems, paused actions, owner response time, corrections, overrides, removal failures, and unresolved exceptions. Each count needs a denominator, period, inclusion rule, and evidence source. None alone proves compliance, safety, fairness, productivity, or worker quality.', 'Repeat the review after a change in law or guidance, purpose, party, contract, data category, system, integration, feature, location, schedule, reviewer, consequence, retention, or repeated exception. Earlier evidence describes an earlier state; it is not a permanent certification of the process.'] },
      { heading: 'Limits and accountable ownership', paragraphs: [t.uncertainty, 'Support staff can retrieve approved evidence, enter defined fields, apply an administrative status under a written rule, prepare a comparison, and route a focused exception. They should not be assigned decisions about legal interpretation, rights, employment status, security risk, regulatory reporting, or other consequential matters outside written authority.', 'The accountable controller, employer, client manager, data protection officer, security lead, counsel, HR owner, finance owner, or other qualified professional must decide questions within their remit. Titles vary, but the operating record should name a person or controlled role and a backup rather than an unspecified department.', 'Workers need a protected stop path. Throughput pressure, urgency, a senior requester, or a familiar-looking precedent does not replace missing authority. A correct stop should be evaluated as correct work when the instruction requires it, and recurring stops should prompt the owner to clarify the rule.', `The narrow conclusion is that ${t.subject} becomes more reviewable when purpose, source, data, parties, systems, authority, action, verification, correction, and exit evidence remain connected. Documentation supports accountability; it does not make an underlying activity lawful, secure, fair, or effective by itself.`] },
      { heading: 'A buyer implementation sequence', paragraphs: ['First, describe one finished output in plain language. Second, identify its authoritative inputs and minimum necessary data. Third, map every party, system, account, location, and copy involved. Fourth, name the decisions retained by the client and the specialist owners who receive exceptions. Fifth, test with redacted or synthetic examples before granting live access.', 'Next, run the bounded consecutive sample and inspect exceptions more closely than volume. Confirm that workers can find the current instruction, that reviewers can reproduce status from source evidence, and that owner responses answer the precise question asked. Where ambiguity repeats, revise the instruction and examples before increasing volume.', 'Then align commercial documents with operations. Check that the actual provider, employing or contracting entity, purpose, service, data flow, access model, subprocessor path, security commitments, incident route, rights support, retention, deletion, and exit evidence match what daily tools and managers require.', 'Finally, keep a dated decision register showing what changed, why, sources reviewed, uncertainty, approver, conditions, implementation evidence, later corrections, review trigger, and exit result. This creates a controlled learning cycle while leaving legal and professional judgments with the people accountable for them.'] }
    ],
    methodology: `Qualitative desk review of ${t.sources.length} primary Philippine government sources, checked September 24, 2026. The method separated explicit source propositions from FilipinoOutsource.com operating analysis, applied the analysis to one hypothetical boundary case, and defined a five-case consecutive review. No provider, worker, client, personal data, production system, price, performance result, or legal outcome was tested. The method cannot establish prevalence, causation, compliance, security, or service quality.`,
    faq: [
      { q: 'Is this legal, privacy, employment, security, or tax advice?', a: 'No. It is a buyer-side research and workflow framework. Qualified advisers and accountable owners must decide how current rules apply to real facts.' },
      { q: 'Does a five-case review prove quality or compliance?', a: 'No. It tests whether the current written instruction is usable on a bounded set and exposes exclusions, uncertainty, and disagreement.' },
      { q: 'What may the support role own?', a: 'Approved evidence gathering, defined administrative fields, status preparation, correction records, and focused escalation—not consequential decisions outside written authority.' },
      { q: 'When should the record be reopened?', a: 'When purpose, source, data, party, contract, system, tool, location, reviewer, consequence, law, or retention practice changes.' }
    ],
    sources: t.sources, related: t.related, serviceHandoff: t.service, heroImage: '/article-planning.svg'
  };
}

export const september24ResearchPosts: readonly ResearchPost[] = topics.map(makePost);
