import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'National Privacy Commission — Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST SP 800-53 Rev. 5 — Audit and Accountability',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'CISA — Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'Philippine Statistics Authority — Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = {slug:string;title:string;excerpt:string;cluster:string;question:string;setting:string;model:string;caseStudy:string;limit:string;finding:string;labels:readonly [string,string,string]};
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-queue-reopen-rate-research-2026',title:'What Does a Queue Reopen Rate Actually Measure?',excerpt:'Research on interpreting reopened outsourced work without treating every return as worker error.',cluster:'Quality Operations',question:'When a completed item returns to a Philippines-based support queue, what can the reopen event legitimately show?',setting:'customer tickets, invoice packets, catalog corrections, and candidate schedules',model:'record the original finish state, reopening actor, new evidence, reason category, and final owner decision',caseStudy:'A ticket returns after a customer supplies a document that did not exist during the first review.',limit:'No live provider queue was observed, and the sources do not prescribe a universal acceptable reopen percentage.',finding:'A reopen rate becomes useful only when new evidence, correction, changed instruction, and premature closure are counted separately.',labels:['Reopen reasons','Sample records','Universal target']},
  {slug:'philippines-outsourcing-owner-wait-time-research-2026',title:'Can Owner-Wait Time Clarify Outsourcing Bottlenecks?',excerpt:'A source-bounded study of measuring work paused for client decisions across Philippine and buyer time zones.',cluster:'Remote Operations',question:'Can a queue distinguish preparation time from the hours spent waiting for an authorized client owner?',setting:'refund exceptions, payment reviews, access requests, publication approvals, and schedule changes',model:'store ready-for-review time, owner-notified time, source-refresh time, decision time, and any expiry event',caseStudy:'A prepared refund case waits overnight, then receives a new customer message before the manager replies.',limit:'The analysis did not test response times or define an SLA; owner availability and consequence vary by workflow.',finding:'Owner-wait time is descriptive when its clock, decision boundary, and source changes remain visible.',labels:['Queue clocks','Decision owners','Promised SLA']},
  {slug:'philippines-outsourcing-redaction-review-research-2026',title:'When Is Redaction Review Ready for a Remote Handoff?',excerpt:'Research on checking minimum necessary evidence before a redacted packet crosses roles or systems.',cluster:'Evidence Operations',question:'What makes a redacted support packet reviewable without implying that visible text is automatically safe to share?',setting:'candidate files, customer complaints, vendor checks, and executive meeting extracts',model:'identify purpose, intended reviewer, source class, removal rule, residual-risk question, and release owner',caseStudy:'A candidate schedule hides the name but leaves an email address and free-text medical note in the attachment.',limit:'This is operational analysis, not a legal determination of anonymization or permission to disclose information.',finding:'Redaction is a controlled release decision, not merely a visual editing task.',labels:['Packet checks','Release owner','Automatic safety']},
  {slug:'philippines-outsourcing-exception-owner-churn-research-2026',title:'How Does Exception-Owner Churn Affect Handoff Quality?',excerpt:'Research on preserving decision accountability when managers or role owners change during outsourced work.',cluster:'Governance Operations',question:'What evidence keeps an exception reviewable when the named client owner changes before a decision?',setting:'contract renewals, customer remedies, accounting differences, access approvals, and content claims',model:'retain the original owner, transfer authority source, effective time, pending decision, notified parties, and new owner',caseStudy:'A renewal exception is reassigned after the original approver leaves, but no record shows who inherited authority.',limit:'The model was not tested inside a client governance system and cannot establish who legally holds authority.',finding:'Reassignment is reliable only when authority transfer is evidenced rather than inferred from availability.',labels:['Transfer fields','Pending cases','Inferred owners']},
  {slug:'philippines-outsourcing-instruction-exception-debt-research-2026',title:'Can Repeated Exceptions Reveal Instruction Debt?',excerpt:'A study of when recurring questions point to a weak operating guide instead of isolated support mistakes.',cluster:'Process Research',question:'When do repeated escalations justify revising the approved instruction for a Philippines-based support lane?',setting:'inbox routing, order updates, reconciliation packets, CRM cleanup, and publishing checks',model:'group questions by instruction version, source condition, stop rule, owner answer, recurrence, and correction status',caseStudy:'Three coordinators separately ask how to handle orders with a carrier scan but no warehouse dispatch record.',limit:'The examples are hypothetical and do not prove that fewer questions will improve commercial or customer outcomes.',finding:'Recurring, similarly evidenced exceptions can reveal a missing rule, but only the instruction owner can change it.',labels:['Exception groups','Guide versions','Outcome claim']},
];

function makeStudy(s: Study): ResearchPost {
  const [first,second,third]=s.labels;
  return {
    slug:s.slug,title:s.title,excerpt:s.excerpt,published:'September 4, 2026',datePublished:'2026-09-04',dateModified:'2026-09-04',readTime:'11 minute read',cluster:s.cluster,
    cardHighlight:s.finding,
    keyTakeaways:[s.finding,'A metric needs a defined event, denominator, time window, and decision owner.','Observed queue evidence should remain separate from inference and business judgment.'],
    stats:[{label:first,value:'5',width:76},{label:second,value:'1',width:42},{label:third,value:'0',width:18}],
    graphicCaption:`The review model keeps ${first.toLowerCase()}, ${second.toLowerCase()}, and the limits of ${third.toLowerCase()} explicit.`,
    heroImage:'/images/research-2026-08-21-evidence-freshness.png',
    sections:[
      {heading:'Research question and operating context',paragraphs:[s.question,`The study uses ${s.setting} as bounded examples. It asks what a remote coordinator can observe and preserve before a client-side owner makes a decision. It does not transfer approval authority or turn a queue measure into a performance promise.`]},
      {heading:'Evidence scope and method',paragraphs:[`The National Privacy Commission source supplies principles of accuracy, proportionality, security, and declared purpose. NIST audit guidance supports recording identifiable events, times, actors, and outcomes. CISA guidance contributes an access-control lens, while PSA technical notes illustrate why definitions and reference periods must travel with reported figures. These sources address different domains; applying them to outsourced operations is our analytical model, not a rule stated by the sources.`,`Five hypothetical records were examined across the listed settings. For each one, the review separated observable source facts, coordinator classifications, owner decisions, and later outcomes. The proposed record design is: ${s.model}.`]},
      {heading:'What the measure can and cannot say',paragraphs:[`${s.finding} A raw count cannot explain causation. It must be paired with total eligible items, the observation period, exclusions, and any instruction change during that period.`,`The coordinator may keep the record and flag a threshold chosen by the client. The owner decides whether the pattern changes staffing, policy, access, or workflow. A small sample may be useful for diagnosis without supporting a general claim about people or providers.`]},
      {heading:'A boundary case',paragraphs:[s.caseStudy,`The safe handoff keeps both the earlier state and the later evidence. It names what changed, which action remains paused, and who can decide. Replacing the original record would make the eventual result look simpler than the work actually was.`]},
      {heading:'A practical review routine',paragraphs:[`Start with five consecutive eligible items and one deliberately selected exception. Ask a second reviewer to reproduce the status from the approved sources, check the category, and locate the decision owner. Record disagreement instead of forcing consensus into the first label.`,`Review category definitions after the sample. If two reviewers use one label differently, revise the example or split the category. Keep the old version and effective date so historical counts are not silently compared under a new rule.`]},
      {heading:'Limitations and evidence-led conclusion',paragraphs:[s.limit,`The evidence supports a narrow conclusion: ${s.finding.toLowerCase()} For FilipinoOutsource.com buyers, the useful next step is a small, dated sample with visible source links and owner decisions—not a benchmark borrowed from another queue.`,`Access limits, retention, professional review, and customer or employee rights still depend on the buyer’s setting. Any legal, accounting, clinical, employment, security, or commercial determination stays with an authorized professional or client owner.`]},
    ],
    methodology:`Qualitative desk analysis applying official Philippine privacy guidance, NIST audit-control guidance, CISA access guidance, and PSA definition practices to five hypothetical ${s.cluster.toLowerCase()} records. No production provider, worker, customer, or outcome was measured.`,
    faq:[{q:'Does the study set a performance target?',a:'No. It proposes observable fields and limits; the buyer defines any target for its own queue.'},{q:'Can a coordinator resolve the exception?',a:'The coordinator can document and route it. The authorized client owner makes the consequential decision.'},{q:'What is the smallest useful test?',a:'Review five eligible records and one exception against the original sources with a second reviewer.'}],
    sources,related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Review the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}],
  };
}

export const september4ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
