import type {ResearchPost} from './fleet-data';
type Study={slug:string;title:string;cluster:string;question:string;finding:string;caseStudy:string;sourceName:string;sourceUrl:string;scope:string;limitations:string;fields:string[]};
const studies:readonly Study[]=[
{slug:'philippines-outsourcing-consent-record-precedence-research-2026',title:'Philippines Outsourcing Consent Record Precedence Research 2026',cluster:'Privacy Operations',question:'How should a support queue handle conflicting marketing consent and suppression records?',finding:'A reviewable preference packet preserves every channel event, collection wording, timestamp, source system, and suppression state.',caseStudy:'The CRM has an older opt-in while the sending platform has a newer unsubscribe.',sourceName:'National Privacy Commission: Data Privacy Act',sourceUrl:'https://privacy.gov.ph/data-privacy-act/',scope:'Privacy principles inform purpose and controlled processing but do not decide a buyer-specific lawful basis.',limitations:'This analysis is not legal advice and does not test a consent system.',fields:['contact identifier','channel event','collection wording','timestamp','source system','owner decision']},
{slug:'philippines-outsourcing-purchase-order-change-control-research-2026',title:'Philippines Outsourcing Purchase Order Change Control Research 2026',cluster:'Procurement Operations',question:'Which evidence fields separate purchase-order change preparation from purchasing authority?',finding:'A bounded change record links the approved order, requested difference, requester, supplier response, approval status, and effective version.',caseStudy:'A supplier confirms a later delivery date while inserting an unapproved quantity change.',sourceName:'Government Procurement Policy Board',sourceUrl:'https://www.gppb.gov.ph/',scope:'Public procurement materials provide control context but do not govern a private purchase order.',limitations:'This study does not interpret contracts or establish procurement compliance.',fields:['approved order','requested difference','requester','supplier response','approval status','effective version']},
{slug:'philippines-outsourcing-training-version-evidence-research-2026',title:'Philippines Outsourcing Training Version Evidence Research 2026',cluster:'People Operations',question:'What records make remote-team training completion reviewable when course versions change?',finding:'Completion evidence should tie the learner, requirement, assigned version, completion event, exception, and manager review together.',caseStudy:'A worker completed a retired course after its replacement became mandatory.',sourceName:'Department of Labor and Employment',sourceUrl:'https://www.dole.gov.ph/',scope:'Official labor information supplies general context but does not certify competency or a training program.',limitations:'This analysis does not decide employment duties, competency, or disciplinary action.',fields:['learner','requirement','assigned version','completion event','exception','manager review']},
{slug:'philippines-outsourcing-security-questionnaire-provenance-research-2026',title:'Philippines Outsourcing Security Questionnaire Provenance Research 2026',cluster:'Access Governance',question:'How can remote support prepare security-questionnaire answers without creating unsupported assurances?',finding:'Question-level provenance connects the prompt, approved response, evidence version, owner, sharing restriction, and final approver.',caseStudy:'An old answer names a replaced tool, while replacement evidence is not approved for sharing.',sourceName:'National Privacy Commission: Data Privacy Act IRR',sourceUrl:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/',scope:'Security requirements inform governance but do not certify a control or authorize disclosure.',limitations:'This is not a security assessment, certification, or authorization to answer a questionnaire.',fields:['question identifier','approved response','evidence version','evidence owner','sharing restriction','final approver']},
{slug:'philippines-outsourcing-retention-hold-separation-research-2026',title:'Philippines Outsourcing Retention and Hold Separation Research 2026',cluster:'Data Operations',question:'How should a records queue distinguish scheduled disposition from legal-hold authority?',finding:'A preparation record separates category, schedule source, trigger date, hold status, proposed action, and completion evidence.',caseStudy:'A schedule indicates disposition while an unresolved hold flag has no named owner.',sourceName:'National Archives of the Philippines',sourceUrl:'https://nationalarchives.gov.ph/',scope:'Public records material offers context but does not set private legal duties or release a hold.',limitations:'This is not legal advice and does not determine retention periods, hold scope, or deletion method.',fields:['record category','schedule source','trigger date','hold status','proposed action','completion evidence']},
];
function build(s:Study):ResearchPost{const sections=[
{heading:'Research question and boundary',paragraphs:[s.question,`${s.finding} The inquiry concerns evidence preparation, not approval of a workflow or outcome.`]},
{heading:'Source scope and method',paragraphs:[`The anchor source is ${s.sourceName}. ${s.scope}`,`The method separates publisher claims, operating interpretation, and limitations. The source does not endorse FilipinoOutsource.com.`]},
{heading:'Reproducible evidence fields',paragraphs:[`The proposed record contains ${s.fields.join(', ')}. Each value retains a source location, version or timestamp, and status.`,`Missing evidence stays open, reported wording stays attributed, and the authorized owner records the decision.`],bullets:s.fields},
{heading:'Applied exception analysis',paragraphs:[s.caseStudy,'The support role preserves both sources, records the exact difference, pauses the consequential step, and routes one focused question to the owner.']},
{heading:'Sampling and operating measures',paragraphs:['Review an ordinary item, an incomplete item, and the exception against the written rule, access, escalation, and correction path.','Count arrivals, missing fields, conflicts, returns, owner waits, and age. These indicate queue condition, not business outcomes.']},
{heading:'Limitations',paragraphs:[s.limitations,'Sources and system configurations change. Sensitive decisions remain with a qualified owner.']},
{heading:'Evidence-led conclusion',paragraphs:['The evidence supports a narrow preparation role that preserves provenance and disagreement while limiting access. It does not transfer authority.','Before volume expands, a second reviewer should retrace each consequential field and explain the stop rule without private context.']},
];return{slug:s.slug,title:s.title,excerpt:`A source-backed analysis of ${s.question.charAt(0).toLowerCase()+s.question.slice(1)}`,published:'September 2, 2026',datePublished:'2026-09-02',readTime:'10 minute read',cluster:s.cluster,cardHighlight:s.finding,keyTakeaways:[s.finding,'Separate source facts, interpretation, and owner decisions.','Test ordinary, incomplete, and stop-case records.','Queue measures do not establish outcomes.'],stats:[{label:'Evidence fields',value:String(s.fields.length),width:78},{label:'Review samples',value:'3',width:58},{label:'Decision owner',value:'1',width:38}],graphicCaption:`A bounded evidence model for ${s.title.replace(' Research 2026','').toLowerCase()}.`,sections,table:{heading:'Evidence-to-owner handoff',headers:['Stage','Record','Boundary'],rows:[['Intake',s.fields.slice(0,2).join(' and '),'Preserve source'],['Preparation',s.fields.slice(2,4).join(' and '),'Label differences'],['Decision',s.fields.slice(4).join(' and '),'Owner decides']]},methodology:`Qualitative source-scope analysis using ${s.sourceName}, separating source claims from a proposed FilipinoOutsource.com workflow and testing a hypothetical exception.`,faq:[{q:'Does this approve a workflow?',a:'No. The authorized owner must approve the actual workflow and access.'},{q:'Why review three samples?',a:'Ordinary, incomplete, and stop-case records reveal different instruction gaps.'}],sources:[{name:s.sourceName,url:s.sourceUrl},{name:'National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'Philippine Statistics Authority',url:'https://psa.gov.ph/'}],related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Use the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]}}
export const september2ResearchPosts:readonly ResearchPost[]=studies.map(build);
