import type { ResearchPost } from './fleet-data';

type Study={slug:string;title:string;cluster:string;question:string;finding:string;caseStudy:string;sourceName:string;sourceUrl:string;sourceScope:string;limitations:string;fields:string[]};
const studies: readonly Study[]=[
  {slug:'philippines-outsourcing-payment-evidence-separation-research-2026',title:'Philippines Outsourcing Payment Evidence Separation Research 2026',cluster:'Finance Operations',question:'How should a remote team separate payment-source evidence from posting and allocation decisions?',finding:'A reproducible payment packet preserves the bank event, remittance detail, invoice references, unresolved differences, and the authorized finance decision as separate records.',caseStudy:'One receipt matches the total of two invoices, but the customer remittance names an invoice held on a different account.',sourceName:'Bangko Sentral ng Pilipinas',sourceUrl:'https://www.bsp.gov.ph/',sourceScope:'Official Philippine central-bank information provides financial-system context but does not decide a private ledger entry.',limitations:'This qualitative study is not accounting, tax, banking, or legal advice and does not test a buyer’s controls.',fields:['bank event','remittance detail','invoice reference','amount comparison','unresolved difference','finance-owner decision']},
  {slug:'philippines-outsourcing-access-removal-evidence-research-2026',title:'Philippines Outsourcing Access Removal Evidence Research 2026',cluster:'Access Governance',question:'Which records make remote-worker access removal reviewable after a role change or separation?',finding:'An access-removal record is stronger when it links the system, named account, permission, trigger, responsible owner, completion evidence, and exception status.',caseStudy:'A user account is disabled, but the worker still owns an automation token and a shared reporting schedule.',sourceName:'National Privacy Commission: Data Privacy Act IRR',sourceUrl:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/',sourceScope:'Philippine privacy and security requirements inform access governance but do not certify a specific offboarding process.',limitations:'The study does not inspect technical logs or establish that access is fully removed in any particular system.',fields:['system','named account','permission','removal trigger','completion evidence','exception owner']},
  {slug:'philippines-ecommerce-catalog-claim-provenance-research-2026',title:'Philippines Ecommerce Catalog Claim Provenance Research 2026',cluster:'Ecommerce Operations',question:'What provenance fields help a catalog support queue avoid inventing or silently changing product claims?',finding:'Catalog preparation is easier to review when each public claim retains an approved source, version, product identifier, reviewer, publication state, and conflict note.',caseStudy:'Approved packaging artwork and a supplier spreadsheet describe the same product material differently.',sourceName:'Department of Trade and Industry Ecommerce FAQs',sourceUrl:'https://ecommerce.dti.gov.ph/faqs/',sourceScope:'Public ecommerce and consumer information provides context; it does not approve a merchant’s product representation.',limitations:'This analysis does not determine claim legality, product safety, intellectual-property rights, or marketplace compliance.',fields:['product identifier','claim text','approved source','source version','reviewer decision','publication state']},
  {slug:'philippines-services-workforce-schedule-overlap-research-2026',title:'Philippines Services Workforce Schedule-Overlap Research 2026',cluster:'Philippines Market Data',question:'What can Philippine labor statistics establish about planning schedule overlap for a remote services role?',finding:'National labor statistics describe employment conditions at a population level; they cannot prove an individual candidate’s availability, schedule fit, connectivity, or performance.',caseStudy:'A buyer assumes that a large services workforce guarantees immediate overnight coverage without testing the actual shift and manager overlap.',sourceName:'Philippine Statistics Authority: Labor Force Survey',sourceUrl:'https://psa.gov.ph/statistics/labor-force-survey/index',sourceScope:'Official national survey estimates describe labor-force conditions for stated reference periods, not outsourcing availability.',limitations:'Survey estimates have sampling and non-sampling limitations and should not be converted into provider or candidate guarantees.',fields:['survey period','covered population','published estimate','role schedule','manager overlap','candidate confirmation']},
  {slug:'philippines-consumer-service-credit-evidence-research-2026',title:'Philippines Consumer Service-Credit Evidence Research 2026',cluster:'Customer Support',question:'How can a support queue prepare service-credit evidence without turning a customer allegation into an eligibility finding?',finding:'The safer packet distinguishes the customer statement, applicable agreement, observed service events, missing evidence, requested remedy, and authorized owner response.',caseStudy:'A customer reports an outage, while monitoring confirms an event outside the service boundary named in the agreement.',sourceName:'DTI Consumer Complaints Assistance and Resolution System',sourceUrl:'https://consumercare.dti.gov.ph/',sourceScope:'The public complaint channel provides consumer-resolution context but does not determine a private service-credit claim.',limitations:'The workflow is not legal advice, does not interpret a contract, and does not establish fault or remedy eligibility.',fields:['customer statement','agreement version','service events','scope comparison','requested remedy','owner response']},
];

function build(s:Study):ResearchPost{const sections=[
  {heading:'Research question and boundary',paragraphs:[s.question,`${s.finding} The inquiry concerns evidence preparation, not whether a role, provider, or outcome is approved.`]},
  {heading:'Source scope and method',paragraphs:[`The anchor publication is ${s.sourceName}. ${s.sourceScope}`,`The method records publisher, reference period, defined population or subject, source claim, and limitation before proposing an operating interpretation. Official context does not endorse FilipinoOutsource.com.`]},
  {heading:'Reproducible evidence fields',paragraphs:[`The proposed record contains ${s.fields.join(', ')}. Each consequential value retains a source location, checking time, and status.`,`Missing evidence remains missing, reported wording stays attributed, calculations retain inputs, and owner decisions identify the authorized person and effective time.`],bullets:s.fields},
  {heading:'Applied case analysis',paragraphs:[s.caseStudy,`The coordinator preserves both sources, records the exact disagreement, pauses consequential action, and routes one focused question. The named owner decides what governs.`]},
  {heading:'Sampling and measures',paragraphs:[`Review one ordinary item, one incomplete item, and the case above against the written rule, source fields, access used, escalation, and correction.`,`Count received items, missing fields, conflicts, returns, owner waits, and unresolved age. These describe workflow condition, not accuracy, savings, compliance, or future results.`]},
  {heading:'Limitations',paragraphs:[s.limitations,`Public sources may change, definitions differ across systems, and a general authority may be too broad for a buyer-specific conclusion. Sensitive decisions need a qualified owner.`]},
  {heading:'Evidence-led conclusion',paragraphs:[`The evidence supports a bounded preparation role that preserves sources and disagreements while minimizing access. It does not transfer owner judgment.`,`A second reviewer should be able to retrace every consequential field and explain the stop rule without private context before volume expands.`]},
];return{slug:s.slug,title:s.title,excerpt:`A source-backed analysis of ${s.question.charAt(0).toLowerCase()+s.question.slice(1)}`,published:'September 1, 2026',datePublished:'2026-09-01',readTime:'10 minute read',cluster:s.cluster,cardHighlight:s.finding,keyTakeaways:[s.finding,'Keep source facts, operating interpretation, and owner decisions separate.','Test an ordinary, incomplete, and stop-case sample.','Queue measures are not business-outcome claims.'],stats:[{label:'Evidence fields',value:String(s.fields.length),width:78},{label:'Review samples',value:'3',width:58},{label:'Decision owner',value:'1',width:38}],graphicCaption:`A bounded evidence model for ${s.title.replace(' Research 2026','').toLowerCase()}.`,sections,table:{heading:'Evidence-to-owner handoff',headers:['Stage','Record','Boundary'],rows:[['Intake',s.fields.slice(0,2).join(' and '),'Preserve source'],['Preparation',s.fields.slice(2,4).join(' and '),'Label conflicts'],['Decision',s.fields.slice(4).join(' and '),'Owner decides']]},methodology:`Qualitative source-scope analysis using ${s.sourceName}. The method separates source claims from a proposed FilipinoOutsource.com workflow and applies the fields to a hypothetical exception.`,faq:[{q:'Does this approve a workflow?',a:'No. The buyer’s authorized owner must approve the actual workflow and access.'},{q:'Why use three samples?',a:'Ordinary, incomplete, and stop-case records expose different instruction gaps.'}],sources:[{name:s.sourceName,url:s.sourceUrl},{name:'National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'Philippine Statistics Authority: Labor Force Survey',url:'https://psa.gov.ph/statistics/labor-force-survey/index'}],related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Use the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]}}
export const september1ResearchPosts: readonly ResearchPost[]=studies.map(build);
