import type { ResearchPost } from './fleet-data';

const sources = [
  {name:'National Privacy Commission — Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST SP 800-53 Rev. 5 — Audit and Accountability',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'CISA — Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'Philippine Statistics Authority — Technical Notes',url:'https://psa.gov.ph/statistics/technical-notes/165790'},
] as const;

type Study = {slug:string;title:string;excerpt:string;cluster:string;question:string;setting:string;model:string;caseStudy:string;limit:string;finding:string;labels:readonly [string,string,string]};
const studies: readonly Study[] = [
  {slug:'philippines-outsourcing-evidence-completeness-rate-research-2026',title:'Can an Evidence Completeness Rate Improve Outsourced Work Reviews?',excerpt:'A source-bounded study of measuring complete review packets without confusing completeness with correctness.',cluster:'Quality Operations',question:'What can an evidence completeness rate show in a Philippines-based operations queue?',setting:'refund reviews, payroll changes, supplier files, access reviews, and delivery exceptions',model:'define eligible records, required fields, acceptable sources, observation time, missing state, and decision owner',caseStudy:'A refund packet contains every required file, but the delivery scan conflicts with the customer message.',limit:'No live provider queue was studied, and the sources do not supply a universal completeness target.',finding:'Completeness is observable only against a versioned packet definition, and it does not prove that a decision is correct.',labels:['Required fields','Packet sample','Accuracy claim']},
  {slug:'philippines-outsourcing-source-conflict-aging-research-2026',title:'What Does Source-Conflict Aging Reveal in Remote Operations?',excerpt:'Research on timing unresolved source conflicts without turning elapsed time into a worker-performance judgment.',cluster:'Remote Operations',question:'Can teams measure how long conflicting records wait for an authorized owner without mislabeling the delay?',setting:'shipment timelines, CRM consent records, payroll inputs, lease indexes, and board reports',model:'record conflict discovery, sources involved, owner notification, source refresh, decision timestamp, and closure reason',caseStudy:'A carrier event and warehouse record disagree, then the carrier replaces its scan the following morning.',limit:'The examples are hypothetical; owner schedules, risk, and source refresh cycles vary across workflows.',finding:'Conflict age becomes interpretable only when owner-wait time and later source changes remain separate from preparation time.',labels:['Conflict clocks','Owner wait','Worker speed']},
  {slug:'philippines-outsourcing-minimum-access-review-research-2026',title:'How Should Minimum Access Be Reviewed for an Outsourced Role?',excerpt:'A qualitative study of matching named permissions to a bounded workflow and recording exceptions.',cluster:'Security Operations',question:'What evidence helps a buyer review whether remote-support access matches the stated work?',setting:'customer exports, supplier documents, software reviews, payroll registers, and content approvals',model:'map each permission to a task, data class, named account, approver, review date, dependency, and removal trigger',caseStudy:'A coordinator needs report exports, but the default role also permits user administration.',limit:'This study is not a penetration test, legal opinion, or certification of any access-control system.',finding:'A useful access review connects every permission to a current task and sends surplus or ambiguous rights to the system owner.',labels:['Task links','Named accounts','Security verdict']},
  {slug:'philippines-outsourcing-definition-change-ledger-research-2026',title:'Why Keep a Definition-Change Ledger for Outsourced Reporting?',excerpt:'Research on preserving metric meaning when reporting definitions change across periods or teams.',cluster:'Reporting Governance',question:'How can an outsourced reporting lane keep historical figures interpretable after a definition changes?',setting:'board packs, service queues, training renewals, promotion checks, and supplier-document dashboards',model:'store the metric name, old definition, new definition, approver, effective date, affected periods, restatement decision, and source',caseStudy:'A dashboard begins excluding reopened tickets, but the earlier months are left under the old definition.',limit:'The proposed fields were not tested in a production reporting stack and do not determine accounting treatment.',finding:'A dated definition ledger prevents a clean-looking trend from silently combining unlike measures.',labels:['Definitions','Effective dates','Trend claim']},
  {slug:'philippines-outsourcing-review-sample-selection-research-2026',title:'Can Review Sample Selection Distort Outsourcing Quality Signals?',excerpt:'A study of documenting how work samples are chosen so favorable or difficult cases do not quietly skew conclusions.',cluster:'Process Research',question:'What minimum record makes a quality-review sample understandable to a client owner?',setting:'data exports, customer remedies, ecommerce setups, lease files, and access evidence',model:'record the eligible population, time window, selection method, exclusions, sample size, reviewer, disagreement, and follow-up',caseStudy:'A weekly review uses only completed records and excludes every item still waiting on an owner decision.',limit:'Five hypothetical examples cannot estimate prevalence or compare providers, workers, industries, or countries.',finding:'A sample supports a narrow operational conclusion only when its population, exclusions, and selection method are visible.',labels:['Eligible queue','Selected cases','Provider ranking']},
];

function makeStudy(s: Study): ResearchPost {
  const [first,second,third]=s.labels;
  return {slug:s.slug,title:s.title,excerpt:s.excerpt,published:'September 7, 2026',datePublished:'2026-09-07',dateModified:'2026-09-07',readTime:'11 minute read',cluster:s.cluster,cardHighlight:s.finding,
    keyTakeaways:[s.finding,'A measure needs a defined event, denominator, time window, and decision owner.','Observed records should remain separate from inference and business judgment.'],
    stats:[{label:first,value:'5',width:76},{label:second,value:'1',width:42},{label:third,value:'0',width:18}],
    graphicCaption:`The review separates ${first.toLowerCase()}, ${second.toLowerCase()}, and the limits of any ${third.toLowerCase()}.`,heroImage:'/images/research-2026-08-21-topic-distinctness.png',
    sections:[
      {heading:'Research question and operating context',paragraphs:[s.question,`The analysis uses ${s.setting} as bounded examples. It asks what a coordinator can observe and preserve before an authorized client owner acts. It does not transfer approval authority or turn a queue measure into a performance promise.`]},
      {heading:'Evidence scope and method',paragraphs:[`The National Privacy Commission source informs purpose, proportionality, accuracy, and security. NIST audit guidance supports recording events, times, actors, and outcomes. CISA contributes an account-control lens, while PSA technical notes illustrate why definitions and reference periods should accompany figures. Applying these sources to outsourced operations is our analytical model, not a rule stated by those sources.`,`Five hypothetical records were examined across the listed settings. Each review separated source facts, coordinator classifications, owner decisions, and later outcomes. The proposed record is: ${s.model}.`]},
      {heading:'What the measure can and cannot show',paragraphs:[`${s.finding} A raw count cannot establish cause. It needs the eligible population, observation period, exclusions, and any instruction change during that period.`,`A coordinator can maintain the record and flag a client-defined threshold. The owner decides whether the pattern changes access, staffing, policy, or workflow. A small sample may diagnose a process without supporting claims about a person or provider.`]},
      {heading:'Boundary case',paragraphs:[s.caseStudy,`The sound handoff preserves the earlier state and later evidence, names what changed, and identifies the action that remains paused. Replacing the first record would erase useful context.`]},
      {heading:'Practical review routine',paragraphs:[`Begin with five consecutive eligible records and one deliberately chosen exception. Ask a second reviewer to reproduce the state from approved sources, check the category, and locate the decision owner. Record disagreement rather than forcing the first label to appear certain.`,`Review the definitions after the sample. If reviewers apply one label differently, revise the example or split the category. Keep the old version and effective date so historical figures are not silently compared under a new rule.`]},
      {heading:'Limitations and conclusion',paragraphs:[s.limit,`The evidence supports a narrow conclusion: ${s.finding.toLowerCase()} The useful next step for a FilipinoOutsource.com buyer is a small, dated sample with visible source links and owner decisions, not a benchmark borrowed from another queue.`,`Access, retention, professional review, and individual rights depend on the buyer's setting. Legal, accounting, clinical, employment, security, and commercial determinations stay with an authorized professional or client owner.`]},
    ],
    methodology:`Qualitative desk analysis applying official Philippine privacy guidance, NIST audit-control guidance, CISA account-security guidance, and PSA definition practices to five hypothetical ${s.cluster.toLowerCase()} records. No provider, worker, customer, or business outcome was measured.`,
    faq:[{q:'Does this research set a performance target?',a:'No. It proposes observable fields and limits; each buyer defines any target for its own queue.'},{q:'Can a coordinator resolve the exception?',a:'The coordinator can document and route it. The authorized client owner makes the consequential decision.'},{q:'What is the smallest useful test?',a:'Review five eligible records and one exception against original sources with a second reviewer.'}],sources,related:[{label:'Build a staffing plan',href:'/blog/Filipino-outsource-staffing-planning'},{label:'Review the onboarding checklist',href:'/blog/Filipino-outsource-staffing-onboarding-checklist'}]};
}

export const september7ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
