import type { ResearchPost } from './fleet-data';

type Study = Omit<ResearchPost, 'published' | 'datePublished' | 'readTime' | 'heroImage'>;
const checked = 'Accessed October 2, 2026';
const common = {
  published: 'October 2, 2026', datePublished: '2026-10-02', readTime: '13 minute read',
  heroImage: '/article-planning.svg'
} as const;

const studies: readonly Study[] = [
  {
    slug: 'philippines-outsourcing-sec-efast-filing-packet-research-2026',
    title: 'How Should an SEC eFAST Filing Packet Be Prepared?',
    excerpt: 'A primary-source study of annual-report document control, authorized-filer boundaries, submission evidence, reversion handling, and corporate-owner decisions.',
    cluster: 'Corporate Administration',
    cardHighlight: 'Treat document readiness, filing authority, portal submission, acceptance, and correction as different states.',
    keyTakeaways: ['Build the packet from owner-approved corporate records.', 'Never confuse an upload receipt with SEC acceptance.', 'Keep filer access narrower than document preparation.', 'Route reversion and legal interpretation to accountable owners.'],
    stats: [{label:'Packet states',value:'5',width:82},{label:'Boundary cases',value:'4',width:66},{label:'Decision owner',value:'1',width:42}],
    graphicCaption: 'A controlled path from approved corporate records to eFAST acceptance evidence.',
    sections: [
      {heading:'The buyer decision behind an eFAST support role',paragraphs:[
        'A company considering Philippines-based administrative support for SEC reporting should ask a narrower question than whether filing can be outsourced. The useful question is which preparation steps can be made repeatable without transferring corporate judgment or signatory authority. eFAST accepts annual financial statements, the General Information Sheet, and other covered reports from authorized filers. That makes the role operationally useful, but it also creates a boundary: assembling an approved packet is not the same act as deciding what the corporation must disclose.',
        'This study treats one reporting event as a chain of evidence. The chain begins with the legal entity and covered period, moves through the approved form and attachments, records the authorized filer and submission event, and ends only when the resulting portal state has been reviewed. Each link needs a source, version, owner, timestamp, and status. A generic task marked filed hides the very distinctions that matter when a document is reverted, uploaded under the wrong entity, or accepted with the wrong period.',
        'For a buyer, the staffing implication is concrete. A coordinator can maintain a calendar, request approved inputs, run format checks, name files, stage documents, record portal responses, and chase an assigned correction. Corporate officers, counsel, accountants, and authorized signatories retain responsibility for report selection, substantive accuracy, certification, approval, and any conclusion about legal compliance. Access should be granted only after those responsibilities are written into the workflow.'
      ]},
      {heading:'What the SEC sources establish',paragraphs:[
        'The SEC eFAST FAQ describes the service as an online submission tool for Annual Financial Statements, General Information Sheets, and other covered annual reports. It also identifies authorized filers as the people who submit through registered accounts. The current user guide adds a crucial control point: the authorized filer and document signatories are responsible for accuracy and completeness, and the required file format depends on the report. Those statements support a preparation role, but they do not authorize a coordinator to certify content.',
        'The SEC reportorial-requirements page separates document types and due-date rules. It also reflects newer routing, including the use of HARBOR for beneficial-ownership declarations and the 2026 GIS version. This matters because an old checklist can be internally consistent and still send the wrong document to the wrong system. A durable desk procedure therefore stores the controlling SEC page, date checked, entity classification supplied by the owner, covered period, selected report, due-date decision, and destination decision.',
        'The portal guidance also distinguishes a submitted record from an accepted one and publishes material about avoiding reversion. Operational analysis follows from that distinction: the coordinator should capture the upload identifier and response without asserting acceptance, then return later under an approved schedule to capture the actual status. If the system reports a reversion or mismatch, the worker preserves the message verbatim and routes it; they do not silently alter a signed document to make the portal accept it.'
      ]},
      {heading:'Designing the filing packet',paragraphs:[
        'Start with a cover record containing exact corporate name, SEC registration number, report type, reporting period, fiscal year end, approved due date, filing channel, source links, accountable officer, preparer, reviewer, authorized filer, and signatory set. Reference protected documents by controlled location instead of duplicating them into open tickets. A version label should change whenever an approved field, signature page, attachment, or conversion output changes. The final upload candidate must be reproducible from the recorded inputs.',
        'Run mechanical checks separately from substantive review. Mechanical checks can test file type, size, naming, page count, legibility, orientation, presence of required pages, period labels, and consistency between the cover record and visible document identifiers. Substantive review asks whether facts, classifications, figures, disclosures, signatures, and certifications are correct. The coordinator may report a discrepancy found by comparison, but the responsible officer or professional decides the correction and approves the replacement.',
        'Record five states: requested, owner-approved, staged, submitted, and portal-resolved. A packet is not ready because every file exists; it is ready when the designated owner approves the exact versions and the authorized filer is identified. It is not submitted because a browser upload reached one hundred percent; it is submitted when the system returns the relevant transaction evidence. It is not resolved because an email arrived; it is resolved when the reviewed portal status and any required correction are attached to the record.'
      ]},
      {heading:'Boundary scenario: a last-minute GIS change',paragraphs:[
        'Assume a GIS packet has signatures and appears ready. Hours before filing, the corporate secretary sends a new officer address in chat, while the approved source record still shows the earlier address. At the same time, the portal account lists a former employee as active filer. The coordinator should stop the affected steps, preserve both versions, ask the corporate owner which record controls, and require the filer-access owner to resolve account authority. The worker should not edit a signed form from chat or submit through the former employee.',
        'A focused escalation names the entity, period, form version, disputed field, competing sources, existing signatures, deadline, portal-account issue, action withheld, and requested decision. The answer must identify the approved value, whether a new document and signature are required, who may file, and whether the deadline plan changes. This is more useful than forwarding a long thread because it lets the owner see the decision surface without implying that the coordinator has already chosen.',
        'After resolution, the history remains. Do not overwrite the superseded packet or delete the access anomaly. Link the owner decision, regenerated file, new approval, account change, submission response, and final portal status. That evidence supports later review of what happened and helps improve the next cycle. It does not prove the report was legally sufficient; it proves that the administrative handoff followed the authorized decision.'
      ]},
      {heading:'A bounded test before scaling',paragraphs:[
        'Test the workflow on three completed filings and two exception cases, selected consecutively rather than chosen for cleanliness. For each, trace the calendar decision to the SEC source, source records to the approved document, approved document to the exact uploaded hash, authorized filer to the submission event, and portal response to the final owner review. Record exclusions before computing any completion measure. One missing evidence link is an exception even when the portal eventually shows accepted.',
        'Review failure modes qualitatively. Look for corporate details copied from an earlier year, wrong period labels, unapproved changes after signature, unreadable scans, stale filer access, uploads to the wrong entity, response emails without portal confirmation, and reverted documents closed as complete. Measure the age of unresolved decisions separately from preparation time. That prevents an approval delay from being blamed on the coordinator and prevents a fast upload from being celebrated when its underlying packet was wrong.',
        'Repeat the test whenever the SEC changes a form, destination, authentication method, report list, or portal behavior; whenever the corporation changes officers, fiscal year, signatories, or service providers; and whenever a filing produces an unexpected response. Past acceptance is evidence about one packet under one configuration. It is not permission to reuse an old answer without reviewing current requirements.'
      ]},
      {heading:'Method limits and accountable ownership',paragraphs:[
        'This is a qualitative desk review, not a filing opinion or test of a real corporation. It does not determine whether an entity must file, which form applies, when a deadline falls, whether a document is complete, whether a signature is valid, or what a portal status means for legal compliance. Those conclusions require current facts and the corporation’s authorized professionals. The sources were checked on October 2, 2026 and can change after that date.',
        'The narrow conclusion is operational: eFAST support is a reasonable administrative role when the buyer separates source collection, document approval, filer authority, submission, portal resolution, and correction evidence. A good role brief names the officer who owns report selection, the professional who owns substantive figures or disclosures, the person who approves the final document, the filer who performs submission, and the backup who handles exceptions.',
        'Buyers should reject a proposal that promises to take care of SEC compliance without naming these decisions. They should prefer a workflow that makes uncertainty visible, limits credentials, preserves exact versions, and treats a stop for missing authority as correct performance. That design gives an outsourced coordinator useful work while keeping corporate accountability with the people who actually hold it.'
      ]}
    ],
    table:{heading:'eFAST evidence gates',headers:['Gate','Evidence','Owner decision'],rows:[['Scope','entity, report, period, current SEC source','what must be filed'],['Packet','approved files, hashes, signatories','content is authorized'],['Submission','authorized filer, transaction response','release to portal'],['Resolution','portal status, reversion message','correction or closure']]},
    methodology:'Qualitative desk review of current SEC eFAST instructions, user guidance, and reportorial-requirements pages checked October 2, 2026. The method separated published facts from operating inferences and tested one hypothetical exception. No company account, filing, deadline, document, or acceptance result was examined.',
    faq:[{q:'Can a coordinator sign or certify the report?',a:'No. Signing, certification, substantive approval, and filing authority stay with the designated corporate owners.'},{q:'Does an upload receipt prove acceptance?',a:'No. Preserve the receipt and separately review the portal disposition and any reversion.'}],
    sources:[{name:`SEC eFAST FAQ (${checked})`,url:'https://efast.sec.gov.ph/faqs'},{name:`SEC eFAST User Guide (${checked})`,url:'https://efast.sec.gov.ph/user/static/media/user_guide_022825.2d5ac2ad.pdf'},{name:`SEC reportorial requirements for corporations with primary licenses (${checked})`,url:'https://www.sec.gov.ph/reportorial-requirements/corporations-with-primary-licenses/'}],
    related:[{label:'Review corporate records support',href:'/services/administrative-support'},{label:'Review document-version evidence research',href:'/research/philippines-outsourcing-document-version-evidence-research-2026'}],
    serviceHandoff:{heading:'Turn the filing calendar into a controlled queue',copy:'Define document sources, approval owners, filer access, portal evidence, and reversion escalation before assigning SEC administration.',label:'Review administrative support',href:'/services/administrative-support'}
  },
  {
    slug:'philippines-outsourcing-trademark-docket-control-research-2026', title:'What Should a Philippine Trademark Docket Control Preserve?',
    excerpt:'An IPOPHL-source workflow for separating deadline monitoring, document preparation, filing authority, payment evidence, and legal decisions.', cluster:'Legal Administration',
    cardHighlight:'A docket is useful when every deadline is tied to the mark, case state, controlling notice, owner, and evidence of action.',
    keyTakeaways:['Monitor without giving legal advice.','Tie each task to an official record or notice.','Separate filing acknowledgement, payment, and disposition.','Escalate classification and strategy decisions.'],
    stats:[{label:'Docket controls',value:'7',width:86},{label:'Test matters',value:'5',width:64},{label:'Legal owner',value:'1',width:38}], graphicCaption:'A trademark docket from official event to authorized action and verified evidence.',
    sections:[
      {heading:'Why trademark administration needs a narrower promise',paragraphs:[
        'Trademark work contains many tasks that look administrative: monitoring an inbox, saving notices, entering dates, preparing a standard form, uploading an approved document, recording payment, and checking whether a response appeared. Those tasks can support counsel and brand owners. They do not make the coordinator qualified to judge availability, ownership, classification, registrability, infringement, response strategy, evidence sufficiency, or whether a deadline can be extended.',
        'IPOPHL states that new and renewal trademark applications are filed online and that documents for registered marks and pending applications are transmitted through its electronic facilities. Its eTMfile material links application work to classification and search tools and describes electronic receipts after payment. These facts make a remote workflow possible, but the portal does not erase the difference between clerical execution and legal judgment.',
        'A buyer should therefore define the role around docket integrity. The worker makes the official event visible, connects it to the correct matter, alerts the named professional, prepares only approved materials, and preserves what the system returned. The accountable lawyer, agent, or rights owner chooses the legal action and approves its substance. The workflow succeeds when nobody has to infer authority from urgency.'
      ]},
      {heading:'Build one identity record for each mark',paragraphs:[
        'The core record should include the exact mark representation, application or registration number, applicant or registrant name, jurisdiction, classes, goods or services text, filing date, status as observed, representative, owner contact, controlled document location, and official-source link. Similar brand names must never be the only lookup key. A docket task that cannot be tied to the exact official identifier stays unresolved.',
        'Preserve changes as events rather than silently updating a profile. Ownership instructions, address changes, representative changes, class restrictions, declarations, renewals, notices, responses, payment events, and dispositions each receive their own source, received time, entered-by field, reviewer, and effective status. The current view may summarize the latest approved state, but the event history explains how it became current.',
        'Access also belongs in the matter record. Identify who may view confidential drafts, who may prepare a portal transaction, who may approve fees, who may submit, and who may communicate externally. Shared passwords and undocumented handoffs destroy attribution. Where the system supports named accounts, use them; where it does not, preserve an approved custody and review procedure.'
      ]},
      {heading:'Turn notices into reviewable deadlines',paragraphs:[
        'A coordinator should enter the notice date, source channel, exact document name, matter identifier, stated response date, rule or instruction cited in the notice, time zone where relevant, responsible professional, internal review date, and escalation date. The worker can transcribe a date and calculate a proposed internal reminder under a written rule. The professional must confirm the operative deadline and any extension, grace period, consequence, or strategic choice.',
        'Use two-person review for newly entered consequential dates. The second reviewer opens the source notice rather than checking another spreadsheet cell. They confirm the matter, event, visible date, and cited basis, then record the review. Calendar reminders should contain the matter identifier and controlled link, not sensitive attachments. A missed or ambiguous source immediately becomes an exception instead of a guessed date.',
        'Monitoring needs a declared perimeter. List the official portals, designated email addresses, physical correspondence route, counsel channels, and owner messages that feed the docket. Name who checks each channel, how often, what happens during leave, and how a failed login is escalated. A dashboard cannot demonstrate complete monitoring if an unlisted mailbox holds the actual notice.'
      ]},
      {heading:'Prepare online transactions without choosing the law',paragraphs:[
        'For an approved filing, stage the selected transaction type, exact matter, owner-approved form, attachments, filenames, fee estimate, payer, approval evidence, submitter, and release window. Compare the staged screen with the instruction before release. Do not choose a class, narrow goods, make a declaration, select an applicant, respond to an examiner, or abandon a right based on what seems conventional. Those choices can change legal scope.',
        'After submission, capture the acknowledgement, transaction number, submitted document hash, timestamp, payment instruction, payment result, electronic receipt, and later status as separate evidence. IPOPHL notes that official receipts may arrive after payment; this supports a follow-up state rather than immediate closure. A screenshot saying successful should be linked to the exact transaction, not stored as an unlabeled image in a shared folder.',
        'When a portal rejects a file, shows duplicate transactions, or produces conflicting states, preserve the error and stop. The coordinator may check format and approved retry instructions. They should not submit multiple identical applications to solve uncertainty. IPOPHL guidance specifically addresses inadvertent duplicate filings, which illustrates why the record must distinguish an attempted upload from the application the owner intends to pursue.'
      ]},
      {heading:'Boundary case: similar marks, different owners',paragraphs:[
        'Suppose two group companies use nearly identical marks. A renewal instruction names the brand but not the registration number, and the folder contains specimens for both entities. The portal search also shows a pending application with a related logo. A rushed worker might select the first match and upload the available specimen. A controlled workflow blocks because the matter identity, owner, registration, and approved evidence are not unambiguous.',
        'The escalation should present the instruction, candidate identifiers, owner names, classes, current states, source links, deadline flagged for professional confirmation, and action withheld. It should ask the rights owner or counsel to identify the matter, transaction, approved documents, submitter, and fee authorization. It should not offer a legal recommendation disguised as a clerical question.',
        'Once answered, the coordinator updates the event record, not the legal conclusion. If counsel supplies a new deadline or strategy, record counsel as source and the scope of that instruction. If the wrong matter was previously touched, preserve the attempted action and remediation. Clean history is more useful than an apparently perfect docket whose mistakes were erased.'
      ]},
      {heading:'Testing the docket and stating its limits',paragraphs:[
        'Select five consecutive matters covering at least one new application, one renewal or post-registration event, one official notice, one payment, and one exception if they occur. Trace each official event through identity matching, deadline review, owner instruction, staged transaction, submission evidence, payment evidence, and follow-up. Do not claim an accuracy percentage from a handpicked sample. Report missing links and the reason each matter was excluded.',
        'Look for repeated paragraphs or default reasoning in the operating record as well as missed fields. If every escalation says please advise, the workflow is not doing enough analysis. Each case should identify its own ambiguity and requested decision. Conversely, a detailed administrative note must not cross into a legal conclusion. Quality means relevant facts, controlled sources, and a clean handoff to the qualified owner.',
        'This study does not determine any trademark right, deadline, filing requirement, fee, class, registrability question, response, or remedy. No live IPOPHL account or matter was tested. Official pages and portal behavior can change after the October 2, 2026 review. Recheck current instructions and use qualified Philippine trademark counsel for legal decisions. The defensible conclusion is limited: disciplined docket support can reduce lost context while authority stays with the rights owner and professional adviser.'
      ]}
    ],
    table:{heading:'Trademark docket chain',headers:['Event','Coordinator record','Reserved decision'],rows:[['Notice','source, matter, received time','legal meaning and deadline'],['Preparation','approved form and attachments','substance and strategy'],['Submission','transaction and file hashes','authority to file'],['Follow-up','payment, receipt, status','response or closure']]},
    methodology:'Desk review of IPOPHL trademark filing, online-service, and advisory materials checked October 2, 2026. The analysis mapped official portal events to administrative controls and challenged the map with a two-owner ambiguity. It did not test a live matter or provide legal advice.',
    faq:[{q:'Can an assistant calculate and own trademark deadlines?',a:'They may transcribe and propose reminders under written rules, but a qualified owner must confirm consequential deadlines.'},{q:'Is a payment confirmation the final matter status?',a:'No. Preserve payment and receipt evidence, then monitor the official matter state under the approved plan.'}],
    sources:[{name:`IPOPHL trademark filing guidance (${checked})`,url:'https://www.ipophil.gov.ph/trademark/filing/'},{name:`IPOPHL eTMfile service page (${checked})`,url:'https://www.ipophil.gov.ph/etm-file-trademark/'},{name:`IPOPHL online filing advisories (${checked})`,url:'https://www.ipophil.gov.ph/advisories/'}],
    related:[{label:'Review administrative support',href:'/services/administrative-support'},{label:'Review deadline-source control research',href:'/research/philippines-outsourcing-deadline-source-control-research-2026'}],
    serviceHandoff:{heading:'Define the docket perimeter before assigning monitoring',copy:'Name official channels, matter identifiers, legal reviewers, filing authority, payment approval, and exception routes.',label:'Review administrative support',href:'/services/administrative-support'}
  },
  {
    slug:'philippines-outsourcing-bir-2307-certificate-reconciliation-research-2026', title:'How Should BIR Form 2307 Certificates Be Reconciled?',
    excerpt:'A BIR-source analysis of payee identity, income-payment lines, tax withheld, certificate delivery, alphalist matching, and tax-owner review.', cluster:'Finance Operations',
    cardHighlight:'Reconcile every certificate to approved transactions and withholding records before treating it as complete.',
    keyTakeaways:['Match payor, payee, period, ATC, payment, and tax.','Keep calculation and tax treatment with qualified owners.','Track issuance and delivery independently.','Preserve corrections instead of replacing history.'],
    stats:[{label:'Match fields',value:'8',width:88},{label:'Exception tests',value:'5',width:61},{label:'Tax owner',value:'1',width:39}], graphicCaption:'A certificate-level bridge between approved transactions, withholding records, and recipient evidence.',
    sections:[
      {heading:'The operational question is certificate integrity',paragraphs:[
        'BIR Form 2307 is a Certificate of Creditable Tax Withheld at Source. The form identifies a period, payee, payor, income payments, codes, and tax withheld. BIR guidance explains that it is issued to recipients of income subject to expanded withholding tax and can support the recipient’s tax-credit record. Because the certificate carries consequences for two parties, generating a PDF is not an adequate definition of completion.',
        'A Philippines-based finance support role can organize approved transactions, compare certificate fields with controlled ledgers, prepare a draft from tax-owner instructions, route it for approval, track issuance, and record delivery. The role should not decide whether withholding applies, select an ATC, determine a rate, classify income, alter a tax return, authorize a signature, or advise a payee how to claim a credit. Those judgments belong to the taxpayer’s qualified owner.',
        'The buyer decision is whether enough structure exists to separate those activities. If the source ledger, tax decision, certificate preparation, approval, issuance, and recipient delivery are all bundled into one task, neither review nor escalation is reliable. A useful operating model gives each certificate a traceable identity and shows which step remains open.'
      ]},
      {heading:'Translate the official form into a control record',paragraphs:[
        'Capture certificate period, payee registered name, payee TIN and branch code as supplied by the approved master, registered address, payor name and TIN, income-payment date or covered period, nature of income, ATC selected by the tax owner, approved tax rate, income amount, tax withheld, source transactions, certificate version, preparer, reviewer, signatory, issue date, delivery channel, and receipt evidence. Mask sensitive identifiers in general queues.',
        'The official form’s monthly breakdown means a quarterly total should be reconstructable rather than pasted from an aggregate. Tie each amount to the approved accounts-payable or payment record and the withholding schedule used for remittance. A zero in one month and an amount in another may be valid, but it needs the underlying transaction chronology. Arithmetic agreement is necessary; it does not establish correct tax treatment.',
        'BIR Form 1604-E includes an alphalist schedule for payees subject to expanded withholding tax declared and certified using Form 2307. This creates a valuable cross-check: payee identity, ATC, income payment, rate, and tax on issued certificates should reconcile with the owner-approved annual information record. A mismatch becomes an exception for the tax owner, not an invitation for the coordinator to make the datasets agree by editing whichever is easier.'
      ]},
      {heading:'Run three reconciliations, not one',paragraphs:[
        'The first reconciliation is transactional. Compare every certificate line with approved payments or accrual instructions, vendor master identity, and the tax-owner classification. Check duplicate source references, reversals, credit notes, split periods, and late-posted transactions. Preserve the denominator: list all candidate transactions and document why an item was included, excluded, or deferred. Otherwise a balanced certificate may conceal an omitted invoice.',
        'The second reconciliation is remittance-facing. Link the certificate totals to the applicable withholding schedules and owner-approved filing evidence without asserting that a certificate alone proves remittance. Differences can arise from timing, adjustment, cancellation, or source errors. Record the reason and owner decision at line level. Do not mark resolved merely because the grand total matches after unrelated positives and negatives offset each other.',
        'The third reconciliation is recipient-facing. Verify the approved payee contact, controlled delivery method, exact certificate hash, sent time, returned-mail or failed-delivery state, recipient query, and replacement history. A generated certificate that never reaches the intended payee is not an effective handoff. A delivered certificate with the wrong TIN is worse because it spreads an error and personal or tax information.'
      ]},
      {heading:'Boundary case: one payment, two vendor profiles',paragraphs:[
        'Consider a professional-services payment booked to a vendor profile using a trade name. A second profile contains the registered name and a different branch code. The invoice, payment advice, and prior certificate do not agree, while the accounts-payable total and withheld amount balance. The coordinator should quarantine the draft, show the competing identity sources, and ask the vendor-master and tax owners to confirm the correct payee data and treatment.',
        'The escalation packet should contain masked identifiers, source record references, period, payment, candidate names, candidate TIN endings, prior certificate reference, ATC instruction, amount, tax, deadline, recipient contact, and action withheld. It should request an approved master correction and tax decision. It should not ask the recipient to pick a number informally or reuse last quarter solely because that certificate was accepted without complaint.',
        'When the owners decide, preserve the incorrect draft, correction authorization, updated master evidence, regenerated hash, approval, issued copy, delivery, and any alphalist or schedule update. The history explains why the certificate changed. Replacing the file under the same name without a version trail may make the folder look tidy, but it prevents the reviewer from proving which document was actually sent.'
      ]},
      {heading:'Test the queue with exception-heavy cases',paragraphs:[
        'Choose five consecutive payees around a quarter boundary and include a credit note, identity change, split payment, corrected tax instruction, or failed delivery if one occurs naturally. For every certificate, trace candidate transactions to the tax-owner instruction, draft fields, arithmetic review, signatory approval, issued hash, delivery evidence, and corresponding schedule line. State exclusions before reporting completeness.',
        'Inspect the reasoning, not only the field population. A worker who copies a code from the previous certificate may fill every box while missing a changed transaction. A reviewer who compares only totals may overlook swapped payees. The test should ask why each line exists, which controlled source supports it, and which qualified owner made the classification. Unanswered questions remain open even when a filing deadline is near.',
        'Useful measures include certificates ready for owner review, certificates waiting on identity decisions, line-level differences, corrected certificates, delivery failures, and age since the next owner received a complete question. Do not publish a tax accuracy rate from this sample. The workflow test evaluates evidence discipline, not tax compliance, recipient entitlement, or the overall quality of the accounting records.'
      ]},
      {heading:'Limits and buyer conclusion',paragraphs:[
        'This study reviewed current BIR form pages, the January 2018 Form 2307 layout, and the 1604-E alphalist format on October 2, 2026. It did not examine a taxpayer, return, payment, certificate, recipient claim, or BIR account. Forms, platforms, instructions, deadlines, rates, codes, and interpretations may change. A qualified tax professional must determine the treatment for real transactions.',
        'The operating conclusion is narrower. Certificate preparation can be delegated when the organization already has approved identity data, transaction records, tax decisions, signatory authority, secure delivery, and exception owners. Without those inputs, an assistant is being asked to invent tax treatment or repair master data under deadline pressure. That is not a reasonable administrative boundary.',
        'A buyer should look for a role design that exposes disagreement early, protects TINs and financial records, retains exact versions, and separates throughput from owner wait time. The best outcome is not the fastest stack of PDFs. It is a set of certificates whose fields can be reconstructed from approved evidence and whose unresolved questions remain visible to the people authorized to answer them.'
      ]}
    ],
    table:{heading:'Form 2307 reconciliation layers',headers:['Layer','Evidence','Stop condition'],rows:[['Transaction','approved payment and vendor identity','missing or duplicate source'],['Tax','owner-approved ATC, rate, withholding','classification unresolved'],['Certificate','field review, approval, issued hash','identity or amount mismatch'],['Delivery','recipient, channel, receipt','failed or wrong recipient']]},
    methodology:'Qualitative review of BIR Form 2307, BIR certificate guidance, and Form 1604-E schedules checked October 2, 2026. The method mapped form fields to transaction, tax, issuance, and delivery evidence and tested a conflicting-vendor case. It is not tax advice.',
    faq:[{q:'Can a support worker choose the ATC or withholding rate?',a:'No. The qualified tax owner supplies and approves tax treatment; the worker may record and compare that instruction.'},{q:'Is a generated PDF complete?',a:'No. It still requires approval, authorized issuance, secure delivery, and reconciliation with controlled records.'}],
    sources:[{name:`BIR Form 2307 PDF (${checked})`,url:'https://bir-cdn.bir.gov.ph/local/pdf/2307%20Jan%202018%20ENCS%20v3.pdf'},{name:`BIR certificates and filing guidance (${checked})`,url:'https://www.bir.gov.ph/bir-forms?datasetCode=3381&idTag=BIR2304&label=2304&tab=Certificates&type=TAB+LINK'},{name:`BIR Form 1604-E alphalist schedule (${checked})`,url:'https://efps.bir.gov.ph/efps-war/EFPSWeb_war/forms/1604E/1604e_v2_02.xhtml'}],
    related:[{label:'Review bookkeeping support',href:'/services/bookkeeping-support'},{label:'Review withholding-tax handoff research',href:'/research/philippines-outsourcing-compensation-withholding-tax-handoff-research-2026'}],
    serviceHandoff:{heading:'Design a certificate queue around approved tax decisions',copy:'Define transaction sources, tax owners, review, signatures, delivery evidence, and correction history before delegating preparation.',label:'Review bookkeeping support',href:'/services/bookkeeping-support'}
  },
  {
    slug:'philippines-outsourcing-data-sharing-register-research-2026', title:'How Should an Outsourced Data-Sharing Register Work?',
    excerpt:'An NPC-source operating model for purpose, parties, data categories, recipients, access, retention, complaints, and termination evidence.', cluster:'Privacy Operations',
    cardHighlight:'A contract index becomes useful only when it controls the actual data flows and decisions it describes.',
    keyTakeaways:['Map each arrangement to a real purpose and flow.','Separate controllers, processors, recipients, and access users.','Track change and termination obligations.','Keep lawful-basis and risk decisions with privacy owners.'],
    stats:[{label:'Register fields',value:'12',width:90},{label:'Flow tests',value:'5',width:62},{label:'Privacy owner',value:'1',width:41}], graphicCaption:'A living register connecting an approved arrangement to systems, recipients, and lifecycle evidence.',
    sections:[
      {heading:'A register is not a folder of signed agreements',paragraphs:[
        'The National Privacy Commission defines a data sharing agreement as a contract, joint issuance, or similar document containing the terms of a sharing arrangement between personal information controllers. NPC Circular No. 2020-03 addresses these arrangements, and current NPC guidance lists expected elements such as purpose, parties, data types, processing, security, duration, rights handling, retention or disposal, online-access details, complaint responsibility, and return or destruction.',
        'A buyer may use Philippines-based privacy operations support to maintain records and coordinate evidence. The worker can index an approved agreement, map named systems, request owner attestations, track review dates, record recipient confirmations, and prepare an exception packet. The worker cannot decide lawful basis, controller status, necessity, proportionality, contract sufficiency, security adequacy, data-subject response, or whether a new flow is permitted.',
        'The practical research question is how to make the register describe operations rather than paperwork. A signed PDF can remain current in a folder while teams add fields, recipients, APIs, exports, or purposes that were never reviewed. The register should therefore connect the approved arrangement to a testable flow and produce a stop when reality no longer matches the recorded scope.'
      ]},
      {heading:'Model the arrangement at purpose level',paragraphs:[
        'Create one record for each approved purpose, even when a master agreement covers several services. Include agreement identifier, parties and declared roles, business owner, privacy owner, purpose, data-subject groups, data categories, sensitive categories, source systems, destination systems, named recipients, processors involved, transfer method, frequency, approximate volume, geography, security reference, retention rule, disposal or return method, rights contact, complaint owner, start, review, expiry, and termination state.',
        'Purpose-level records prevent a broad customer-data label from hiding unrelated operations. Contact details used for order delivery, purchase history used for analytics, support transcripts used for quality review, and identity documents used for account recovery have different recipients and risks. A coordinator can document the owner’s approved map and compare observed fields with it. The privacy owner decides whether each flow is lawful and necessary.',
        'Represent uncertainty explicitly. Use states such as source not confirmed, recipient role under review, field list incomplete, retention evidence missing, security control awaiting owner, and termination pending. Do not replace uncertainty with a blank or assume that a contract clause answers a technical question. A visible unknown gives the accountable owner something actionable; a completed checkbox may let an uncontrolled flow continue.'
      ]},
      {heading:'Connect contract language to system evidence',paragraphs:[
        'For scheduled review, obtain an export of configured integrations, recipient accounts, service users, shared locations, and data fields from system owners under approved access. Compare that evidence with the register’s scope. The coordinator should not browse unrestricted personal data to prove a flow. Metadata, configuration, controlled samples, and owner attestations can often answer the operational question with less exposure.',
        'Online access requires special clarity in NPC guidance: the justification, parties granted access, data made accessible, estimated frequency and volume, and technical method should be specified. Translate those elements into account groups, permission levels, API scopes, export schedules, and monitoring evidence. If an agreement says limited access but a system group grants broad download rights, record the mismatch and escalate rather than rewriting the register to match the system.',
        'Retention and exit deserve equal attention. Record the trigger, period supplied by the privacy owner, systems and backups in scope, legal or operational holds, return requirement, destruction method, responsible party, due date, evidence expected, and residual-copy decision. A recipient email saying deleted is a statement, not automatically sufficient evidence. The owner defines what verification is appropriate and whether an exception can close.'
      ]},
      {heading:'Boundary case: a helpful analytics export',paragraphs:[
        'Imagine a marketing manager asks an analyst to send customer order data to a new dashboard vendor for a one-week experiment. The current register covers campaign delivery to a different provider and lists email address and campaign response, not purchase detail. The new vendor offers a secure upload link and the manager says the data will be deleted after the test. Security features and business urgency do not establish that the new purpose and recipient are approved.',
        'The coordinator should preserve the request, identify the proposed purpose, fields, subjects, source, recipient, transfer method, access users, duration, deletion promise, existing arrangement, and mismatch. They should stop the transfer and ask the privacy and business owners whether a new or amended arrangement, assessment, notice, contract, or system control is required. They should not negotiate privacy terms or decide that pseudonymization solves the issue.',
        'If approved, the record must link the owner decision, executed documents, final field list, approved users, transfer event, monitoring, and exit evidence. If rejected, record that outcome and ensure no staged file remains accessible. The useful reader outcome is not a universal rule against experiments; it is a repeatable way to surface a changed flow before personal data moves.'
      ]},
      {heading:'Audit flows, not document counts',paragraphs:[
        'Select five active arrangements across different purposes or systems. For each, trace one approved purpose from source fields to transfer method, recipient, access users, downstream location, retention state, rights contact, and termination route. Compare current configuration with the register and agreement. Record exactly which evidence was checked, the date, owner, limits, and unresolved differences. Do not infer that unobserved systems are compliant.',
        'Run a change test as well. Ask whether a new field, recipient, processor, API scope, country, frequency, volume, use case, retention period, or complaint route would trigger owner review. Use a hypothetical change and follow the actual escalation path. If staff can add a recipient without creating a review event, the register is retrospective documentation rather than an operating control.',
        'Quality measures should include arrangements reviewed, flows mapped, mismatches by type, overdue owner decisions, exit evidence missing, and stopped unapproved changes. Avoid a percentage called compliant unless a qualified owner has defined its basis and scope. The coordinator reports evidence and exceptions; the accountable privacy team makes compliance conclusions.'
      ]},
      {heading:'Limitations and a buyer-ready conclusion',paragraphs:[
        'This article is a qualitative interpretation of NPC public materials checked October 2, 2026. It does not decide whether an activity is data sharing, identify the parties’ legal roles, establish a lawful basis, draft an agreement, assess security, or determine retention and data-subject obligations. No agreement, organization, system, or personal-data flow was inspected. Privacy counsel and responsible officers must apply current rules to actual facts.',
        'The evidence supports a bounded conclusion: an outsourced coordinator can keep the operational record current when owners have already defined the arrangement and when technical teams can provide controlled evidence. The role creates value by revealing drift, missed reviews, unresolved exits, and unclear ownership. It becomes unsafe when the worker is expected to approve a new flow or convert incomplete information into a compliance assurance.',
        'A strong buyer brief names the controller representatives, data protection officer, security reviewer, business owner, system owner, contract owner, rights contact, and escalation backup. It limits access to what the review needs and separates facts, analysis, decision, and execution. That structure makes the register useful for daily operations without presenting administrative maintenance as professional privacy advice.'
      ]}
    ],
    table:{heading:'Data-sharing register review',headers:['Dimension','Recorded evidence','Owner question'],rows:[['Purpose','approved use and subject group','is the purpose permitted?'],['Flow','fields, systems, recipient, method','does reality match scope?'],['Lifecycle','review, retention, return or disposal','what closes the arrangement?'],['Rights','contact, complaint and request route','who is accountable?']]},
    methodology:'Qualitative desk review of NPC Circular No. 2020-03, current NPC data-security guidance, and the NPC issuances index checked October 2, 2026. The method mapped published agreement elements to system evidence and tested an unapproved analytics export. No legal or security assessment was performed.',
    faq:[{q:'Does every vendor relationship require the same agreement?',a:'No. The responsible privacy and legal owners must determine the parties, activity, basis, and documentation required.'},{q:'Can the register owner approve a new data flow?',a:'Not merely by maintaining the register. Approval must come from the accountable business, privacy, legal, and security roles.'}],
    sources:[{name:`NPC Circular No. 2020-03 on Data Sharing Agreements (${checked})`,url:'https://privacy.gov.ph/wp-content/uploads/2021/01/Circular-Data-Sharing-Agreement-amending-16-02-21-Dec-2020-clean-copy-FINAL-LYA-and-JDN-signed-minor-edit.pdf'},{name:`NPC Data Security guidance (${checked})`,url:'https://privacy.gov.ph/data-security/'},{name:`NPC advisories and circulars index (${checked})`,url:'https://privacy.gov.ph/pips-and-pics/advisories-circulars/'}],
    related:[{label:'Review data processing support',href:'/services/data-processing-support'},{label:'Review consent withdrawal research',href:'/research/philippines-outsourcing-consent-withdrawal-operations-research-2026'}],
    serviceHandoff:{heading:'Make privacy ownership explicit before assigning maintenance',copy:'Define approved purposes, evidence access, review triggers, privacy decisions, and exit verification for each arrangement.',label:'Review data processing support',href:'/services/data-processing-support'}
  },
  {
    slug:'philippines-outsourcing-sales-promotion-permit-evidence-research-2026', title:'What Should a DTI Sales Promotion Permit Evidence Pack Contain?',
    excerpt:'A DTI-source framework for campaign classification questions, approved mechanics, permit references, publication controls, winner evidence, and closeout.', cluster:'Marketing Operations',
    cardHighlight:'Connect every public campaign asset to the approved mechanics and permit decision before launch.',
    keyTakeaways:['Inventory mechanics before creative production.','Keep permit applicability with qualified owners.','Version public assets against approved terms.','Track fulfillment and closeout evidence.'],
    stats:[{label:'Launch gates',value:'6',width:84},{label:'Asset tests',value:'5',width:63},{label:'Campaign owner',value:'1',width:40}], graphicCaption:'An evidence path from proposed mechanics through owner approval, public assets, and campaign closeout.',
    sections:[
      {heading:'The launch question comes before the content queue',paragraphs:[
        'The DTI Fair Trade Enforcement Bureau explains that its Sales Promotion Division regulates promotional campaigns through permits. Its published elements include promotion of a brand, product, or service; an inducement involving gain or a chance of winning; a limited period; public communication; and consumer participants. DTI also provides online application and permit-search routes. These sources show why campaign administration cannot begin with a social post and add governance later.',
        'A Philippines-based marketing operations coordinator can collect owner-approved mechanics, maintain an asset register, prepare application evidence, compare creative with approved terms, record permit references, schedule approved materials, and preserve fulfillment records. The worker should not decide permit applicability, draft legal terms, substantiate a special claim, select winners outside approved mechanics, change an offer, or represent that a campaign complies.',
        'The buyer decision is whether the campaign process gives that coordinator authoritative inputs. If launch dates, audience, entry method, prize, geographic scope, channels, and terms shift in separate chats, no administrative checklist can produce a reliable public campaign. The evidence pack must establish one approved version and make every later change visible.'
      ]},
      {heading:'Describe mechanics before asking for assets',paragraphs:[
        'Create a campaign identity with legal sponsor, participating brands, products or services, objective, campaign type proposed by the owner, audience, geography, eligibility, start and end, entry steps, purchase condition if any, prize or benefit, quantity, value supplied by the owner, selection method, draw or determination date, notification, claim process, fulfillment, disqualification terms, complaint route, channels, agencies, data collected, privacy notice, and accountable approvers.',
        'Separate facts from classification. The coordinator may flag that the proposal includes a limited period, public advertising, consumer participation, and a promised gain because those are stated mechanics. The responsible legal or compliance owner decides whether DTI permit rules apply, which office or system is appropriate, what lead time controls, and what documents and wording are required. Record that decision with its source and conditions.',
        'Give mechanics a version and hash. Terms, application forms, creative briefs, landing-page copy, scripts, winner materials, and fulfillment records should reference that version. If a prize, date, channel, entry step, or geographic scope changes, reopen review rather than editing one asset. The core risk is divergence: a banner can be visually correct yet promise something different from the approved terms.'
      ]},
      {heading:'Build permit and publication gates',paragraphs:[
        'Use distinct states: concept, classification pending, application prepared, owner approved, submitted, permit decision recorded, assets reconciled, launch approved, live monitoring, winner or benefit fulfillment, and closed. A submission acknowledgement is not a permit. A permit reference is not proof that every asset matches. A scheduled post is not live evidence. Keeping the states separate prevents one successful step from closing the entire campaign.',
        'Before release, compare every public asset with the approved mechanic fields that it expresses: sponsor identity, offer, eligibility, period, entry route, prize, quantities, claim limits, required permit reference, material conditions, and links. Check the destination page and mobile rendering, not only the design file. The campaign owner decides whether wording is complete and whether a claim is substantiated; the coordinator records the approval and deployed asset hash.',
        'After publication, capture final URL or placement, first observed time, visible mechanics, linked terms, permit reference where required, image response, and responsible monitor. If an asset is wrong, preserve it, stop or correct under the owner’s instruction, and record the period affected. Silent replacement removes evidence needed to answer consumer questions and learn why the mismatch escaped review.'
      ]},
      {heading:'Boundary case: a prize changes after approval',paragraphs:[
        'Assume a campaign was prepared around ten identical vouchers. Inventory changes one day before launch, and the marketing lead proposes five larger vouchers with the same total value. Creative has already been approved and a permit decision refers to the earlier mechanics. Equal total value does not make the public promise, odds, winner count, or approved campaign identical. The coordinator should stop scheduling and route the proposed change.',
        'The escalation should identify the campaign, mechanics version, permit or classification decision, exact old and proposed prizes, quantity, winner impact, assets affected, planned start, vendors, data flows, and deadline. Ask the campaign and legal owners whether new approval, amended materials, authority contact, or schedule change is required. Do not revise fine print while leaving headline creative unchanged, and do not treat verbal approval as a complete change record.',
        'If the change is authorized, regenerate every affected artifact, obtain the required approvals, record new hashes, and verify scheduling. If it is rejected, confirm that old mechanics remain feasible or pause the campaign. This example gives buyers a specific reader outcome: the coordinator is not a permit expert, but a version-controlled workflow can stop a seemingly minor operational change from becoming a different public offer.'
      ]},
      {heading:'Follow the campaign through fulfillment',paragraphs:[
        'The evidence pack should not end at launch. Track eligible entries according to approved mechanics, restricted access to participant data, selection input and method, witnessed or system evidence required by the owner, winner validation, notification attempts, claim status, fulfillment, unclaimed outcomes, consumer questions, complaints, and final owner closeout. The coordinator executes documented steps; the authorized owner decides disputes and exceptions.',
        'Review five assets across different channels and five participant or fulfillment records selected consecutively. Trace each asset to the mechanics version and approval. Trace each selected record through eligibility evidence, determination, communication, and fulfillment without collecting unnecessary personal data. State exclusions and access limits. The sample tests workflow consistency, not fairness of the entire campaign or legal compliance.',
        'Useful measures include assets reconciled before launch, late changes, publication mismatches, participant records awaiting owner decision, failed notification, fulfillment aging, complaints, and unresolved closeout tasks. Do not use engagement, entries, or redemption as proof of compliance or consumer satisfaction. Those measures answer different business questions and can distract from whether the offer was executed as approved.'
      ]},
      {heading:'Sources, uncertainty, and role boundary',paragraphs:[
        'DTI public guidance checked October 2, 2026 describes the Sales Promotion Division, common promotion elements, online application through iRegIS for relevant campaigns, permit search, and consumer-protection context. The Consumer Act also addresses permits and substantiation of special claims. The exact classification, jurisdiction, procedure, documents, timing, exclusions, and campaign duties depend on current rules and actual mechanics.',
        'This article does not classify a campaign, secure a permit, interpret the Consumer Act, review advertising, validate a draw, decide a complaint, or provide legal advice. No live application, campaign, participant dataset, winner selection, or fulfillment was tested. The hypothetical case is invented. Buyers must use current DTI instructions and qualified Philippine legal or compliance advisers for consequential decisions.',
        'The limited conclusion is strong enough for staffing: campaign administration is delegable when the company supplies approved mechanics, a permit decision, controlled assets, publication authority, privacy rules, fulfillment instructions, and named exception owners. The coordinator’s value lies in keeping those pieces aligned. A proposal that transfers campaign compliance to an assistant without those decisions is not a complete operating model.'
      ]}
    ],
    table:{heading:'Promotion evidence lifecycle',headers:['Stage','Coordinator evidence','Owner authority'],rows:[['Design','mechanics version and asset inventory','classification and terms'],['Permit','application and official response','interpretation and approval'],['Launch','approved asset hashes and live checks','release decision'],['Closeout','selection, fulfillment, complaints','exceptions and closure']]},
    methodology:'Qualitative review of DTI-FTEB Sales Promotion Division guidance, sales-promotion FAQs, and the Consumer Act text checked October 2, 2026. The analysis mapped campaign mechanics to version and publication evidence and tested a changed-prize scenario. No campaign or permit was assessed.',
    faq:[{q:'Can a coordinator decide whether a permit is required?',a:'No. They can organize the facts and evidence, but the qualified owner must make and document that decision.'},{q:'Does a permit reference approve every creative asset?',a:'No. Each released asset still needs comparison with approved mechanics and owner authorization.'}],
    sources:[{name:`DTI-FTEB Sales Promotion Division (${checked})`,url:'https://fairtrade.dti.gov.ph/about/business-regulations/sales-promotion-division/'},{name:`DTI-FTEB sales promotion FAQs (${checked})`,url:'https://fairtrade.dti.gov.ph/stripped-sales-promo-faq/'},{name:`Consumer Act of the Philippines text hosted by DTI (${checked})`,url:'https://standardsph.dti.gov.ph/upload/upload/download?file=e4f8n8H2Sa3uc20230927651374470a596.pdf&path=storage%2Fuploads%2Fsdac%2Fpns%2Flaws_issuances%2F'}],
    related:[{label:'Review digital marketing support',href:'/services/digital-marketing-support'},{label:'Review content claim verification research',href:'/research/philippines-outsourcing-content-claim-verification-research-2026'}],
    serviceHandoff:{heading:'Build campaign controls before opening the content queue',copy:'Define mechanics, permit decisions, asset versions, publication approval, participant-data access, fulfillment, and exception owners.',label:'Review digital marketing support',href:'/services/digital-marketing-support'}
  }
];

export const october2ResearchPosts: readonly ResearchPost[] = studies.map((study) => ({...study, ...common}));
